In [4]:
!pip install -q copernicusmarine
import copernicusmarine

In [ ]:
copernicusmarine.login(check_credentials_valid=True)

INFO - 2026-09-29T16:46:38Z - Credentials file stored in /root/.copernicusmarine/.copernicusmarine-credentials.
INFO:copernicusmarine:Credentials file stored in /root/.copernicusmarine/.copernicusmarine-credentials.

True

In [6]:
import pandas as pd

df = pd.read_csv('/content/sample_data/harmful_algae_events.csv', low_memory=False)

valid_coords = (
    df["Latitude"].notna() & df["Longitude"].notna()
    & df["Latitude"].between(-90, 90)
    & df["Longitude"].between(-180, 180)
)
has_date = df[["Event Date", "Start Date"]].notna().any(axis=1)
not_freshwater = df["Freshwater"] == "No"
approved = df["Status"] == "Approved"

usable = df[valid_coords & has_date & not_freshwater & approved].copy()
usable["date"] = pd.to_datetime(usable["Event Date"].fillna(usable["Start Date"]))

sample = usable.sample(15, random_state=42)[["Event ID", "Country", "Latitude", "Longitude", "date"]]
sample

       Event ID           Country   Latitude   Longitude       date
4618      10562  FRENCH POLYNESIA -16.994000 -142.251000 2014-09-21
3667       5269  FRENCH POLYNESIA -17.178000 -150.244000 2016-12-29
7726       3871             CHINA  27.141091  120.470851 2008-05-01
12748       609          PORTUGAL  40.850000   -9.030000 1995-06-06
7215      11613  FRENCH POLYNESIA -24.150000 -149.060000 2009-07-02
1896       9625       PHILIPPINES   8.244100  126.375700 2020-08-25
10094      4618            POLAND  54.930000   17.290000 2004-07-31
13616       167            FRANCE  49.080000   -2.050000 1989-10-05
770       14104             SPAIN  36.910000   -7.090000 2023-07-26
7624       8951             SPAIN  42.100000   -9.320000 2009-05-01
9113       3531             JAPAN  38.190000  142.350000 2006-03-16
7141      11702  FRENCH POLYNESIA -17.178000 -150.244000 2009-02-14
7040       2114            CANADA  48.663611  -68.076667 2009-08-05
9524       3497             JAPAN  44.860000  143.490000 2005-04-26
2672       6965            CANADA  46.450000  -61.970000 2018-07-19

In [7]:
import copernicusmarine

ds = copernicusmarine.open_dataset(
    dataset_id="cmems_mod_glo_phy_my_0.083deg_P1D-m",
)

print(ds)
print("\nTime range:", ds.time.min().values, "to", ds.time.max().values)
print("\nVariables:", list(ds.data_vars))
print("\nDepth levels (first 10):", ds.depth.values[:10])
print("Lat/lon resolution:",
      float(ds.latitude[1] - ds.latitude[0]),
      float(ds.longitude[1] - ds.longitude[0]))

INFO - 2026-09-29T16:46:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T16:46:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

<xarray.Dataset> Size: 179TB
Dimensions:    (depth: 50, latitude: 2041, longitude: 4320, time: 12227)
Coordinates:
  * depth      (depth) float32 200B 0.494 1.541 2.646 ... 5.275e+03 5.728e+03
  * latitude   (latitude) float32 8kB -80.0 -79.92 -79.83 ... 89.83 89.92 90.0
  * longitude  (longitude) float32 17kB -180.0 -179.9 -179.8 ... 179.8 179.9
  * time       (time) datetime64[ns] 98kB 1993-01-01 1993-01-02 ... 2026-06-23
Data variables:
    bottomT    (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    mlotst     (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    siconc     (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    sithick    (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    so         (time, depth, latitude, longitude) float64 43TB dask.array<chunksize=(50, 2, 512, 2048), meta=np.ndarray>
    thetao     (time, depth, latitude, longitude) float64 43TB dask.array<chunksize=(50, 2, 512, 2048), meta=np.ndarray>
    uo         (time, depth, latitude, longitude) float64 43TB dask.array<chunksize=(50, 2, 512, 2048), meta=np.ndarray>
    usi        (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    vo         (time, depth, latitude, longitude) float64 43TB dask.array<chunksize=(50, 2, 512, 2048), meta=np.ndarray>
    vsi        (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
    zos        (time, latitude, longitude) float64 862GB dask.array<chunksize=(50, 512, 2048), meta=np.ndarray>
Attributes: (12/25)
    Conventions:               CF-1.4
    bulletin_date:             2021-07-07 00:00:00
    bulletin_type:             operational
    comment:                   CMEMS product
    domain_name:               GL12
    easting:                   longitude
    ...                        ...
    references:                http://www.mercator-ocean.fr
    source:                    MERCATOR GLORYS12V1
    title:                     daily mean fields from Global Ocean Physics An...
    z_max:                     5727.9169921875
    z_min:                     0.49402499198913574
    copernicusmarine_version:  2.5.0

Time range: 1993-01-01T00:00:00.000000000 to 2026-06-23T00:00:00.000000000

Variables: [np.str_('bottomT'), np.str_('mlotst'), np.str_('siconc'), np.str_('sithick'), np.str_('so'), np.str_('thetao'), np.str_('uo'), np.str_('usi'), np.str_('vo'), np.str_('vsi'), np.str_('zos')]

Depth levels (first 10): [ 0.494025  1.541375  2.645669  3.819495  5.078224  6.440614  7.92956
  9.572997 11.405    13.46714 ]
Lat/lon resolution: 0.08333587646484375 0.0833282470703125

In [ ]:
records = []
for _, row in sample.iterrows():
    point = ds.sel(
        latitude=row["Latitude"],
        longitude=row["Longitude"],
        time=row["date"],
        depth=0,
        method="nearest"
    )
    record = {
        "Event ID": row["Event ID"],
        "Country": row["Country"],
        "Latitude": row["Latitude"],
        "Longitude": row["Longitude"],
        "date": row["date"],
    }
    for var in ds.data_vars:
        record[var] = point[var].values.item()
    records.append(record)

result = pd.DataFrame(records)
result

,Event ID,Country,Latitude,Longitude,date,bottomT,mlotst,siconc,sithick,so,thetao,uo,usi,vo,vsi,zos
0,10562,FRENCH POLYNESIA,-16.994000,-142.251000,2014-09-21,1.898587,25.025179,NaN,NaN,36.510819,26.534349,-0.056154,0.0,-0.195929,0.0,0.678121
1,5269,FRENCH POLYNESIA,-17.178000,-150.244000,2016-12-29,1.308237,12.359997,NaN,NaN,35.906552,28.858394,-0.039674,NaN,0.050050,NaN,0.672628
2,3871,CHINA,27.141091,120.470851,2008-05-01,21.238044,7.782220,NaN,NaN,27.329325,21.276864,0.023804,0.0,0.034791,0.0,0.193487
3,609,PORTUGAL,40.850000,-9.030000,1995-06-06,13.441176,11.444442,NaN,NaN,35.413678,15.285470,-0.063478,0.0,-0.104984,0.0,-0.379345
4,11613,FRENCH POLYNESIA,-24.150000,-149.060000,2009-07-02,1.029908,60.884429,NaN,NaN,35.351115,23.173894,-0.081790,0.0,0.086062,0.0,0.679952
5,9625,PHILIPPINES,8.244100,126.375700,2020-08-25,29.622333,10.376294,NaN,NaN,34.322642,30.329142,0.270394,NaN,-0.355235,NaN,0.804773
6,4618,POLAND,54.930000,17.290000,2004-07-31,12.433332,10.528886,NaN,NaN,7.098605,18.620289,-0.070803,0.0,-0.012818,0.0,-0.098880
7,167,FRANCE,49.080000,-2.050000,1989-10-05,8.563829,17.853329,NaN,NaN,35.068819,8.574816,-0.010376,0.0,0.006714,0.0,-0.388195
8,14104,SPAIN,36.910000,-7.090000,2023-07-26,15.155828,10.986664,NaN,NaN,36.266671,22.314737,0.083010,NaN,-0.013428,NaN,-0.300913
9,8951,SPAIN,42.100000,-9.320000,2009-05-01,12.297098,11.749627,NaN,NaN,35.532701,14.260048,-0.023804,0.0,-0.087283,0.0,-0.386975
10,3531,JAPAN,38.190000,142.350000,2006-03-16,3.271187,10.528886,NaN,NaN,32.702109,4.536851,0.136113,0.0,0.014039,0.0,-0.109867
11,11702,FRENCH POLYNESIA,-17.178000,-150.244000,2009-02-14,1.273812,17.090366,NaN,NaN,36.085086,28.827631,-0.047609,0.0,-0.079348,0.0,0.639973
12,2114,CANADA,48.663611,-68.076667,2009-08-05,5.393811,10.528886,NaN,NaN,17.754143,15.437086,0.051271,0.0,0.003662,0.0,-0.363170
13,3497,JAPAN,44.860000,143.490000,2005-04-26,1.361705,10.528886,NaN,NaN,32.250435,1.528703,0.052492,0.0,-0.030519,0.0,-0.137028
14,6965,CANADA,46.450000,-61.970000,2018-07-19,15.336741,10.528886,NaN,NaN,27.913755,17.171514,-0.145268,NaN,-0.224616,NaN,-0.377514

In [ ]:
import copernicusmarine
import xarray as xr
import pandas as pd
from pathlib import Path
from datetime import timedelta
import time

tolerance = timedelta(hours=12)
records = []

for i, row in subset_range.iterrows():
    fname = f"cop_point_{row['Event ID']}.nc"

    if not Path(fname).exists():
        t0 = time.time()
        copernicusmarine.subset(
            dataset_id="cmems_mod_glo_phy_my_0.083deg_P1D-m",
            variables=["thetao", "so", "bottomT", "mlotst", "zos", "uo", "vo"],
            minimum_longitude=row["Longitude"] - 0.5, maximum_longitude=row["Longitude"] + 0.5,
            minimum_latitude=row["Latitude"] - 0.5, maximum_latitude=row["Latitude"] + 0.5,
            start_datetime=row["date"] - tolerance,
            end_datetime=row["date"] + tolerance,
            minimum_depth=0, maximum_depth=1,
            coordinates_selection_method="nearest",
            output_filename=fname,
        )
        print(f"Event {row['Event ID']} downloaded in {time.time()-t0:.1f} sec")
    else:
        print(f"Event {row['Event ID']} already cached, skipping download")

    point_ds = xr.open_dataset(fname)
    point = point_ds.sel(latitude=row["Latitude"], longitude=row["Longitude"], time=row["date"], method="nearest")

    record = {"Event ID": row["Event ID"], "Country": row["Country"],
              "Latitude": row["Latitude"], "Longitude": row["Longitude"], "date": row["date"]}
    for var in point_ds.data_vars:
        record[var] = point[var].values.item()
    records.append(record)

full_result = pd.DataFrame(records)
full_result["label"] = 1  # these are all positive (bloom) events
full_result.to_csv("haedat_copernicus_features.csv", index=False)

Event 14793 already cached, skipping download
Event 14805 already cached, skipping download
Event 14794 already cached, skipping download
Event 14795 already cached, skipping download
Event 14796 already cached, skipping download
Event 14797 already cached, skipping download
Event 14798 already cached, skipping download
Event 14806 already cached, skipping download
Event 14801 already cached, skipping download
Event 14799 already cached, skipping download
Event 14802 already cached, skipping download
Event 14800 already cached, skipping download
Event 14803 already cached, skipping download
Event 14804 already cached, skipping download

INFO - 2026-09-29T18:14:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:14:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14541 downloaded in 9.0 sec

INFO - 2026-09-29T18:14:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:14:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14629 downloaded in 8.4 sec

INFO - 2026-09-29T18:14:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:14:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14625 downloaded in 9.1 sec

INFO - 2026-09-29T18:14:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:14:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14348 downloaded in 9.1 sec

INFO - 2026-09-29T18:14:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:14:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14349 downloaded in 8.7 sec

INFO - 2026-09-29T18:14:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:14:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:14:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14652 downloaded in 8.6 sec

INFO - 2026-09-29T18:15:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14651 downloaded in 9.2 sec

INFO - 2026-09-29T18:15:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14649 downloaded in 9.0 sec

INFO - 2026-09-29T18:15:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14648 downloaded in 8.6 sec

INFO - 2026-09-29T18:15:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14647 downloaded in 8.8 sec

INFO - 2026-09-29T18:15:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:15:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14646 downloaded in 9.1 sec

INFO - 2026-09-29T18:15:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:15:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:15:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14645 downloaded in 14.5 sec

INFO - 2026-09-29T18:16:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14644 downloaded in 8.4 sec

INFO - 2026-09-29T18:16:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14643 downloaded in 8.9 sec

INFO - 2026-09-29T18:16:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14642 downloaded in 8.8 sec

INFO - 2026-09-29T18:16:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14641 downloaded in 8.6 sec

INFO - 2026-09-29T18:16:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14640 downloaded in 8.7 sec

INFO - 2026-09-29T18:16:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:16:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14639 downloaded in 8.5 sec

INFO - 2026-09-29T18:16:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:16:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:16:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14637 downloaded in 8.7 sec

INFO - 2026-09-29T18:17:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14636 downloaded in 8.6 sec

INFO - 2026-09-29T18:17:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14628 downloaded in 8.6 sec

INFO - 2026-09-29T18:17:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14623 downloaded in 8.8 sec

INFO - 2026-09-29T18:17:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14622 downloaded in 13.1 sec

INFO - 2026-09-29T18:17:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:17:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14621 downloaded in 8.9 sec

INFO - 2026-09-29T18:17:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:17:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:17:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14620 downloaded in 9.0 sec

INFO - 2026-09-29T18:18:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14653 downloaded in 8.9 sec

INFO - 2026-09-29T18:18:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14650 downloaded in 8.7 sec

INFO - 2026-09-29T18:18:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14638 downloaded in 8.8 sec

INFO - 2026-09-29T18:18:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14624 downloaded in 8.5 sec

INFO - 2026-09-29T18:18:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14626 downloaded in 8.6 sec

INFO - 2026-09-29T18:18:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:18:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14627 downloaded in 8.8 sec

INFO - 2026-09-29T18:18:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:18:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:18:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14346 downloaded in 10.6 sec

INFO - 2026-09-29T18:19:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14634 downloaded in 8.4 sec

INFO - 2026-09-29T18:19:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14632 downloaded in 8.8 sec

INFO - 2026-09-29T18:19:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14633 downloaded in 12.4 sec

INFO - 2026-09-29T18:19:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14631 downloaded in 8.7 sec

INFO - 2026-09-29T18:19:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:19:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14630 downloaded in 8.9 sec

INFO - 2026-09-29T18:19:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:19:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:19:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14655 downloaded in 8.7 sec

INFO - 2026-09-29T18:20:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14347 downloaded in 8.6 sec

INFO - 2026-09-29T18:20:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14654 downloaded in 8.5 sec

INFO - 2026-09-29T18:20:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14635 downloaded in 9.0 sec

INFO - 2026-09-29T18:20:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14678 downloaded in 8.5 sec

INFO - 2026-09-29T18:20:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14615 downloaded in 8.7 sec

INFO - 2026-09-29T18:20:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:20:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14686 downloaded in 8.5 sec

INFO - 2026-09-29T18:20:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:20:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:20:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14676 downloaded in 8.7 sec

INFO - 2026-09-29T18:21:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14614 downloaded in 8.8 sec

INFO - 2026-09-29T18:21:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14610 downloaded in 12.3 sec

INFO - 2026-09-29T18:21:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14616 downloaded in 8.9 sec

INFO - 2026-09-29T18:21:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14609 downloaded in 8.2 sec

INFO - 2026-09-29T18:21:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:21:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14702 downloaded in 8.8 sec

INFO - 2026-09-29T18:21:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:21:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:21:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14617 downloaded in 8.5 sec

INFO - 2026-09-29T18:22:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14677 downloaded in 8.8 sec

INFO - 2026-09-29T18:22:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14688 downloaded in 8.3 sec

INFO - 2026-09-29T18:22:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14675 downloaded in 8.7 sec

INFO - 2026-09-29T18:22:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14687 downloaded in 8.8 sec

INFO - 2026-09-29T18:22:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14689 downloaded in 8.2 sec

INFO - 2026-09-29T18:22:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:22:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14613 downloaded in 8.4 sec

INFO - 2026-09-29T18:22:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:22:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:22:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14680 downloaded in 8.2 sec

INFO - 2026-09-29T18:23:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14612 downloaded in 12.1 sec

INFO - 2026-09-29T18:23:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14611 downloaded in 8.5 sec

INFO - 2026-09-29T18:23:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14682 downloaded in 8.3 sec

INFO - 2026-09-29T18:23:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14674 downloaded in 8.7 sec

INFO - 2026-09-29T18:23:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14679 downloaded in 8.6 sec

INFO - 2026-09-29T18:23:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:23:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14683 downloaded in 8.3 sec

INFO - 2026-09-29T18:23:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:23:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:23:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14685 downloaded in 8.7 sec

INFO - 2026-09-29T18:24:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14684 downloaded in 8.7 sec

INFO - 2026-09-29T18:24:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14461 downloaded in 8.4 sec

INFO - 2026-09-29T18:24:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14435 downloaded in 8.6 sec

INFO - 2026-09-29T18:24:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14439 downloaded in 8.5 sec

INFO - 2026-09-29T18:24:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:24:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14454 downloaded in 8.8 sec

INFO - 2026-09-29T18:24:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:24:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:24:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14459 downloaded in 12.0 sec

INFO - 2026-09-29T18:25:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14666 downloaded in 8.9 sec

INFO - 2026-09-29T18:25:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14704 downloaded in 9.0 sec

INFO - 2026-09-29T18:25:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14705 downloaded in 8.2 sec

INFO - 2026-09-29T18:25:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14707 downloaded in 8.7 sec

INFO - 2026-09-29T18:25:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14708 downloaded in 8.4 sec

INFO - 2026-09-29T18:25:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:25:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14446 downloaded in 8.9 sec

INFO - 2026-09-29T18:25:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:25:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:25:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14691 downloaded in 8.6 sec

INFO - 2026-09-29T18:26:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14444 downloaded in 8.5 sec

INFO - 2026-09-29T18:26:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14445 downloaded in 8.9 sec

INFO - 2026-09-29T18:26:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14706 downloaded in 8.6 sec

INFO - 2026-09-29T18:26:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14436 downloaded in 8.1 sec

INFO - 2026-09-29T18:26:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14437 downloaded in 12.2 sec

INFO - 2026-09-29T18:26:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:26:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:26:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:26:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14438 downloaded in 8.3 sec

INFO - 2026-09-29T18:27:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14440 downloaded in 8.5 sec

INFO - 2026-09-29T18:27:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14441 downloaded in 8.1 sec

INFO - 2026-09-29T18:27:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14442 downloaded in 8.4 sec

INFO - 2026-09-29T18:27:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14448 downloaded in 8.6 sec

INFO - 2026-09-29T18:27:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14443 downloaded in 8.4 sec

INFO - 2026-09-29T18:27:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14447 downloaded in 8.4 sec

INFO - 2026-09-29T18:27:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:27:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:27:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:27:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14449 downloaded in 8.6 sec

INFO - 2026-09-29T18:28:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14450 downloaded in 8.3 sec

INFO - 2026-09-29T18:28:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14451 downloaded in 8.4 sec

INFO - 2026-09-29T18:28:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14452 downloaded in 8.6 sec

INFO - 2026-09-29T18:28:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14453 downloaded in 12.1 sec

INFO - 2026-09-29T18:28:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14455 downloaded in 8.3 sec

INFO - 2026-09-29T18:28:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:28:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14456 downloaded in 8.4 sec

INFO - 2026-09-29T18:28:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:28:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:28:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14457 downloaded in 8.9 sec

INFO - 2026-09-29T18:29:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14458 downloaded in 9.0 sec

INFO - 2026-09-29T18:29:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14460 downloaded in 8.3 sec

INFO - 2026-09-29T18:29:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14372 downloaded in 8.6 sec

INFO - 2026-09-29T18:29:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14607 downloaded in 8.6 sec

INFO - 2026-09-29T18:29:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14601 downloaded in 8.4 sec

INFO - 2026-09-29T18:29:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:29:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14602 downloaded in 8.2 sec

INFO - 2026-09-29T18:29:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:29:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:29:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14603 downloaded in 8.6 sec

INFO - 2026-09-29T18:30:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14604 downloaded in 8.1 sec

INFO - 2026-09-29T18:30:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14605 downloaded in 8.1 sec

INFO - 2026-09-29T18:30:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14606 downloaded in 12.8 sec

INFO - 2026-09-29T18:30:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14608 downloaded in 8.5 sec

INFO - 2026-09-29T18:30:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14667 downloaded in 8.7 sec

INFO - 2026-09-29T18:30:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:30:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:30:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:30:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14668 downloaded in 8.4 sec

INFO - 2026-09-29T18:31:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14669 downloaded in 8.4 sec

INFO - 2026-09-29T18:31:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14692 downloaded in 8.8 sec

INFO - 2026-09-29T18:31:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14690 downloaded in 8.3 sec

INFO - 2026-09-29T18:31:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14696 downloaded in 8.8 sec

INFO - 2026-09-29T18:31:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14697 downloaded in 8.4 sec

INFO - 2026-09-29T18:31:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14693 downloaded in 8.4 sec

INFO - 2026-09-29T18:31:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:31:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:31:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:31:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14694 downloaded in 8.7 sec

INFO - 2026-09-29T18:32:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14695 downloaded in 12.0 sec

INFO - 2026-09-29T18:32:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14699 downloaded in 8.2 sec

INFO - 2026-09-29T18:32:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14703 downloaded in 8.6 sec

INFO - 2026-09-29T18:32:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14698 downloaded in 8.4 sec

INFO - 2026-09-29T18:32:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14709 downloaded in 8.5 sec

INFO - 2026-09-29T18:32:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:32:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14700 downloaded in 8.3 sec

INFO - 2026-09-29T18:32:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:32:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:32:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14701 downloaded in 8.3 sec

INFO - 2026-09-29T18:33:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14713 downloaded in 8.3 sec

INFO - 2026-09-29T18:33:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14710 downloaded in 8.5 sec

INFO - 2026-09-29T18:33:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14711 downloaded in 8.3 sec

INFO - 2026-09-29T18:33:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14712 downloaded in 8.6 sec

INFO - 2026-09-29T18:33:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14747 downloaded in 8.5 sec

INFO - 2026-09-29T18:33:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:33:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:33:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14788 downloaded in 8.7 sec

INFO - 2026-09-29T18:33:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:33:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14772 downloaded in 13.9 sec

INFO - 2026-09-29T18:34:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14767 downloaded in 8.3 sec

INFO - 2026-09-29T18:34:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14776 downloaded in 8.3 sec

INFO - 2026-09-29T18:34:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14775 downloaded in 8.4 sec

INFO - 2026-09-29T18:34:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14771 downloaded in 8.4 sec

INFO - 2026-09-29T18:34:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:34:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14770 downloaded in 8.5 sec

INFO - 2026-09-29T18:34:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:34:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:34:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14789 downloaded in 8.5 sec

INFO - 2026-09-29T18:35:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14780 downloaded in 8.8 sec

INFO - 2026-09-29T18:35:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14769 downloaded in 8.4 sec

INFO - 2026-09-29T18:35:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14791 downloaded in 8.4 sec

INFO - 2026-09-29T18:35:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14790 downloaded in 8.4 sec

INFO - 2026-09-29T18:35:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14792 downloaded in 12.5 sec

INFO - 2026-09-29T18:35:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:35:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14777 downloaded in 8.4 sec

INFO - 2026-09-29T18:35:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:35:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:35:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14768 downloaded in 8.5 sec

INFO - 2026-09-29T18:36:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14774 downloaded in 8.4 sec

INFO - 2026-09-29T18:36:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14765 downloaded in 8.4 sec

INFO - 2026-09-29T18:36:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14773 downloaded in 8.5 sec

INFO - 2026-09-29T18:36:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14779 downloaded in 8.6 sec

INFO - 2026-09-29T18:36:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14766 downloaded in 8.6 sec

INFO - 2026-09-29T18:36:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:36:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14778 downloaded in 8.6 sec

INFO - 2026-09-29T18:36:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:36:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:36:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14781 downloaded in 8.2 sec

INFO - 2026-09-29T18:37:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14782 downloaded in 8.8 sec

INFO - 2026-09-29T18:37:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14784 downloaded in 8.1 sec

INFO - 2026-09-29T18:37:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14783 downloaded in 12.1 sec

INFO - 2026-09-29T18:37:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14763 downloaded in 8.5 sec

INFO - 2026-09-29T18:37:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:37:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14785 downloaded in 8.5 sec

INFO - 2026-09-29T18:37:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:37:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:37:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14764 downloaded in 8.6 sec

INFO - 2026-09-29T18:38:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14786 downloaded in 8.5 sec

INFO - 2026-09-29T18:38:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14787 downloaded in 8.7 sec

INFO - 2026-09-29T18:38:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14344 downloaded in 8.8 sec

INFO - 2026-09-29T18:38:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14345 downloaded in 8.4 sec

INFO - 2026-09-29T18:38:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14047 downloaded in 8.8 sec

INFO - 2026-09-29T18:38:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:38:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14211 downloaded in 8.3 sec

INFO - 2026-09-29T18:38:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:38:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:38:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14342 downloaded in 8.5 sec

INFO - 2026-09-29T18:39:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14343 downloaded in 8.6 sec

INFO - 2026-09-29T18:39:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14243 downloaded in 12.8 sec

INFO - 2026-09-29T18:39:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14663 downloaded in 8.7 sec

INFO - 2026-09-29T18:39:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14664 downloaded in 8.6 sec

INFO - 2026-09-29T18:39:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14660 downloaded in 8.9 sec

INFO - 2026-09-29T18:39:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:39:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:39:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:39:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14619 downloaded in 8.5 sec

INFO - 2026-09-29T18:40:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14661 downloaded in 9.1 sec

INFO - 2026-09-29T18:40:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14659 downloaded in 8.6 sec

INFO - 2026-09-29T18:40:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14658 downloaded in 8.9 sec

INFO - 2026-09-29T18:40:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14662 downloaded in 8.5 sec

INFO - 2026-09-29T18:40:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14657 downloaded in 8.6 sec

INFO - 2026-09-29T18:40:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:40:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14656 downloaded in 8.8 sec

INFO - 2026-09-29T18:40:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:40:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:40:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14272 downloaded in 8.9 sec

INFO - 2026-09-29T18:41:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14273 downloaded in 12.2 sec

INFO - 2026-09-29T18:41:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14267 downloaded in 9.2 sec

INFO - 2026-09-29T18:41:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14172 downloaded in 8.6 sec

INFO - 2026-09-29T18:41:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14058 downloaded in 8.5 sec

INFO - 2026-09-29T18:41:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14249 downloaded in 8.4 sec

INFO - 2026-09-29T18:41:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:41:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:41:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:41:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14073 downloaded in 8.8 sec

INFO - 2026-09-29T18:42:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14074 downloaded in 8.7 sec

INFO - 2026-09-29T18:42:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14274 downloaded in 8.5 sec

INFO - 2026-09-29T18:42:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14250 downloaded in 8.5 sec

INFO - 2026-09-29T18:42:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14251 downloaded in 8.6 sec

INFO - 2026-09-29T18:42:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14253 downloaded in 8.6 sec

INFO - 2026-09-29T18:42:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:42:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14252 downloaded in 8.4 sec

INFO - 2026-09-29T18:42:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:42:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:42:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14275 downloaded in 12.1 sec

INFO - 2026-09-29T18:43:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14071 downloaded in 8.8 sec

INFO - 2026-09-29T18:43:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14247 downloaded in 8.6 sec

INFO - 2026-09-29T18:43:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14259 downloaded in 8.6 sec

INFO - 2026-09-29T18:43:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14171 downloaded in 8.8 sec

INFO - 2026-09-29T18:43:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14170 downloaded in 8.5 sec

INFO - 2026-09-29T18:43:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:43:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14281 downloaded in 8.6 sec

INFO - 2026-09-29T18:43:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:43:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:43:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14280 downloaded in 8.5 sec

INFO - 2026-09-29T18:44:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14162 downloaded in 8.6 sec

INFO - 2026-09-29T18:44:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14049 downloaded in 8.5 sec

INFO - 2026-09-29T18:44:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14050 downloaded in 8.6 sec

INFO - 2026-09-29T18:44:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14051 downloaded in 9.0 sec

INFO - 2026-09-29T18:44:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:44:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14052 downloaded in 13.2 sec

INFO - 2026-09-29T18:44:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:44:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:44:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14053 downloaded in 8.8 sec

INFO - 2026-09-29T18:45:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14054 downloaded in 8.8 sec

INFO - 2026-09-29T18:45:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14055 downloaded in 8.5 sec

INFO - 2026-09-29T18:45:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14056 downloaded in 8.7 sec

INFO - 2026-09-29T18:45:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14173 downloaded in 8.7 sec

INFO - 2026-09-29T18:45:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14156 downloaded in 8.9 sec

INFO - 2026-09-29T18:45:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:45:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14157 downloaded in 8.6 sec

INFO - 2026-09-29T18:45:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:45:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:45:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14279 downloaded in 8.9 sec

INFO - 2026-09-29T18:46:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14070 downloaded in 9.0 sec

INFO - 2026-09-29T18:46:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14161 downloaded in 8.6 sec

INFO - 2026-09-29T18:46:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14283 downloaded in 8.9 sec

INFO - 2026-09-29T18:46:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14282 downloaded in 8.8 sec

INFO - 2026-09-29T18:46:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:46:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14160 downloaded in 12.8 sec

INFO - 2026-09-29T18:46:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:46:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:46:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14072 downloaded in 8.6 sec

INFO - 2026-09-29T18:47:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14159 downloaded in 8.4 sec

INFO - 2026-09-29T18:47:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14285 downloaded in 9.0 sec

INFO - 2026-09-29T18:47:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14048 downloaded in 8.8 sec

INFO - 2026-09-29T18:47:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14158 downloaded in 8.6 sec

INFO - 2026-09-29T18:47:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14277 downloaded in 8.5 sec

INFO - 2026-09-29T18:47:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:47:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14276 downloaded in 8.8 sec

INFO - 2026-09-29T18:47:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:47:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:47:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14270 downloaded in 8.7 sec

INFO - 2026-09-29T18:48:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14268 downloaded in 8.6 sec

INFO - 2026-09-29T18:48:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14266 downloaded in 8.9 sec

INFO - 2026-09-29T18:48:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14265 downloaded in 12.7 sec

INFO - 2026-09-29T18:48:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14264 downloaded in 8.6 sec

INFO - 2026-09-29T18:48:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:48:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14263 downloaded in 9.0 sec

INFO - 2026-09-29T18:48:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:48:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:48:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14262 downloaded in 8.7 sec

INFO - 2026-09-29T18:49:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14261 downloaded in 8.9 sec

INFO - 2026-09-29T18:49:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14260 downloaded in 8.6 sec

INFO - 2026-09-29T18:49:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14258 downloaded in 8.5 sec

INFO - 2026-09-29T18:49:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14257 downloaded in 8.7 sec

INFO - 2026-09-29T18:49:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14256 downloaded in 8.7 sec

INFO - 2026-09-29T18:49:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:49:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14057 downloaded in 8.7 sec

INFO - 2026-09-29T18:49:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:49:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:49:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14246 downloaded in 8.7 sec

INFO - 2026-09-29T18:50:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14255 downloaded in 9.1 sec

INFO - 2026-09-29T18:50:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14254 downloaded in 12.5 sec

INFO - 2026-09-29T18:50:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14169 downloaded in 8.5 sec

INFO - 2026-09-29T18:50:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14248 downloaded in 8.6 sec

INFO - 2026-09-29T18:50:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14245 downloaded in 8.6 sec

INFO - 2026-09-29T18:50:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:50:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:50:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:50:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14163 downloaded in 8.9 sec

INFO - 2026-09-29T18:51:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14075 downloaded in 8.6 sec

INFO - 2026-09-29T18:51:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14269 downloaded in 8.6 sec

INFO - 2026-09-29T18:51:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14271 downloaded in 8.6 sec

INFO - 2026-09-29T18:51:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14278 downloaded in 8.8 sec

INFO - 2026-09-29T18:51:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14284 downloaded in 8.6 sec

INFO - 2026-09-29T18:51:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:51:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14164 downloaded in 8.6 sec

INFO - 2026-09-29T18:51:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:51:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:51:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14165 downloaded in 8.9 sec

INFO - 2026-09-29T18:52:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14292 downloaded in 12.1 sec

INFO - 2026-09-29T18:52:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14291 downloaded in 8.6 sec

INFO - 2026-09-29T18:52:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14290 downloaded in 8.6 sec

INFO - 2026-09-29T18:52:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14289 downloaded in 8.6 sec

INFO - 2026-09-29T18:52:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14288 downloaded in 8.7 sec

INFO - 2026-09-29T18:52:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:52:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:52:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:52:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14287 downloaded in 8.8 sec

INFO - 2026-09-29T18:53:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14286 downloaded in 8.6 sec

INFO - 2026-09-29T18:53:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14206 downloaded in 8.7 sec

INFO - 2026-09-29T18:53:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14200 downloaded in 8.6 sec

INFO - 2026-09-29T18:53:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14202 downloaded in 8.5 sec

INFO - 2026-09-29T18:53:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14147 downloaded in 8.3 sec

INFO - 2026-09-29T18:53:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:53:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14237 downloaded in 8.3 sec

INFO - 2026-09-29T18:53:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:53:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:53:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14221 downloaded in 11.8 sec

INFO - 2026-09-29T18:54:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14240 downloaded in 8.6 sec

INFO - 2026-09-29T18:54:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14239 downloaded in 8.2 sec

INFO - 2026-09-29T18:54:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14155 downloaded in 8.6 sec

INFO - 2026-09-29T18:54:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14230 downloaded in 8.6 sec

INFO - 2026-09-29T18:54:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14218 downloaded in 8.4 sec

INFO - 2026-09-29T18:54:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:54:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14145 downloaded in 8.4 sec

INFO - 2026-09-29T18:54:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:54:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:54:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14201 downloaded in 8.6 sec

INFO - 2026-09-29T18:55:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14205 downloaded in 8.2 sec

INFO - 2026-09-29T18:55:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14217 downloaded in 8.5 sec

INFO - 2026-09-29T18:55:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14241 downloaded in 8.3 sec

INFO - 2026-09-29T18:55:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14216 downloaded in 8.6 sec

INFO - 2026-09-29T18:55:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14236 downloaded in 11.7 sec

INFO - 2026-09-29T18:55:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:55:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:55:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:55:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14234 downloaded in 8.4 sec

INFO - 2026-09-29T18:56:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14204 downloaded in 8.3 sec

INFO - 2026-09-29T18:56:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14235 downloaded in 8.2 sec

INFO - 2026-09-29T18:56:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14222 downloaded in 8.6 sec

INFO - 2026-09-29T18:56:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14238 downloaded in 8.4 sec

INFO - 2026-09-29T18:56:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14144 downloaded in 8.5 sec

INFO - 2026-09-29T18:56:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14219 downloaded in 8.3 sec

INFO - 2026-09-29T18:56:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:56:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:56:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:56:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14220 downloaded in 8.6 sec

INFO - 2026-09-29T18:57:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14242 downloaded in 8.5 sec

INFO - 2026-09-29T18:57:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14208 downloaded in 8.2 sec

INFO - 2026-09-29T18:57:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14214 downloaded in 8.2 sec

INFO - 2026-09-29T18:57:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14203 downloaded in 12.3 sec

INFO - 2026-09-29T18:57:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14152 downloaded in 8.5 sec

INFO - 2026-09-29T18:57:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:57:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14215 downloaded in 8.0 sec

INFO - 2026-09-29T18:57:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:57:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:57:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14231 downloaded in 8.4 sec

INFO - 2026-09-29T18:58:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14232 downloaded in 8.4 sec

INFO - 2026-09-29T18:58:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14233 downloaded in 8.5 sec

INFO - 2026-09-29T18:58:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14146 downloaded in 8.3 sec

INFO - 2026-09-29T18:58:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14148 downloaded in 8.5 sec

INFO - 2026-09-29T18:58:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14149 downloaded in 8.8 sec

INFO - 2026-09-29T18:58:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:58:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14150 downloaded in 8.3 sec

INFO - 2026-09-29T18:58:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:58:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:58:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14153 downloaded in 8.5 sec

INFO - 2026-09-29T18:59:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14151 downloaded in 8.4 sec

INFO - 2026-09-29T18:59:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14212 downloaded in 11.9 sec

INFO - 2026-09-29T18:59:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14213 downloaded in 8.2 sec

INFO - 2026-09-29T18:59:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14504 downloaded in 8.4 sec

INFO - 2026-09-29T18:59:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14368 downloaded in 8.6 sec

INFO - 2026-09-29T18:59:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T18:59:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14518 downloaded in 8.3 sec

INFO - 2026-09-29T18:59:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T18:59:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T18:59:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14501 downloaded in 8.4 sec

INFO - 2026-09-29T19:00:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14500 downloaded in 8.5 sec

INFO - 2026-09-29T19:00:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14369 downloaded in 8.3 sec

INFO - 2026-09-29T19:00:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14426 downloaded in 8.4 sec

INFO - 2026-09-29T19:00:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14519 downloaded in 8.4 sec

INFO - 2026-09-29T19:00:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14427 downloaded in 8.4 sec

INFO - 2026-09-29T19:00:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:00:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14497 downloaded in 8.5 sec

INFO - 2026-09-29T19:00:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:00:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:00:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14481 downloaded in 12.2 sec

INFO - 2026-09-29T19:01:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14480 downloaded in 8.7 sec

INFO - 2026-09-29T19:01:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14428 downloaded in 8.5 sec

INFO - 2026-09-29T19:01:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14464 downloaded in 8.7 sec

INFO - 2026-09-29T19:01:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14393 downloaded in 8.4 sec

INFO - 2026-09-29T19:01:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:01:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14395 downloaded in 8.9 sec

INFO - 2026-09-29T19:01:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:01:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:01:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14405 downloaded in 8.4 sec

INFO - 2026-09-29T19:02:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14425 downloaded in 8.4 sec

INFO - 2026-09-29T19:02:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14424 downloaded in 8.4 sec

INFO - 2026-09-29T19:02:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14409 downloaded in 8.4 sec

INFO - 2026-09-29T19:02:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14408 downloaded in 8.3 sec

INFO - 2026-09-29T19:02:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14407 downloaded in 8.3 sec

INFO - 2026-09-29T19:02:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:02:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:02:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:02:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14419 downloaded in 13.6 sec

INFO - 2026-09-29T19:03:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14394 downloaded in 8.7 sec

INFO - 2026-09-29T19:03:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14392 downloaded in 8.5 sec

INFO - 2026-09-29T19:03:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14381 downloaded in 8.6 sec

INFO - 2026-09-29T19:03:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14463 downloaded in 8.6 sec

INFO - 2026-09-29T19:03:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14462 downloaded in 8.4 sec

INFO - 2026-09-29T19:03:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14431 downloaded in 8.6 sec

INFO - 2026-09-29T19:03:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:03:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:03:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:03:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14380 downloaded in 8.6 sec

INFO - 2026-09-29T19:04:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14371 downloaded in 8.6 sec

INFO - 2026-09-29T19:04:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14370 downloaded in 8.5 sec

INFO - 2026-09-29T19:04:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14467 downloaded in 8.6 sec

INFO - 2026-09-29T19:04:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14479 downloaded in 8.6 sec

INFO - 2026-09-29T19:04:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14484 downloaded in 12.8 sec

INFO - 2026-09-29T19:04:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:04:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14487 downloaded in 9.0 sec

INFO - 2026-09-29T19:04:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:04:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:04:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14492 downloaded in 8.4 sec

INFO - 2026-09-29T19:05:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14494 downloaded in 8.6 sec

INFO - 2026-09-29T19:05:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14498 downloaded in 8.6 sec

INFO - 2026-09-29T19:05:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14499 downloaded in 8.3 sec

INFO - 2026-09-29T19:05:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14521 downloaded in 8.3 sec

INFO - 2026-09-29T19:05:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14523 downloaded in 8.5 sec

INFO - 2026-09-29T19:05:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:05:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14503 downloaded in 8.4 sec

INFO - 2026-09-29T19:05:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:05:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:05:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14502 downloaded in 8.4 sec

INFO - 2026-09-29T19:06:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14468 downloaded in 8.3 sec

INFO - 2026-09-29T19:06:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14508 downloaded in 8.4 sec

INFO - 2026-09-29T19:06:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14373 downloaded in 13.2 sec

INFO - 2026-09-29T19:06:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14466 downloaded in 8.2 sec

INFO - 2026-09-29T19:06:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:06:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14465 downloaded in 8.7 sec

INFO - 2026-09-29T19:06:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:06:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:06:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14469 downloaded in 8.8 sec

INFO - 2026-09-29T19:07:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14389 downloaded in 8.5 sec

INFO - 2026-09-29T19:07:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14470 downloaded in 8.3 sec

INFO - 2026-09-29T19:07:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14471 downloaded in 8.6 sec

INFO - 2026-09-29T19:07:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14472 downloaded in 8.3 sec

INFO - 2026-09-29T19:07:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14473 downloaded in 8.4 sec

INFO - 2026-09-29T19:07:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:07:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14474 downloaded in 8.5 sec

INFO - 2026-09-29T19:07:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:07:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:07:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14475 downloaded in 8.8 sec

INFO - 2026-09-29T19:08:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14476 downloaded in 8.1 sec

INFO - 2026-09-29T19:08:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14477 downloaded in 11.5 sec

INFO - 2026-09-29T19:08:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14434 downloaded in 8.7 sec

INFO - 2026-09-29T19:08:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14478 downloaded in 8.4 sec

INFO - 2026-09-29T19:08:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14433 downloaded in 8.2 sec

INFO - 2026-09-29T19:08:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:08:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14432 downloaded in 8.2 sec

INFO - 2026-09-29T19:08:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:08:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:08:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14430 downloaded in 8.6 sec

INFO - 2026-09-29T19:09:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14429 downloaded in 8.5 sec

INFO - 2026-09-29T19:09:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14482 downloaded in 8.3 sec

INFO - 2026-09-29T19:09:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14483 downloaded in 8.4 sec

INFO - 2026-09-29T19:09:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14485 downloaded in 8.4 sec

INFO - 2026-09-29T19:09:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14486 downloaded in 8.3 sec

INFO - 2026-09-29T19:09:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:09:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14374 downloaded in 8.5 sec

INFO - 2026-09-29T19:09:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:09:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:09:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14423 downloaded in 12.5 sec

INFO - 2026-09-29T19:10:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14375 downloaded in 8.4 sec

INFO - 2026-09-29T19:10:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14422 downloaded in 8.6 sec

INFO - 2026-09-29T19:10:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14421 downloaded in 8.5 sec

INFO - 2026-09-29T19:10:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14420 downloaded in 8.4 sec

INFO - 2026-09-29T19:10:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14378 downloaded in 8.4 sec

INFO - 2026-09-29T19:10:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:10:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:10:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:10:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14382 downloaded in 8.5 sec

INFO - 2026-09-29T19:11:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14383 downloaded in 8.5 sec

INFO - 2026-09-29T19:11:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14384 downloaded in 8.3 sec

INFO - 2026-09-29T19:11:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14385 downloaded in 8.1 sec

INFO - 2026-09-29T19:11:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14387 downloaded in 8.6 sec

INFO - 2026-09-29T19:11:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14388 downloaded in 8.5 sec

INFO - 2026-09-29T19:11:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:11:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14390 downloaded in 12.2 sec

INFO - 2026-09-29T19:11:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:11:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:11:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14391 downloaded in 8.5 sec

INFO - 2026-09-29T19:12:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14396 downloaded in 8.7 sec

INFO - 2026-09-29T19:12:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14386 downloaded in 8.5 sec

INFO - 2026-09-29T19:12:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14398 downloaded in 8.5 sec

INFO - 2026-09-29T19:12:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14488 downloaded in 8.3 sec

INFO - 2026-09-29T19:12:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14489 downloaded in 8.5 sec

INFO - 2026-09-29T19:12:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:12:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14490 downloaded in 8.5 sec

INFO - 2026-09-29T19:12:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:12:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:12:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14491 downloaded in 8.5 sec

INFO - 2026-09-29T19:13:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14493 downloaded in 8.1 sec

INFO - 2026-09-29T19:13:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14495 downloaded in 8.4 sec

INFO - 2026-09-29T19:13:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14496 downloaded in 8.3 sec

INFO - 2026-09-29T19:13:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14399 downloaded in 11.7 sec

INFO - 2026-09-29T19:13:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14400 downloaded in 8.5 sec

INFO - 2026-09-29T19:13:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:13:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:13:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:13:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14412 downloaded in 8.6 sec

INFO - 2026-09-29T19:14:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14401 downloaded in 8.5 sec

INFO - 2026-09-29T19:14:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14402 downloaded in 8.1 sec

INFO - 2026-09-29T19:14:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14403 downloaded in 8.5 sec

INFO - 2026-09-29T19:14:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14404 downloaded in 8.1 sec

INFO - 2026-09-29T19:14:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14417 downloaded in 8.2 sec

INFO - 2026-09-29T19:14:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14416 downloaded in 8.4 sec

INFO - 2026-09-29T19:14:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:14:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:14:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:14:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14415 downloaded in 8.3 sec

INFO - 2026-09-29T19:15:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14414 downloaded in 8.3 sec

INFO - 2026-09-29T19:15:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14413 downloaded in 8.2 sec

INFO - 2026-09-29T19:15:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14406 downloaded in 12.2 sec

INFO - 2026-09-29T19:15:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14410 downloaded in 8.3 sec

INFO - 2026-09-29T19:15:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14379 downloaded in 8.7 sec

INFO - 2026-09-29T19:15:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:15:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14507 downloaded in 8.5 sec

INFO - 2026-09-29T19:15:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:15:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:15:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14509 downloaded in 8.3 sec

INFO - 2026-09-29T19:16:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14511 downloaded in 8.5 sec

INFO - 2026-09-29T19:16:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14512 downloaded in 8.2 sec

INFO - 2026-09-29T19:16:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14506 downloaded in 8.5 sec

INFO - 2026-09-29T19:16:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14513 downloaded in 8.3 sec

INFO - 2026-09-29T19:16:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14524 downloaded in 8.6 sec

INFO - 2026-09-29T19:16:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:16:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14505 downloaded in 8.6 sec

INFO - 2026-09-29T19:16:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:16:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:16:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14520 downloaded in 8.3 sec

INFO - 2026-09-29T19:17:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14510 downloaded in 11.9 sec

INFO - 2026-09-29T19:17:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14514 downloaded in 8.2 sec

INFO - 2026-09-29T19:17:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14515 downloaded in 8.4 sec

INFO - 2026-09-29T19:17:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14516 downloaded in 8.5 sec

INFO - 2026-09-29T19:17:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14522 downloaded in 8.4 sec

INFO - 2026-09-29T19:17:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:17:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14547 downloaded in 8.5 sec

INFO - 2026-09-29T19:17:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:17:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:17:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14548 downloaded in 8.6 sec

INFO - 2026-09-29T19:18:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14549 downloaded in 8.6 sec

INFO - 2026-09-29T19:18:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14550 downloaded in 8.4 sec

INFO - 2026-09-29T19:18:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14544 downloaded in 8.4 sec

INFO - 2026-09-29T19:18:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14545 downloaded in 8.3 sec

INFO - 2026-09-29T19:18:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:18:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14546 downloaded in 8.4 sec

INFO - 2026-09-29T19:18:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:18:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:18:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14729 downloaded in 11.6 sec

INFO - 2026-09-29T19:19:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14719 downloaded in 9.3 sec

INFO - 2026-09-29T19:19:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14727 downloaded in 9.5 sec

INFO - 2026-09-29T19:19:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14757 downloaded in 8.4 sec

INFO - 2026-09-29T19:19:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14750 downloaded in 8.4 sec

INFO - 2026-09-29T19:19:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14741 downloaded in 9.4 sec

INFO - 2026-09-29T19:19:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:19:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14714 downloaded in 9.2 sec

INFO - 2026-09-29T19:19:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:19:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:19:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14715 downloaded in 9.3 sec

INFO - 2026-09-29T19:20:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14716 downloaded in 9.1 sec

INFO - 2026-09-29T19:20:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14717 downloaded in 9.4 sec

INFO - 2026-09-29T19:20:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14718 downloaded in 9.2 sec

INFO - 2026-09-29T19:20:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14722 downloaded in 9.1 sec

INFO - 2026-09-29T19:20:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:20:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14724 downloaded in 12.8 sec

INFO - 2026-09-29T19:20:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:20:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:20:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14725 downloaded in 9.2 sec

INFO - 2026-09-29T19:21:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14760 downloaded in 9.2 sec

INFO - 2026-09-29T19:21:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14759 downloaded in 8.7 sec

INFO - 2026-09-29T19:21:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14756 downloaded in 9.3 sec

INFO - 2026-09-29T19:21:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14755 downloaded in 9.2 sec

INFO - 2026-09-29T19:21:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:21:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14754 downloaded in 9.0 sec

INFO - 2026-09-29T19:21:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:21:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:21:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14753 downloaded in 9.2 sec

INFO - 2026-09-29T19:22:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14752 downloaded in 9.3 sec

INFO - 2026-09-29T19:22:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14751 downloaded in 9.3 sec

INFO - 2026-09-29T19:22:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14742 downloaded in 8.6 sec

INFO - 2026-09-29T19:22:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14746 downloaded in 9.3 sec

INFO - 2026-09-29T19:22:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14740 downloaded in 12.9 sec

INFO - 2026-09-29T19:22:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:22:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:22:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:22:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14730 downloaded in 8.5 sec

INFO - 2026-09-29T19:23:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14749 downloaded in 9.2 sec

INFO - 2026-09-29T19:23:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14738 downloaded in 9.1 sec

INFO - 2026-09-29T19:23:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14734 downloaded in 9.3 sec

INFO - 2026-09-29T19:23:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14748 downloaded in 8.7 sec

INFO - 2026-09-29T19:23:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14733 downloaded in 8.9 sec

INFO - 2026-09-29T19:23:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:23:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14732 downloaded in 9.3 sec

INFO - 2026-09-29T19:23:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:23:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:23:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14731 downloaded in 8.5 sec

INFO - 2026-09-29T19:24:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14728 downloaded in 8.4 sec

INFO - 2026-09-29T19:24:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14745 downloaded in 9.1 sec

INFO - 2026-09-29T19:24:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14723 downloaded in 9.0 sec

INFO - 2026-09-29T19:24:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14720 downloaded in 12.7 sec

INFO - 2026-09-29T19:24:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:24:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14721 downloaded in 9.4 sec

INFO - 2026-09-29T19:24:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:24:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:24:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14762 downloaded in 9.2 sec

INFO - 2026-09-29T19:25:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14761 downloaded in 9.2 sec

INFO - 2026-09-29T19:25:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14758 downloaded in 8.4 sec

INFO - 2026-09-29T19:25:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14744 downloaded in 9.2 sec

INFO - 2026-09-29T19:25:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14743 downloaded in 8.5 sec

INFO - 2026-09-29T19:25:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14739 downloaded in 9.3 sec

INFO - 2026-09-29T19:25:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:25:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14737 downloaded in 9.4 sec

INFO - 2026-09-29T19:25:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:25:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:25:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14736 downloaded in 9.2 sec

INFO - 2026-09-29T19:26:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14735 downloaded in 9.3 sec

INFO - 2026-09-29T19:26:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14681 downloaded in 8.5 sec

INFO - 2026-09-29T19:26:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14726 downloaded in 12.6 sec

INFO - 2026-09-29T19:26:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14244 downloaded in 8.6 sec

INFO - 2026-09-29T19:26:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:26:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14534 downloaded in 8.4 sec

INFO - 2026-09-29T19:26:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:26:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:26:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14525 downloaded in 8.3 sec

INFO - 2026-09-29T19:27:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14536 downloaded in 8.5 sec

INFO - 2026-09-29T19:27:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14527 downloaded in 8.7 sec

INFO - 2026-09-29T19:27:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14528 downloaded in 8.4 sec

INFO - 2026-09-29T19:27:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14533 downloaded in 8.4 sec

INFO - 2026-09-29T19:27:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14532 downloaded in 8.5 sec

INFO - 2026-09-29T19:27:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:27:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14529 downloaded in 8.8 sec

INFO - 2026-09-29T19:27:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:27:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:27:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14530 downloaded in 8.3 sec

INFO - 2026-09-29T19:28:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14531 downloaded in 8.7 sec

INFO - 2026-09-29T19:28:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14526 downloaded in 12.4 sec

INFO - 2026-09-29T19:28:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14535 downloaded in 8.8 sec

INFO - 2026-09-29T19:28:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14539 downloaded in 8.2 sec

INFO - 2026-09-29T19:28:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14540 downloaded in 8.2 sec

INFO - 2026-09-29T19:28:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:28:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:28:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:28:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14538 downloaded in 8.7 sec

INFO - 2026-09-29T19:29:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14537 downloaded in 8.3 sec

INFO - 2026-09-29T19:29:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14575 downloaded in 8.5 sec

INFO - 2026-09-29T19:29:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14576 downloaded in 8.5 sec

INFO - 2026-09-29T19:29:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14577 downloaded in 8.5 sec

INFO - 2026-09-29T19:29:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14574 downloaded in 8.5 sec

INFO - 2026-09-29T19:29:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:29:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14128 downloaded in 8.6 sec

INFO - 2026-09-29T19:29:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:29:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:29:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14045 downloaded in 8.9 sec

INFO - 2026-09-29T19:30:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14046 downloaded in 12.1 sec

INFO - 2026-09-29T19:30:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13703 downloaded in 8.5 sec

INFO - 2026-09-29T19:30:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14084 downloaded in 8.4 sec

INFO - 2026-09-29T19:30:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14085 downloaded in 8.3 sec

INFO - 2026-09-29T19:30:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14086 downloaded in 8.6 sec

INFO - 2026-09-29T19:30:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:30:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14087 downloaded in 8.7 sec

INFO - 2026-09-29T19:30:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:30:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:30:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14088 downloaded in 8.6 sec

INFO - 2026-09-29T19:31:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14076 downloaded in 8.1 sec

INFO - 2026-09-29T19:31:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14069 downloaded in 8.7 sec

INFO - 2026-09-29T19:31:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14059 downloaded in 8.7 sec

INFO - 2026-09-29T19:31:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14037 downloaded in 8.6 sec

INFO - 2026-09-29T19:31:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14060 downloaded in 8.7 sec

INFO - 2026-09-29T19:31:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:31:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:31:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:31:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14021 downloaded in 8.7 sec

INFO - 2026-09-29T19:32:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13891 downloaded in 12.0 sec

INFO - 2026-09-29T19:32:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13890 downloaded in 8.6 sec

INFO - 2026-09-29T19:32:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13886 downloaded in 9.0 sec

INFO - 2026-09-29T19:32:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13853 downloaded in 8.6 sec

INFO - 2026-09-29T19:32:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13741 downloaded in 8.3 sec

INFO - 2026-09-29T19:32:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:32:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14022 downloaded in 9.0 sec

INFO - 2026-09-29T19:32:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:32:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:32:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14004 downloaded in 8.7 sec

INFO - 2026-09-29T19:33:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14034 downloaded in 8.6 sec

INFO - 2026-09-29T19:33:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13680 downloaded in 8.6 sec

INFO - 2026-09-29T19:33:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14038 downloaded in 9.0 sec

INFO - 2026-09-29T19:33:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14068 downloaded in 8.4 sec

INFO - 2026-09-29T19:33:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13906 downloaded in 8.6 sec

INFO - 2026-09-29T19:33:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:33:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:33:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:33:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13998 downloaded in 12.2 sec

INFO - 2026-09-29T19:34:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14067 downloaded in 8.7 sec

INFO - 2026-09-29T19:34:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13999 downloaded in 8.6 sec

INFO - 2026-09-29T19:34:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14001 downloaded in 8.6 sec

INFO - 2026-09-29T19:34:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14002 downloaded in 8.7 sec

INFO - 2026-09-29T19:34:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14023 downloaded in 8.8 sec

INFO - 2026-09-29T19:34:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:34:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14003 downloaded in 8.5 sec

INFO - 2026-09-29T19:34:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:34:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:34:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14024 downloaded in 8.6 sec

INFO - 2026-09-29T19:35:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14025 downloaded in 8.8 sec

INFO - 2026-09-29T19:35:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14019 downloaded in 8.8 sec

INFO - 2026-09-29T19:35:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14020 downloaded in 8.6 sec

INFO - 2026-09-29T19:35:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14005 downloaded in 11.9 sec

INFO - 2026-09-29T19:35:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14061 downloaded in 8.6 sec

INFO - 2026-09-29T19:35:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:35:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:35:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:35:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14036 downloaded in 8.8 sec

INFO - 2026-09-29T19:36:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14062 downloaded in 8.7 sec

INFO - 2026-09-29T19:36:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13966 downloaded in 8.5 sec

INFO - 2026-09-29T19:36:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13967 downloaded in 8.5 sec

INFO - 2026-09-29T19:36:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13968 downloaded in 8.6 sec

INFO - 2026-09-29T19:36:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14063 downloaded in 8.8 sec

INFO - 2026-09-29T19:36:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14064 downloaded in 8.5 sec

INFO - 2026-09-29T19:36:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:36:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:36:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:36:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13969 downloaded in 8.7 sec

INFO - 2026-09-29T19:37:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13970 downloaded in 8.7 sec

INFO - 2026-09-29T19:37:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14065 downloaded in 8.5 sec

INFO - 2026-09-29T19:37:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13971 downloaded in 12.2 sec

INFO - 2026-09-29T19:37:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14039 downloaded in 8.6 sec

INFO - 2026-09-29T19:37:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14066 downloaded in 8.8 sec

INFO - 2026-09-29T19:37:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:37:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13885 downloaded in 8.5 sec

INFO - 2026-09-29T19:37:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:37:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:37:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13887 downloaded in 8.5 sec

INFO - 2026-09-29T19:38:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13888 downloaded in 8.8 sec

INFO - 2026-09-29T19:38:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13899 downloaded in 8.7 sec

INFO - 2026-09-29T19:38:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13900 downloaded in 8.7 sec

INFO - 2026-09-29T19:38:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13901 downloaded in 8.5 sec

INFO - 2026-09-29T19:38:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13678 downloaded in 8.8 sec

INFO - 2026-09-29T19:38:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:38:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13903 downloaded in 8.6 sec

INFO - 2026-09-29T19:38:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:38:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:38:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13904 downloaded in 8.4 sec

INFO - 2026-09-29T19:39:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13907 downloaded in 12.1 sec

INFO - 2026-09-29T19:39:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13908 downloaded in 8.6 sec

INFO - 2026-09-29T19:39:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13902 downloaded in 8.4 sec

INFO - 2026-09-29T19:39:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13905 downloaded in 8.7 sec

INFO - 2026-09-29T19:39:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:39:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14035 downloaded in 8.9 sec

INFO - 2026-09-29T19:39:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:39:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:39:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13745 downloaded in 8.6 sec

INFO - 2026-09-29T19:40:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13850 downloaded in 8.7 sec

INFO - 2026-09-29T19:40:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13884 downloaded in 8.7 sec

INFO - 2026-09-29T19:40:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13909 downloaded in 8.7 sec

INFO - 2026-09-29T19:40:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13740 downloaded in 9.6 sec

INFO - 2026-09-29T19:40:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13777 downloaded in 8.5 sec

INFO - 2026-09-29T19:40:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:40:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13776 downloaded in 8.9 sec

INFO - 2026-09-29T19:40:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:40:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:40:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13737 downloaded in 12.1 sec

INFO - 2026-09-29T19:41:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13738 downloaded in 8.7 sec

INFO - 2026-09-29T19:41:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13739 downloaded in 8.5 sec

INFO - 2026-09-29T19:41:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13775 downloaded in 8.4 sec

INFO - 2026-09-29T19:41:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13774 downloaded in 8.6 sec

INFO - 2026-09-29T19:41:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:41:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13784 downloaded in 8.5 sec

INFO - 2026-09-29T19:41:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:41:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:41:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13783 downloaded in 8.6 sec

INFO - 2026-09-29T19:42:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13782 downloaded in 8.3 sec

INFO - 2026-09-29T19:42:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13781 downloaded in 8.8 sec

INFO - 2026-09-29T19:42:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13780 downloaded in 8.8 sec

INFO - 2026-09-29T19:42:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13779 downloaded in 8.4 sec

INFO - 2026-09-29T19:42:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13778 downloaded in 8.4 sec

INFO - 2026-09-29T19:42:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:42:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13742 downloaded in 12.5 sec

INFO - 2026-09-29T19:42:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:42:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:42:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13743 downloaded in 8.8 sec

INFO - 2026-09-29T19:43:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13848 downloaded in 8.5 sec

INFO - 2026-09-29T19:43:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13847 downloaded in 8.6 sec

INFO - 2026-09-29T19:43:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13849 downloaded in 8.8 sec

INFO - 2026-09-29T19:43:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13851 downloaded in 8.5 sec

INFO - 2026-09-29T19:43:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13744 downloaded in 8.4 sec

INFO - 2026-09-29T19:43:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:43:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:43:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:43:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13852 downloaded in 8.5 sec

INFO - 2026-09-29T19:44:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13854 downloaded in 8.7 sec

INFO - 2026-09-29T19:44:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13672 downloaded in 8.6 sec

INFO - 2026-09-29T19:44:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13673 downloaded in 8.6 sec

INFO - 2026-09-29T19:44:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13674 downloaded in 8.9 sec

INFO - 2026-09-29T19:44:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13675 downloaded in 12.0 sec

INFO - 2026-09-29T19:44:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:44:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13679 downloaded in 8.5 sec

INFO - 2026-09-29T19:44:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:44:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:44:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13681 downloaded in 8.7 sec

INFO - 2026-09-29T19:45:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13682 downloaded in 8.8 sec

INFO - 2026-09-29T19:45:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13889 downloaded in 8.6 sec

INFO - 2026-09-29T19:45:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13892 downloaded in 8.6 sec

INFO - 2026-09-29T19:45:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14198 downloaded in 8.4 sec

INFO - 2026-09-29T19:45:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14199 downloaded in 8.5 sec

INFO - 2026-09-29T19:45:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:45:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14080 downloaded in 8.4 sec

INFO - 2026-09-29T19:45:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:45:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:45:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14081 downloaded in 8.3 sec

INFO - 2026-09-29T19:46:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14082 downloaded in 8.6 sec

INFO - 2026-09-29T19:46:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14077 downloaded in 8.0 sec

INFO - 2026-09-29T19:46:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14078 downloaded in 11.6 sec

INFO - 2026-09-29T19:46:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14079 downloaded in 8.5 sec

INFO - 2026-09-29T19:46:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14224 downloaded in 9.0 sec

INFO - 2026-09-29T19:46:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:46:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:46:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:46:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14227 downloaded in 8.7 sec

INFO - 2026-09-29T19:47:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14223 downloaded in 8.8 sec

INFO - 2026-09-29T19:47:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14225 downloaded in 9.1 sec

INFO - 2026-09-29T19:47:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14226 downloaded in 8.9 sec

INFO - 2026-09-29T19:47:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14228 downloaded in 8.1 sec

INFO - 2026-09-29T19:47:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14229 downloaded in 8.7 sec

INFO - 2026-09-29T19:47:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14102 downloaded in 8.2 sec

INFO - 2026-09-29T19:47:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:47:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:47:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:47:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14099 downloaded in 8.0 sec

INFO - 2026-09-29T19:48:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14103 downloaded in 8.6 sec

INFO - 2026-09-29T19:48:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14101 downloaded in 11.4 sec

INFO - 2026-09-29T19:48:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13965 downloaded in 8.6 sec

INFO - 2026-09-29T19:48:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13958 downloaded in 8.0 sec

INFO - 2026-09-29T19:48:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14031 downloaded in 8.4 sec

INFO - 2026-09-29T19:48:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:48:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14029 downloaded in 8.4 sec

INFO - 2026-09-29T19:48:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:48:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:48:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14030 downloaded in 8.2 sec

INFO - 2026-09-29T19:49:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13959 downloaded in 8.0 sec

INFO - 2026-09-29T19:49:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13996 downloaded in 8.1 sec

INFO - 2026-09-29T19:49:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13997 downloaded in 8.6 sec

INFO - 2026-09-29T19:49:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13973 downloaded in 8.2 sec

INFO - 2026-09-29T19:49:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14032 downloaded in 8.4 sec

INFO - 2026-09-29T19:49:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:49:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13957 downloaded in 8.1 sec

INFO - 2026-09-29T19:49:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:49:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:49:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13896 downloaded in 12.0 sec

INFO - 2026-09-29T19:50:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13960 downloaded in 8.1 sec

INFO - 2026-09-29T19:50:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14027 downloaded in 8.5 sec

INFO - 2026-09-29T19:50:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14028 downloaded in 8.4 sec

INFO - 2026-09-29T19:50:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13956 downloaded in 8.3 sec

INFO - 2026-09-29T19:50:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13898 downloaded in 8.2 sec

INFO - 2026-09-29T19:50:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:50:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13897 downloaded in 8.4 sec

INFO - 2026-09-29T19:50:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:50:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:50:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13895 downloaded in 8.1 sec

INFO - 2026-09-29T19:51:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13883 downloaded in 8.4 sec

INFO - 2026-09-29T19:51:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13882 downloaded in 8.6 sec

INFO - 2026-09-29T19:51:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13881 downloaded in 8.5 sec

INFO - 2026-09-29T19:51:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13880 downloaded in 8.4 sec

INFO - 2026-09-29T19:51:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13869 downloaded in 8.3 sec

INFO - 2026-09-29T19:51:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:51:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:51:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:51:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13866 downloaded in 12.3 sec

INFO - 2026-09-29T19:52:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13868 downloaded in 8.7 sec

INFO - 2026-09-29T19:52:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13867 downloaded in 8.2 sec

INFO - 2026-09-29T19:52:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13964 downloaded in 8.4 sec

INFO - 2026-09-29T19:52:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13963 downloaded in 8.3 sec

INFO - 2026-09-29T19:52:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13962 downloaded in 8.0 sec

INFO - 2026-09-29T19:52:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13961 downloaded in 8.1 sec

INFO - 2026-09-29T19:52:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:52:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:52:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:52:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13972 downloaded in 8.5 sec

INFO - 2026-09-29T19:53:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13955 downloaded in 8.1 sec

INFO - 2026-09-29T19:53:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13865 downloaded in 8.1 sec

INFO - 2026-09-29T19:53:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13893 downloaded in 8.3 sec

INFO - 2026-09-29T19:53:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13894 downloaded in 12.0 sec

INFO - 2026-09-29T19:53:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13951 downloaded in 8.3 sec

INFO - 2026-09-29T19:53:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:53:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13950 downloaded in 8.0 sec

INFO - 2026-09-29T19:53:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:53:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:53:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13954 downloaded in 8.4 sec

INFO - 2026-09-29T19:54:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13953 downloaded in 8.5 sec

INFO - 2026-09-29T19:54:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13952 downloaded in 8.1 sec

INFO - 2026-09-29T19:54:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13927 downloaded in 8.3 sec

INFO - 2026-09-29T19:54:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13921 downloaded in 8.5 sec

INFO - 2026-09-29T19:54:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13932 downloaded in 8.3 sec

INFO - 2026-09-29T19:54:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:54:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13931 downloaded in 8.2 sec

INFO - 2026-09-29T19:54:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:54:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:54:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13935 downloaded in 8.5 sec

INFO - 2026-09-29T19:55:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13916 downloaded in 8.2 sec

INFO - 2026-09-29T19:55:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13923 downloaded in 8.2 sec

INFO - 2026-09-29T19:55:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13913 downloaded in 11.9 sec

INFO - 2026-09-29T19:55:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13925 downloaded in 8.7 sec

INFO - 2026-09-29T19:55:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13929 downloaded in 8.1 sec

INFO - 2026-09-29T19:55:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:55:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13937 downloaded in 8.1 sec

INFO - 2026-09-29T19:55:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:55:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:55:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13918 downloaded in 8.2 sec

INFO - 2026-09-29T19:56:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13933 downloaded in 8.4 sec

INFO - 2026-09-29T19:56:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14126 downloaded in 8.4 sec

INFO - 2026-09-29T19:56:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14090 downloaded in 9.3 sec

INFO - 2026-09-29T19:56:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14118 downloaded in 9.3 sec

INFO - 2026-09-29T19:56:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14121 downloaded in 9.2 sec

INFO - 2026-09-29T19:56:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:56:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:56:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:56:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14122 downloaded in 9.2 sec

INFO - 2026-09-29T19:57:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14123 downloaded in 12.3 sec

INFO - 2026-09-29T19:57:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14124 downloaded in 9.3 sec

INFO - 2026-09-29T19:57:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14125 downloaded in 8.6 sec

INFO - 2026-09-29T19:57:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14119 downloaded in 9.0 sec

INFO - 2026-09-29T19:57:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14116 downloaded in 9.4 sec

INFO - 2026-09-29T19:57:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:57:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14117 downloaded in 9.1 sec

INFO - 2026-09-29T19:57:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:57:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:57:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14114 downloaded in 9.0 sec

INFO - 2026-09-29T19:58:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14098 downloaded in 9.0 sec

INFO - 2026-09-29T19:58:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14110 downloaded in 9.1 sec

INFO - 2026-09-29T19:58:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14115 downloaded in 9.1 sec

INFO - 2026-09-29T19:58:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14112 downloaded in 8.5 sec

INFO - 2026-09-29T19:58:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:58:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14113 downloaded in 8.6 sec

INFO - 2026-09-29T19:58:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:58:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:58:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13765 downloaded in 11.8 sec

INFO - 2026-09-29T19:59:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14111 downloaded in 8.5 sec

INFO - 2026-09-29T19:59:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14109 downloaded in 8.6 sec

INFO - 2026-09-29T19:59:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14105 downloaded in 8.3 sec

INFO - 2026-09-29T19:59:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14083 downloaded in 8.4 sec

INFO - 2026-09-29T19:59:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14104 downloaded in 8.2 sec

INFO - 2026-09-29T19:59:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T19:59:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14108 downloaded in 8.6 sec

INFO - 2026-09-29T19:59:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T19:59:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T19:59:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14107 downloaded in 8.2 sec

INFO - 2026-09-29T20:00:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14106 downloaded in 8.7 sec

INFO - 2026-09-29T20:00:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14095 downloaded in 8.5 sec

INFO - 2026-09-29T20:00:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14093 downloaded in 8.3 sec

INFO - 2026-09-29T20:00:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14094 downloaded in 8.1 sec

INFO - 2026-09-29T20:00:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14096 downloaded in 11.8 sec

INFO - 2026-09-29T20:00:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:00:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:00:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:00:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14091 downloaded in 8.6 sec

INFO - 2026-09-29T20:01:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14092 downloaded in 8.9 sec

INFO - 2026-09-29T20:01:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14097 downloaded in 8.1 sec

INFO - 2026-09-29T20:01:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14552 downloaded in 8.8 sec

INFO - 2026-09-29T20:01:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14551 downloaded in 8.7 sec

INFO - 2026-09-29T20:01:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14553 downloaded in 8.5 sec

INFO - 2026-09-29T20:01:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14556 downloaded in 8.6 sec

INFO - 2026-09-29T20:01:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:01:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:01:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:01:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13948 downloaded in 8.9 sec

INFO - 2026-09-29T20:02:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13949 downloaded in 8.7 sec

INFO - 2026-09-29T20:02:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14040 downloaded in 8.6 sec

INFO - 2026-09-29T20:02:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14350 downloaded in 8.8 sec

INFO - 2026-09-29T20:02:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14033 downloaded in 12.1 sec

INFO - 2026-09-29T20:02:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13692 downloaded in 8.7 sec

INFO - 2026-09-29T20:02:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:02:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13691 downloaded in 8.9 sec

INFO - 2026-09-29T20:02:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:02:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:02:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13693 downloaded in 8.8 sec

INFO - 2026-09-29T20:03:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13702 downloaded in 8.7 sec

INFO - 2026-09-29T20:03:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13600 downloaded in 8.5 sec

INFO - 2026-09-29T20:03:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13844 downloaded in 8.7 sec

INFO - 2026-09-29T20:03:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13821 downloaded in 8.7 sec

INFO - 2026-09-29T20:03:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13822 downloaded in 8.7 sec

INFO - 2026-09-29T20:03:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:03:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:03:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:03:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13823 downloaded in 8.6 sec

INFO - 2026-09-29T20:04:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13827 downloaded in 8.7 sec

INFO - 2026-09-29T20:04:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13845 downloaded in 9.3 sec

INFO - 2026-09-29T20:04:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13826 downloaded in 12.1 sec

INFO - 2026-09-29T20:04:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13843 downloaded in 8.5 sec

INFO - 2026-09-29T20:04:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13846 downloaded in 9.1 sec

INFO - 2026-09-29T20:04:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:04:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13824 downloaded in 8.5 sec

INFO - 2026-09-29T20:04:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:04:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:04:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13825 downloaded in 8.7 sec

INFO - 2026-09-29T20:05:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13828 downloaded in 8.5 sec

INFO - 2026-09-29T20:05:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13842 downloaded in 8.4 sec

INFO - 2026-09-29T20:05:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14009 downloaded in 8.6 sec

INFO - 2026-09-29T20:05:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14017 downloaded in 8.4 sec

INFO - 2026-09-29T20:05:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14016 downloaded in 8.2 sec

INFO - 2026-09-29T20:05:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:05:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14013 downloaded in 8.5 sec

INFO - 2026-09-29T20:05:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:05:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:05:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14010 downloaded in 8.4 sec

INFO - 2026-09-29T20:06:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14011 downloaded in 11.7 sec

INFO - 2026-09-29T20:06:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14012 downloaded in 8.5 sec

INFO - 2026-09-29T20:06:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14015 downloaded in 8.4 sec

INFO - 2026-09-29T20:06:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14014 downloaded in 8.7 sec

INFO - 2026-09-29T20:06:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14008 downloaded in 8.4 sec

INFO - 2026-09-29T20:06:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:06:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:06:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:06:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14006 downloaded in 8.3 sec

INFO - 2026-09-29T20:07:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14007 downloaded in 8.6 sec

INFO - 2026-09-29T20:07:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13461 downloaded in 8.3 sec

INFO - 2026-09-29T20:07:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13770 downloaded in 8.3 sec

INFO - 2026-09-29T20:07:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13769 downloaded in 8.7 sec

INFO - 2026-09-29T20:07:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13768 downloaded in 8.4 sec

INFO - 2026-09-29T20:07:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:07:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13771 downloaded in 8.6 sec

INFO - 2026-09-29T20:07:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:07:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:07:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14377 downloaded in 11.9 sec

INFO - 2026-09-29T20:08:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13460 downloaded in 8.7 sec

INFO - 2026-09-29T20:08:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13665 downloaded in 8.7 sec

INFO - 2026-09-29T20:08:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13543 downloaded in 8.7 sec

INFO - 2026-09-29T20:08:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13671 downloaded in 8.4 sec

INFO - 2026-09-29T20:08:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13532 downloaded in 8.9 sec

INFO - 2026-09-29T20:08:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:08:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13493 downloaded in 8.6 sec

INFO - 2026-09-29T20:08:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:08:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:08:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13530 downloaded in 8.6 sec

INFO - 2026-09-29T20:09:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13538 downloaded in 8.4 sec

INFO - 2026-09-29T20:09:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13645 downloaded in 8.9 sec

INFO - 2026-09-29T20:09:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13548 downloaded in 8.6 sec

INFO - 2026-09-29T20:09:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13546 downloaded in 8.5 sec

INFO - 2026-09-29T20:09:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:09:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13545 downloaded in 12.2 sec

INFO - 2026-09-29T20:09:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:09:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:09:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13539 downloaded in 8.8 sec

INFO - 2026-09-29T20:10:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13537 downloaded in 8.5 sec

INFO - 2026-09-29T20:10:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13535 downloaded in 8.4 sec

INFO - 2026-09-29T20:10:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13533 downloaded in 8.7 sec

INFO - 2026-09-29T20:10:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13466 downloaded in 8.7 sec

INFO - 2026-09-29T20:10:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13534 downloaded in 8.6 sec

INFO - 2026-09-29T20:10:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:10:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13459 downloaded in 8.5 sec

INFO - 2026-09-29T20:10:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:10:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:10:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13458 downloaded in 8.8 sec

INFO - 2026-09-29T20:11:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13457 downloaded in 8.4 sec

INFO - 2026-09-29T20:11:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13512 downloaded in 8.4 sec

INFO - 2026-09-29T20:11:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13490 downloaded in 8.5 sec

INFO - 2026-09-29T20:11:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13525 downloaded in 12.2 sec

INFO - 2026-09-29T20:11:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13526 downloaded in 8.5 sec

INFO - 2026-09-29T20:11:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:11:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:11:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:11:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13527 downloaded in 8.7 sec

INFO - 2026-09-29T20:12:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12455 downloaded in 8.6 sec

INFO - 2026-09-29T20:12:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12456 downloaded in 8.8 sec

INFO - 2026-09-29T20:12:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12457 downloaded in 9.0 sec

INFO - 2026-09-29T20:12:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12454 downloaded in 8.6 sec

INFO - 2026-09-29T20:12:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12458 downloaded in 8.5 sec

INFO - 2026-09-29T20:12:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:12:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12459 downloaded in 8.6 sec

INFO - 2026-09-29T20:12:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:12:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:12:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12460 downloaded in 8.7 sec

INFO - 2026-09-29T20:13:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13638 downloaded in 8.7 sec

INFO - 2026-09-29T20:13:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13626 downloaded in 8.8 sec

INFO - 2026-09-29T20:13:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13666 downloaded in 14.1 sec

INFO - 2026-09-29T20:13:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12567 downloaded in 8.6 sec

INFO - 2026-09-29T20:13:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12568 downloaded in 8.5 sec

INFO - 2026-09-29T20:13:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:13:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:13:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:13:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12569 downloaded in 8.8 sec

INFO - 2026-09-29T20:14:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13670 downloaded in 9.0 sec

INFO - 2026-09-29T20:14:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13669 downloaded in 8.5 sec

INFO - 2026-09-29T20:14:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13667 downloaded in 8.5 sec

INFO - 2026-09-29T20:14:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13491 downloaded in 8.7 sec

INFO - 2026-09-29T20:14:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13528 downloaded in 8.5 sec

INFO - 2026-09-29T20:14:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:14:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13529 downloaded in 8.6 sec

INFO - 2026-09-29T20:14:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:14:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:14:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13531 downloaded in 8.6 sec

INFO - 2026-09-29T20:15:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13668 downloaded in 8.5 sec

INFO - 2026-09-29T20:15:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13659 downloaded in 8.5 sec

INFO - 2026-09-29T20:15:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13492 downloaded in 13.1 sec

INFO - 2026-09-29T20:15:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13647 downloaded in 8.6 sec

INFO - 2026-09-29T20:15:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13646 downloaded in 8.4 sec

INFO - 2026-09-29T20:15:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:15:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:15:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:15:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13644 downloaded in 8.7 sec

INFO - 2026-09-29T20:16:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13643 downloaded in 8.6 sec

INFO - 2026-09-29T20:16:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13642 downloaded in 8.5 sec

INFO - 2026-09-29T20:16:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13637 downloaded in 8.8 sec

INFO - 2026-09-29T20:16:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13636 downloaded in 8.7 sec

INFO - 2026-09-29T20:16:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13632 downloaded in 8.9 sec

INFO - 2026-09-29T20:16:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13631 downloaded in 8.5 sec

INFO - 2026-09-29T20:16:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:16:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:16:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:16:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13630 downloaded in 8.4 sec

INFO - 2026-09-29T20:17:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13629 downloaded in 12.8 sec

INFO - 2026-09-29T20:17:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13628 downloaded in 8.5 sec

INFO - 2026-09-29T20:17:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13540 downloaded in 8.8 sec

INFO - 2026-09-29T20:17:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13627 downloaded in 8.8 sec

INFO - 2026-09-29T20:17:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13635 downloaded in 8.7 sec

INFO - 2026-09-29T20:17:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:17:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13541 downloaded in 8.5 sec

INFO - 2026-09-29T20:17:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:17:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:17:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13542 downloaded in 8.6 sec

INFO - 2026-09-29T20:18:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13634 downloaded in 8.9 sec

INFO - 2026-09-29T20:18:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13633 downloaded in 8.6 sec

INFO - 2026-09-29T20:18:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13625 downloaded in 8.6 sec

INFO - 2026-09-29T20:18:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13624 downloaded in 9.0 sec

INFO - 2026-09-29T20:18:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:18:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13581 downloaded in 8.8 sec

INFO - 2026-09-29T20:18:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:18:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:18:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13494 downloaded in 12.9 sec

INFO - 2026-09-29T20:19:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13509 downloaded in 8.6 sec

INFO - 2026-09-29T20:19:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13522 downloaded in 8.6 sec

INFO - 2026-09-29T20:19:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13523 downloaded in 8.7 sec

INFO - 2026-09-29T20:19:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13524 downloaded in 8.5 sec

INFO - 2026-09-29T20:19:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13582 downloaded in 8.7 sec

INFO - 2026-09-29T20:19:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:19:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13544 downloaded in 8.6 sec

INFO - 2026-09-29T20:19:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:19:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:19:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13467 downloaded in 8.5 sec

INFO - 2026-09-29T20:20:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13465 downloaded in 8.5 sec

INFO - 2026-09-29T20:20:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13464 downloaded in 8.9 sec

INFO - 2026-09-29T20:20:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13584 downloaded in 8.7 sec

INFO - 2026-09-29T20:20:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13583 downloaded in 8.6 sec

INFO - 2026-09-29T20:20:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:20:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13549 downloaded in 12.9 sec

INFO - 2026-09-29T20:20:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:20:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:20:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13547 downloaded in 8.5 sec

INFO - 2026-09-29T20:21:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14197 downloaded in 8.6 sec

INFO - 2026-09-29T20:21:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13715 downloaded in 8.3 sec

INFO - 2026-09-29T20:21:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13717 downloaded in 8.5 sec

INFO - 2026-09-29T20:21:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13712 downloaded in 8.5 sec

INFO - 2026-09-29T20:21:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13718 downloaded in 8.4 sec

INFO - 2026-09-29T20:21:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:21:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13713 downloaded in 8.5 sec

INFO - 2026-09-29T20:21:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:21:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:21:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13716 downloaded in 8.6 sec

INFO - 2026-09-29T20:22:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13714 downloaded in 8.4 sec

INFO - 2026-09-29T20:22:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13746 downloaded in 8.5 sec

INFO - 2026-09-29T20:22:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13755 downloaded in 8.0 sec

INFO - 2026-09-29T20:22:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13588 downloaded in 12.9 sec

INFO - 2026-09-29T20:22:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13587 downloaded in 8.4 sec

INFO - 2026-09-29T20:22:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:22:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:22:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:22:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13617 downloaded in 8.3 sec

INFO - 2026-09-29T20:23:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13576 downloaded in 8.5 sec

INFO - 2026-09-29T20:23:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13440 downloaded in 8.4 sec

INFO - 2026-09-29T20:23:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13486 downloaded in 8.8 sec

INFO - 2026-09-29T20:23:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13439 downloaded in 8.5 sec

INFO - 2026-09-29T20:23:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13616 downloaded in 8.3 sec

INFO - 2026-09-29T20:23:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13615 downloaded in 8.5 sec

INFO - 2026-09-29T20:23:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:23:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:23:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:23:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13580 downloaded in 8.4 sec

INFO - 2026-09-29T20:24:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13577 downloaded in 8.2 sec

INFO - 2026-09-29T20:24:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13621 downloaded in 8.5 sec

INFO - 2026-09-29T20:24:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13619 downloaded in 14.6 sec

INFO - 2026-09-29T20:24:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13614 downloaded in 8.4 sec

INFO - 2026-09-29T20:24:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13613 downloaded in 8.4 sec

INFO - 2026-09-29T20:24:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:24:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13612 downloaded in 8.1 sec

INFO - 2026-09-29T20:24:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:24:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:24:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13656 downloaded in 8.6 sec

INFO - 2026-09-29T20:25:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13655 downloaded in 8.3 sec

INFO - 2026-09-29T20:25:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13654 downloaded in 8.4 sec

INFO - 2026-09-29T20:25:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13653 downloaded in 8.5 sec

INFO - 2026-09-29T20:25:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13429 downloaded in 8.3 sec

INFO - 2026-09-29T20:25:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13611 downloaded in 8.3 sec

INFO - 2026-09-29T20:25:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:25:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13489 downloaded in 8.5 sec

INFO - 2026-09-29T20:25:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:25:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:25:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13488 downloaded in 8.5 sec

INFO - 2026-09-29T20:26:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13574 downloaded in 13.0 sec

INFO - 2026-09-29T20:26:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13641 downloaded in 8.6 sec

INFO - 2026-09-29T20:26:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13640 downloaded in 8.1 sec

INFO - 2026-09-29T20:26:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13639 downloaded in 8.4 sec

INFO - 2026-09-29T20:26:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13579 downloaded in 8.2 sec

INFO - 2026-09-29T20:26:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:26:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:26:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:26:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13578 downloaded in 8.5 sec

INFO - 2026-09-29T20:27:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13575 downloaded in 8.5 sec

INFO - 2026-09-29T20:27:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13572 downloaded in 9.2 sec

INFO - 2026-09-29T20:27:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13487 downloaded in 8.4 sec

INFO - 2026-09-29T20:27:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13571 downloaded in 8.4 sec

INFO - 2026-09-29T20:27:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13435 downloaded in 8.3 sec

INFO - 2026-09-29T20:27:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:27:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13652 downloaded in 8.3 sec

INFO - 2026-09-29T20:27:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:27:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:27:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13427 downloaded in 12.6 sec

INFO - 2026-09-29T20:28:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13426 downloaded in 8.2 sec

INFO - 2026-09-29T20:28:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13620 downloaded in 8.6 sec

INFO - 2026-09-29T20:28:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13622 downloaded in 8.5 sec

INFO - 2026-09-29T20:28:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13570 downloaded in 8.8 sec

INFO - 2026-09-29T20:28:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13428 downloaded in 8.5 sec

INFO - 2026-09-29T20:28:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:28:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13434 downloaded in 8.2 sec

INFO - 2026-09-29T20:28:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:28:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:28:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13573 downloaded in 8.3 sec

INFO - 2026-09-29T20:29:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13618 downloaded in 8.5 sec

INFO - 2026-09-29T20:29:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13928 downloaded in 8.4 sec

INFO - 2026-09-29T20:29:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13947 downloaded in 8.3 sec

INFO - 2026-09-29T20:29:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13924 downloaded in 8.9 sec

INFO - 2026-09-29T20:29:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:29:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13920 downloaded in 13.3 sec

INFO - 2026-09-29T20:29:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:29:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:29:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13926 downloaded in 8.6 sec

INFO - 2026-09-29T20:30:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13945 downloaded in 8.5 sec

INFO - 2026-09-29T20:30:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13944 downloaded in 8.3 sec

INFO - 2026-09-29T20:30:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13943 downloaded in 8.6 sec

INFO - 2026-09-29T20:30:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13941 downloaded in 8.5 sec

INFO - 2026-09-29T20:30:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13922 downloaded in 8.4 sec

INFO - 2026-09-29T20:30:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:30:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13946 downloaded in 8.2 sec

INFO - 2026-09-29T20:30:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:30:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:30:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13917 downloaded in 8.6 sec

INFO - 2026-09-29T20:31:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13940 downloaded in 8.7 sec

INFO - 2026-09-29T20:31:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13919 downloaded in 8.2 sec

INFO - 2026-09-29T20:31:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13915 downloaded in 8.3 sec

INFO - 2026-09-29T20:31:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13939 downloaded in 13.2 sec

INFO - 2026-09-29T20:31:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13938 downloaded in 8.7 sec

INFO - 2026-09-29T20:31:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:31:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:31:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:31:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13936 downloaded in 8.4 sec

INFO - 2026-09-29T20:32:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13934 downloaded in 8.2 sec

INFO - 2026-09-29T20:32:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13930 downloaded in 8.4 sec

INFO - 2026-09-29T20:32:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13914 downloaded in 8.3 sec

INFO - 2026-09-29T20:32:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13912 downloaded in 8.5 sec

INFO - 2026-09-29T20:32:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13911 downloaded in 8.5 sec

INFO - 2026-09-29T20:32:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13942 downloaded in 8.5 sec

INFO - 2026-09-29T20:32:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:32:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:32:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:32:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14089 downloaded in 8.3 sec

INFO - 2026-09-29T20:33:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14100 downloaded in 8.4 sec

INFO - 2026-09-29T20:33:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13721 downloaded in 8.7 sec

INFO - 2026-09-29T20:33:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13719 downloaded in 12.5 sec

INFO - 2026-09-29T20:33:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13720 downloaded in 8.3 sec

INFO - 2026-09-29T20:33:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13860 downloaded in 9.4 sec

INFO - 2026-09-29T20:33:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:33:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13861 downloaded in 9.3 sec

INFO - 2026-09-29T20:33:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:33:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:33:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13862 downloaded in 8.3 sec

INFO - 2026-09-29T20:34:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13863 downloaded in 8.3 sec

INFO - 2026-09-29T20:34:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13864 downloaded in 8.7 sec

INFO - 2026-09-29T20:34:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13841 downloaded in 9.3 sec

INFO - 2026-09-29T20:34:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13840 downloaded in 8.3 sec

INFO - 2026-09-29T20:34:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13839 downloaded in 8.7 sec

INFO - 2026-09-29T20:34:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:34:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:34:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:34:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13838 downloaded in 8.5 sec

INFO - 2026-09-29T20:35:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13857 downloaded in 9.2 sec

INFO - 2026-09-29T20:35:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13836 downloaded in 11.9 sec

INFO - 2026-09-29T20:35:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13835 downloaded in 8.6 sec

INFO - 2026-09-29T20:35:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13832 downloaded in 9.5 sec

INFO - 2026-09-29T20:35:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13830 downloaded in 9.2 sec

INFO - 2026-09-29T20:35:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:35:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13837 downloaded in 8.4 sec

INFO - 2026-09-29T20:35:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:35:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:35:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13875 downloaded in 9.0 sec

INFO - 2026-09-29T20:36:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13871 downloaded in 8.6 sec

INFO - 2026-09-29T20:36:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13831 downloaded in 9.1 sec

INFO - 2026-09-29T20:36:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13829 downloaded in 9.5 sec

INFO - 2026-09-29T20:36:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13856 downloaded in 9.3 sec

INFO - 2026-09-29T20:36:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:36:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13879 downloaded in 9.4 sec

INFO - 2026-09-29T20:36:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:36:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:36:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13834 downloaded in 8.5 sec

INFO - 2026-09-29T20:37:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13833 downloaded in 13.8 sec

INFO - 2026-09-29T20:37:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13858 downloaded in 9.2 sec

INFO - 2026-09-29T20:37:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13859 downloaded in 9.4 sec

INFO - 2026-09-29T20:37:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13870 downloaded in 8.4 sec

INFO - 2026-09-29T20:37:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13872 downloaded in 8.3 sec

INFO - 2026-09-29T20:37:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:37:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:37:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:37:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13873 downloaded in 8.5 sec

INFO - 2026-09-29T20:38:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13878 downloaded in 8.5 sec

INFO - 2026-09-29T20:38:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13874 downloaded in 9.4 sec

INFO - 2026-09-29T20:38:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13877 downloaded in 9.1 sec

INFO - 2026-09-29T20:38:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13855 downloaded in 9.4 sec

INFO - 2026-09-29T20:38:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13876 downloaded in 8.5 sec

INFO - 2026-09-29T20:38:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:38:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14018 downloaded in 8.6 sec

INFO - 2026-09-29T20:38:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:38:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:38:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13759 downloaded in 12.9 sec

INFO - 2026-09-29T20:39:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11067 downloaded in 8.6 sec

INFO - 2026-09-29T20:39:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13749 downloaded in 8.5 sec

INFO - 2026-09-29T20:39:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13728 downloaded in 8.6 sec

INFO - 2026-09-29T20:39:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13748 downloaded in 8.7 sec

INFO - 2026-09-29T20:39:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13752 downloaded in 8.3 sec

INFO - 2026-09-29T20:39:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:39:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:39:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:39:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13753 downloaded in 8.3 sec

INFO - 2026-09-29T20:40:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13732 downloaded in 8.6 sec

INFO - 2026-09-29T20:40:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13733 downloaded in 8.1 sec

INFO - 2026-09-29T20:40:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13734 downloaded in 8.6 sec

INFO - 2026-09-29T20:40:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13735 downloaded in 8.6 sec

INFO - 2026-09-29T20:40:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13736 downloaded in 8.5 sec

INFO - 2026-09-29T20:40:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:40:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13756 downloaded in 12.7 sec

INFO - 2026-09-29T20:40:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:40:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:40:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13677 downloaded in 8.3 sec

INFO - 2026-09-29T20:41:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13757 downloaded in 8.4 sec

INFO - 2026-09-29T20:41:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13751 downloaded in 8.7 sec

INFO - 2026-09-29T20:41:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13758 downloaded in 8.5 sec

INFO - 2026-09-29T20:41:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13754 downloaded in 8.5 sec

INFO - 2026-09-29T20:41:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13760 downloaded in 8.6 sec

INFO - 2026-09-29T20:41:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:41:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13750 downloaded in 8.4 sec

INFO - 2026-09-29T20:41:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:41:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:41:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13761 downloaded in 8.0 sec

INFO - 2026-09-29T20:42:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13711 downloaded in 8.7 sec

INFO - 2026-09-29T20:42:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13710 downloaded in 8.3 sec

INFO - 2026-09-29T20:42:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13709 downloaded in 9.0 sec

INFO - 2026-09-29T20:42:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13708 downloaded in 8.5 sec

INFO - 2026-09-29T20:42:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:42:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13707 downloaded in 13.8 sec

INFO - 2026-09-29T20:42:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:42:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:42:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13764 downloaded in 8.3 sec

INFO - 2026-09-29T20:43:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13763 downloaded in 8.3 sec

INFO - 2026-09-29T20:43:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13762 downloaded in 8.4 sec

INFO - 2026-09-29T20:43:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13725 downloaded in 8.5 sec

INFO - 2026-09-29T20:43:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13723 downloaded in 8.4 sec

INFO - 2026-09-29T20:43:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13726 downloaded in 8.3 sec

INFO - 2026-09-29T20:43:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:43:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13722 downloaded in 8.4 sec

INFO - 2026-09-29T20:43:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:43:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:43:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13730 downloaded in 8.3 sec

INFO - 2026-09-29T20:44:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13729 downloaded in 8.2 sec

INFO - 2026-09-29T20:44:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13727 downloaded in 8.8 sec

INFO - 2026-09-29T20:44:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13724 downloaded in 12.4 sec

INFO - 2026-09-29T20:44:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13731 downloaded in 8.2 sec

INFO - 2026-09-29T20:44:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13785 downloaded in 8.9 sec

INFO - 2026-09-29T20:44:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:44:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13806 downloaded in 8.4 sec

INFO - 2026-09-29T20:44:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:44:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:44:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13803 downloaded in 9.2 sec

INFO - 2026-09-29T20:45:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13798 downloaded in 9.3 sec

INFO - 2026-09-29T20:45:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13802 downloaded in 9.1 sec

INFO - 2026-09-29T20:45:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13799 downloaded in 9.0 sec

INFO - 2026-09-29T20:45:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13801 downloaded in 9.2 sec

INFO - 2026-09-29T20:45:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:45:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13786 downloaded in 8.7 sec

INFO - 2026-09-29T20:45:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:45:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:45:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13792 downloaded in 8.7 sec

INFO - 2026-09-29T20:46:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13773 downloaded in 8.9 sec

INFO - 2026-09-29T20:46:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13791 downloaded in 13.1 sec

INFO - 2026-09-29T20:46:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13790 downloaded in 8.5 sec

INFO - 2026-09-29T20:46:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13772 downloaded in 8.6 sec

INFO - 2026-09-29T20:46:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13800 downloaded in 9.2 sec

INFO - 2026-09-29T20:46:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:46:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:46:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:46:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13805 downloaded in 9.2 sec

INFO - 2026-09-29T20:47:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13804 downloaded in 8.4 sec

INFO - 2026-09-29T20:47:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13787 downloaded in 8.4 sec

INFO - 2026-09-29T20:47:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13788 downloaded in 8.8 sec

INFO - 2026-09-29T20:47:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13789 downloaded in 8.6 sec

INFO - 2026-09-29T20:47:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13793 downloaded in 8.5 sec

INFO - 2026-09-29T20:47:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:47:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13794 downloaded in 8.6 sec

INFO - 2026-09-29T20:47:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:47:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:47:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13689 downloaded in 8.9 sec

INFO - 2026-09-29T20:48:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13688 downloaded in 13.1 sec

INFO - 2026-09-29T20:48:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13536 downloaded in 8.6 sec

INFO - 2026-09-29T20:48:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13817 downloaded in 8.9 sec

INFO - 2026-09-29T20:48:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13818 downloaded in 8.7 sec

INFO - 2026-09-29T20:48:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13819 downloaded in 8.6 sec

INFO - 2026-09-29T20:48:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:48:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:48:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:48:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13812 downloaded in 8.8 sec

INFO - 2026-09-29T20:49:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13815 downloaded in 8.6 sec

INFO - 2026-09-29T20:49:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13816 downloaded in 8.6 sec

INFO - 2026-09-29T20:49:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13811 downloaded in 9.2 sec

INFO - 2026-09-29T20:49:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13820 downloaded in 8.9 sec

INFO - 2026-09-29T20:49:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13814 downloaded in 8.8 sec

INFO - 2026-09-29T20:49:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:49:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13603 downloaded in 8.7 sec

INFO - 2026-09-29T20:49:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:49:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:49:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13608 downloaded in 13.6 sec

INFO - 2026-09-29T20:50:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13607 downloaded in 8.5 sec

INFO - 2026-09-29T20:50:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13609 downloaded in 8.5 sec

INFO - 2026-09-29T20:50:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13604 downloaded in 8.4 sec

INFO - 2026-09-29T20:50:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13602 downloaded in 8.6 sec

INFO - 2026-09-29T20:50:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13601 downloaded in 8.5 sec

INFO - 2026-09-29T20:50:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:50:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:50:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:50:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13606 downloaded in 8.4 sec

INFO - 2026-09-29T20:51:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13610 downloaded in 8.8 sec

INFO - 2026-09-29T20:51:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13605 downloaded in 8.4 sec

INFO - 2026-09-29T20:51:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 4955 downloaded in 8.6 sec

INFO - 2026-09-29T20:51:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13766 downloaded in 8.4 sec

INFO - 2026-09-29T20:51:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13767 downloaded in 8.7 sec

INFO - 2026-09-29T20:51:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:51:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10217 downloaded in 12.5 sec

INFO - 2026-09-29T20:51:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:51:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:51:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13599 downloaded in 8.2 sec

INFO - 2026-09-29T20:52:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12453 downloaded in 8.8 sec

INFO - 2026-09-29T20:52:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10086 downloaded in 8.8 sec

INFO - 2026-09-29T20:52:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9759 downloaded in 8.7 sec

INFO - 2026-09-29T20:52:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9761 downloaded in 8.4 sec

INFO - 2026-09-29T20:52:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10218 downloaded in 8.9 sec

INFO - 2026-09-29T20:52:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:52:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10222 downloaded in 8.6 sec

INFO - 2026-09-29T20:52:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:52:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:52:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10271 downloaded in 8.6 sec

INFO - 2026-09-29T20:53:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10286 downloaded in 8.8 sec

INFO - 2026-09-29T20:53:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10325 downloaded in 8.6 sec

INFO - 2026-09-29T20:53:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10246 downloaded in 8.8 sec

INFO - 2026-09-29T20:53:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10260 downloaded in 13.7 sec

INFO - 2026-09-29T20:53:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:53:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12452 downloaded in 8.6 sec

INFO - 2026-09-29T20:53:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:53:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:53:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12451 downloaded in 8.6 sec

INFO - 2026-09-29T20:54:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9762 downloaded in 8.7 sec

INFO - 2026-09-29T20:54:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12450 downloaded in 8.6 sec

INFO - 2026-09-29T20:54:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10088 downloaded in 8.6 sec

INFO - 2026-09-29T20:54:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9824 downloaded in 8.7 sec

INFO - 2026-09-29T20:54:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9823 downloaded in 8.2 sec

INFO - 2026-09-29T20:54:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:54:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9841 downloaded in 8.6 sec

INFO - 2026-09-29T20:54:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:54:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:54:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9840 downloaded in 8.5 sec

INFO - 2026-09-29T20:55:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10326 downloaded in 8.5 sec

INFO - 2026-09-29T20:55:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9763 downloaded in 8.6 sec

INFO - 2026-09-29T20:55:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10264 downloaded in 12.9 sec

INFO - 2026-09-29T20:55:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10235 downloaded in 8.6 sec

INFO - 2026-09-29T20:55:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:55:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10234 downloaded in 9.0 sec

INFO - 2026-09-29T20:55:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:55:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:55:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10231 downloaded in 8.5 sec

INFO - 2026-09-29T20:56:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10265 downloaded in 8.5 sec

INFO - 2026-09-29T20:56:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10268 downloaded in 8.6 sec

INFO - 2026-09-29T20:56:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10230 downloaded in 8.8 sec

INFO - 2026-09-29T20:56:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10229 downloaded in 8.5 sec

INFO - 2026-09-29T20:56:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10269 downloaded in 8.8 sec

INFO - 2026-09-29T20:56:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:56:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10270 downloaded in 9.0 sec

INFO - 2026-09-29T20:56:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:56:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:56:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10289 downloaded in 8.8 sec

INFO - 2026-09-29T20:57:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10485 downloaded in 8.5 sec

INFO - 2026-09-29T20:57:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9839 downloaded in 12.8 sec

INFO - 2026-09-29T20:57:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10263 downloaded in 8.5 sec

INFO - 2026-09-29T20:57:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10290 downloaded in 9.0 sec

INFO - 2026-09-29T20:57:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:57:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9755 downloaded in 8.6 sec

INFO - 2026-09-29T20:57:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:57:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:57:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10486 downloaded in 8.7 sec

INFO - 2026-09-29T20:58:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10283 downloaded in 8.8 sec

INFO - 2026-09-29T20:58:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9913 downloaded in 8.5 sec

INFO - 2026-09-29T20:58:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11160 downloaded in 8.8 sec

INFO - 2026-09-29T20:58:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10387 downloaded in 8.6 sec

INFO - 2026-09-29T20:58:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10221 downloaded in 8.7 sec

INFO - 2026-09-29T20:58:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:58:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10219 downloaded in 8.5 sec

INFO - 2026-09-29T20:58:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:58:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:58:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10298 downloaded in 8.7 sec

INFO - 2026-09-29T20:59:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10216 downloaded in 12.6 sec

INFO - 2026-09-29T20:59:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10161 downloaded in 8.6 sec

INFO - 2026-09-29T20:59:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10215 downloaded in 9.0 sec

INFO - 2026-09-29T20:59:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10214 downloaded in 8.5 sec

INFO - 2026-09-29T20:59:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T20:59:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10295 downloaded in 8.6 sec

INFO - 2026-09-29T20:59:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T20:59:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T20:59:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10212 downloaded in 8.9 sec

INFO - 2026-09-29T21:00:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10297 downloaded in 8.6 sec

INFO - 2026-09-29T21:00:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9760 downloaded in 8.7 sec

INFO - 2026-09-29T21:00:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10211 downloaded in 8.5 sec

INFO - 2026-09-29T21:00:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10649 downloaded in 9.1 sec

INFO - 2026-09-29T21:00:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10284 downloaded in 8.6 sec

INFO - 2026-09-29T21:00:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:00:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10285 downloaded in 8.6 sec

INFO - 2026-09-29T21:00:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:00:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:00:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10213 downloaded in 8.5 sec

INFO - 2026-09-29T21:01:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10296 downloaded in 13.7 sec

INFO - 2026-09-29T21:01:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9961 downloaded in 8.8 sec

INFO - 2026-09-29T21:01:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11236 downloaded in 8.6 sec

INFO - 2026-09-29T21:01:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9756 downloaded in 8.6 sec

INFO - 2026-09-29T21:01:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:01:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9757 downloaded in 8.8 sec

INFO - 2026-09-29T21:01:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:01:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:01:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10327 downloaded in 8.9 sec

INFO - 2026-09-29T21:02:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10291 downloaded in 8.6 sec

INFO - 2026-09-29T21:02:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9758 downloaded in 8.6 sec

INFO - 2026-09-29T21:02:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10292 downloaded in 8.7 sec

INFO - 2026-09-29T21:02:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10328 downloaded in 8.6 sec

INFO - 2026-09-29T21:02:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10245 downloaded in 8.7 sec

INFO - 2026-09-29T21:02:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:02:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:02:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:02:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9826 downloaded in 12.9 sec

INFO - 2026-09-29T21:03:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10244 downloaded in 8.7 sec

INFO - 2026-09-29T21:03:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10243 downloaded in 8.9 sec

INFO - 2026-09-29T21:03:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10100 downloaded in 9.4 sec

INFO - 2026-09-29T21:03:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10087 downloaded in 8.6 sec

INFO - 2026-09-29T21:03:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11266 downloaded in 8.7 sec

INFO - 2026-09-29T21:03:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:03:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14194 downloaded in 8.7 sec

INFO - 2026-09-29T21:03:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:03:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:03:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14193 downloaded in 8.4 sec

INFO - 2026-09-29T21:04:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14196 downloaded in 8.5 sec

INFO - 2026-09-29T21:04:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14195 downloaded in 8.5 sec

INFO - 2026-09-29T21:04:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13438 downloaded in 8.2 sec

INFO - 2026-09-29T21:04:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13437 downloaded in 8.5 sec

INFO - 2026-09-29T21:04:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13436 downloaded in 12.9 sec

INFO - 2026-09-29T21:04:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:04:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:04:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:04:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11231 downloaded in 8.7 sec

INFO - 2026-09-29T21:05:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13456 downloaded in 8.5 sec

INFO - 2026-09-29T21:05:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10233 downloaded in 8.5 sec

INFO - 2026-09-29T21:05:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10254 downloaded in 8.7 sec

INFO - 2026-09-29T21:05:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10293 downloaded in 8.2 sec

INFO - 2026-09-29T21:05:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10236 downloaded in 8.5 sec

INFO - 2026-09-29T21:05:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10226 downloaded in 8.2 sec

INFO - 2026-09-29T21:05:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:05:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:05:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:05:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10388 downloaded in 8.3 sec

INFO - 2026-09-29T21:06:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10389 downloaded in 8.4 sec

INFO - 2026-09-29T21:06:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10225 downloaded in 8.4 sec

INFO - 2026-09-29T21:06:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10227 downloaded in 8.7 sec

INFO - 2026-09-29T21:06:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10232 downloaded in 12.9 sec

INFO - 2026-09-29T21:06:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10237 downloaded in 8.3 sec

INFO - 2026-09-29T21:06:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:06:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10238 downloaded in 8.7 sec

INFO - 2026-09-29T21:06:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:06:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:06:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10239 downloaded in 8.4 sec

INFO - 2026-09-29T21:07:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10240 downloaded in 8.5 sec

INFO - 2026-09-29T21:07:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10241 downloaded in 8.4 sec

INFO - 2026-09-29T21:07:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10247 downloaded in 8.5 sec

INFO - 2026-09-29T21:07:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10248 downloaded in 8.4 sec

INFO - 2026-09-29T21:07:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10249 downloaded in 8.1 sec

INFO - 2026-09-29T21:07:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:07:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10253 downloaded in 9.3 sec

INFO - 2026-09-29T21:07:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:07:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:07:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10255 downloaded in 8.6 sec

INFO - 2026-09-29T21:08:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10256 downloaded in 8.3 sec

INFO - 2026-09-29T21:08:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10220 downloaded in 12.8 sec

INFO - 2026-09-29T21:08:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10250 downloaded in 9.0 sec

INFO - 2026-09-29T21:08:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10251 downloaded in 8.3 sec

INFO - 2026-09-29T21:08:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:08:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10252 downloaded in 8.3 sec

INFO - 2026-09-29T21:08:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:08:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:08:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10258 downloaded in 8.3 sec

INFO - 2026-09-29T21:09:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10262 downloaded in 8.5 sec

INFO - 2026-09-29T21:09:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10257 downloaded in 8.2 sec

INFO - 2026-09-29T21:09:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10261 downloaded in 8.3 sec

INFO - 2026-09-29T21:09:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10354 downloaded in 8.5 sec

INFO - 2026-09-29T21:09:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10294 downloaded in 8.5 sec

INFO - 2026-09-29T21:09:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:09:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10390 downloaded in 9.1 sec

INFO - 2026-09-29T21:09:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:09:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:09:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9994 downloaded in 8.3 sec

INFO - 2026-09-29T21:10:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10003 downloaded in 13.1 sec

INFO - 2026-09-29T21:10:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9993 downloaded in 8.3 sec

INFO - 2026-09-29T21:10:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9992 downloaded in 8.4 sec

INFO - 2026-09-29T21:10:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9991 downloaded in 8.3 sec

INFO - 2026-09-29T21:10:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9989 downloaded in 8.4 sec

INFO - 2026-09-29T21:10:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:10:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9988 downloaded in 8.4 sec

INFO - 2026-09-29T21:10:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:10:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:10:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9919 downloaded in 8.5 sec

INFO - 2026-09-29T21:11:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9987 downloaded in 8.6 sec

INFO - 2026-09-29T21:11:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9985 downloaded in 8.2 sec

INFO - 2026-09-29T21:11:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9977 downloaded in 8.4 sec

INFO - 2026-09-29T21:11:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9942 downloaded in 8.4 sec

INFO - 2026-09-29T21:11:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:11:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9968 downloaded in 8.8 sec

INFO - 2026-09-29T21:11:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:11:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:11:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9984 downloaded in 12.9 sec

INFO - 2026-09-29T21:12:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9983 downloaded in 8.2 sec

INFO - 2026-09-29T21:12:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9920 downloaded in 8.4 sec

INFO - 2026-09-29T21:12:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9941 downloaded in 8.4 sec

INFO - 2026-09-29T21:12:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9939 downloaded in 8.3 sec

INFO - 2026-09-29T21:12:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9921 downloaded in 8.5 sec

INFO - 2026-09-29T21:12:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:12:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9922 downloaded in 8.6 sec

INFO - 2026-09-29T21:12:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:12:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:12:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9965 downloaded in 8.7 sec

INFO - 2026-09-29T21:13:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9964 downloaded in 8.3 sec

INFO - 2026-09-29T21:13:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9963 downloaded in 8.5 sec

INFO - 2026-09-29T21:13:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9938 downloaded in 8.5 sec

INFO - 2026-09-29T21:13:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9982 downloaded in 8.2 sec

INFO - 2026-09-29T21:13:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9981 downloaded in 8.1 sec

INFO - 2026-09-29T21:13:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:13:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:13:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:13:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9955 downloaded in 13.0 sec

INFO - 2026-09-29T21:14:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9937 downloaded in 8.1 sec

INFO - 2026-09-29T21:14:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9954 downloaded in 8.2 sec

INFO - 2026-09-29T21:14:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9936 downloaded in 8.4 sec

INFO - 2026-09-29T21:14:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9923 downloaded in 8.1 sec

INFO - 2026-09-29T21:14:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9953 downloaded in 8.4 sec

INFO - 2026-09-29T21:14:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9951 downloaded in 8.3 sec

INFO - 2026-09-29T21:14:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:14:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9924 downloaded in 8.3 sec

INFO - 2026-09-29T21:14:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:14:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:14:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9950 downloaded in 8.3 sec

INFO - 2026-09-29T21:15:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9925 downloaded in 8.1 sec

INFO - 2026-09-29T21:15:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9962 downloaded in 8.0 sec

INFO - 2026-09-29T21:15:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9931 downloaded in 12.7 sec

INFO - 2026-09-29T21:15:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9935 downloaded in 8.2 sec

INFO - 2026-09-29T21:15:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9915 downloaded in 8.2 sec

INFO - 2026-09-29T21:15:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:15:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:15:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:15:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9949 downloaded in 8.3 sec

INFO - 2026-09-29T21:16:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9948 downloaded in 8.0 sec

INFO - 2026-09-29T21:16:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9934 downloaded in 8.1 sec

INFO - 2026-09-29T21:16:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9947 downloaded in 8.1 sec

INFO - 2026-09-29T21:16:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9916 downloaded in 8.3 sec

INFO - 2026-09-29T21:16:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9976 downloaded in 8.3 sec

INFO - 2026-09-29T21:16:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10001 downloaded in 8.4 sec

INFO - 2026-09-29T21:16:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:16:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:16:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:16:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9914 downloaded in 8.1 sec

INFO - 2026-09-29T21:17:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9978 downloaded in 8.6 sec

INFO - 2026-09-29T21:17:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9979 downloaded in 13.4 sec

INFO - 2026-09-29T21:17:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9944 downloaded in 8.0 sec

INFO - 2026-09-29T21:17:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9932 downloaded in 8.4 sec

INFO - 2026-09-29T21:17:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9926 downloaded in 8.2 sec

INFO - 2026-09-29T21:17:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:17:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9972 downloaded in 8.2 sec

INFO - 2026-09-29T21:17:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:17:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:17:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9943 downloaded in 8.2 sec

INFO - 2026-09-29T21:18:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9971 downloaded in 8.2 sec

INFO - 2026-09-29T21:18:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9970 downloaded in 8.2 sec

INFO - 2026-09-29T21:18:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9928 downloaded in 8.1 sec

INFO - 2026-09-29T21:18:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9929 downloaded in 8.4 sec

INFO - 2026-09-29T21:18:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9995 downloaded in 8.2 sec

INFO - 2026-09-29T21:18:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:18:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9996 downloaded in 8.1 sec

INFO - 2026-09-29T21:18:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:18:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:18:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9997 downloaded in 12.4 sec

INFO - 2026-09-29T21:19:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9945 downloaded in 8.1 sec

INFO - 2026-09-29T21:19:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9973 downloaded in 8.3 sec

INFO - 2026-09-29T21:19:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9974 downloaded in 8.0 sec

INFO - 2026-09-29T21:19:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9975 downloaded in 8.3 sec

INFO - 2026-09-29T21:19:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9930 downloaded in 8.5 sec

INFO - 2026-09-29T21:19:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:19:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9917 downloaded in 8.1 sec

INFO - 2026-09-29T21:19:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:19:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:19:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9998 downloaded in 8.2 sec

INFO - 2026-09-29T21:20:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10000 downloaded in 8.1 sec

INFO - 2026-09-29T21:20:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9980 downloaded in 8.1 sec

INFO - 2026-09-29T21:20:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10002 downloaded in 8.1 sec

INFO - 2026-09-29T21:20:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9933 downloaded in 8.3 sec

INFO - 2026-09-29T21:20:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9967 downloaded in 12.9 sec

INFO - 2026-09-29T21:20:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:20:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:20:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:20:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9969 downloaded in 8.2 sec

INFO - 2026-09-29T21:21:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9946 downloaded in 8.7 sec

INFO - 2026-09-29T21:21:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9966 downloaded in 8.1 sec

INFO - 2026-09-29T21:21:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9918 downloaded in 8.2 sec

INFO - 2026-09-29T21:21:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9927 downloaded in 8.1 sec

INFO - 2026-09-29T21:21:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9940 downloaded in 8.2 sec

INFO - 2026-09-29T21:21:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9952 downloaded in 8.4 sec

INFO - 2026-09-29T21:21:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:21:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:21:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:21:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9999 downloaded in 8.2 sec

INFO - 2026-09-29T21:22:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9990 downloaded in 8.0 sec

INFO - 2026-09-29T21:22:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9986 downloaded in 8.2 sec

INFO - 2026-09-29T21:22:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13453 downloaded in 8.1 sec

INFO - 2026-09-29T21:22:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13452 downloaded in 12.6 sec

INFO - 2026-09-29T21:22:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13451 downloaded in 8.5 sec

INFO - 2026-09-29T21:22:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:22:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13450 downloaded in 8.5 sec

INFO - 2026-09-29T21:22:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:22:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:22:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13585 downloaded in 8.4 sec

INFO - 2026-09-29T21:23:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13419 downloaded in 8.6 sec

INFO - 2026-09-29T21:23:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13421 downloaded in 8.4 sec

INFO - 2026-09-29T21:23:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13424 downloaded in 8.2 sec

INFO - 2026-09-29T21:23:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13423 downloaded in 8.2 sec

INFO - 2026-09-29T21:23:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13431 downloaded in 8.4 sec

INFO - 2026-09-29T21:23:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:23:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13403 downloaded in 8.2 sec

INFO - 2026-09-29T21:23:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:23:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:23:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13407 downloaded in 8.4 sec

INFO - 2026-09-29T21:24:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13408 downloaded in 8.3 sec

INFO - 2026-09-29T21:24:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13410 downloaded in 12.8 sec

INFO - 2026-09-29T21:24:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13406 downloaded in 8.6 sec

INFO - 2026-09-29T21:24:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13409 downloaded in 8.5 sec

INFO - 2026-09-29T21:24:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13411 downloaded in 8.4 sec

INFO - 2026-09-29T21:24:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:24:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:24:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:24:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13415 downloaded in 8.1 sec

INFO - 2026-09-29T21:25:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13416 downloaded in 8.5 sec

INFO - 2026-09-29T21:25:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13422 downloaded in 8.2 sec

INFO - 2026-09-29T21:25:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13417 downloaded in 8.5 sec

INFO - 2026-09-29T21:25:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13404 downloaded in 8.2 sec

INFO - 2026-09-29T21:25:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13405 downloaded in 8.6 sec

INFO - 2026-09-29T21:25:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13418 downloaded in 8.6 sec

INFO - 2026-09-29T21:25:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:25:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:25:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:25:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13413 downloaded in 8.2 sec

INFO - 2026-09-29T21:26:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13412 downloaded in 12.9 sec

INFO - 2026-09-29T21:26:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13414 downloaded in 8.7 sec

INFO - 2026-09-29T21:26:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13402 downloaded in 8.9 sec

INFO - 2026-09-29T21:26:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13454 downloaded in 8.1 sec

INFO - 2026-09-29T21:26:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13455 downloaded in 8.3 sec

INFO - 2026-09-29T21:26:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:26:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11230 downloaded in 8.5 sec

INFO - 2026-09-29T21:26:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:26:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:26:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13676 downloaded in 8.4 sec

INFO - 2026-09-29T21:27:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13441 downloaded in 8.1 sec

INFO - 2026-09-29T21:27:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13446 downloaded in 8.6 sec

INFO - 2026-09-29T21:27:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13445 downloaded in 8.5 sec

INFO - 2026-09-29T21:27:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13447 downloaded in 8.2 sec

INFO - 2026-09-29T21:27:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13444 downloaded in 8.5 sec

INFO - 2026-09-29T21:27:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:27:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:27:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:27:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13442 downloaded in 13.4 sec

INFO - 2026-09-29T21:28:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13443 downloaded in 8.3 sec

INFO - 2026-09-29T21:28:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13485 downloaded in 8.6 sec

INFO - 2026-09-29T21:28:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13495 downloaded in 8.4 sec

INFO - 2026-09-29T21:28:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13496 downloaded in 9.0 sec

INFO - 2026-09-29T21:28:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13498 downloaded in 8.4 sec

INFO - 2026-09-29T21:28:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:28:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13504 downloaded in 8.2 sec

INFO - 2026-09-29T21:28:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:28:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:28:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13481 downloaded in 8.6 sec

INFO - 2026-09-29T21:29:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13472 downloaded in 8.4 sec

INFO - 2026-09-29T21:29:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13470 downloaded in 8.5 sec

INFO - 2026-09-29T21:29:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13469 downloaded in 8.4 sec

INFO - 2026-09-29T21:29:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13476 downloaded in 8.9 sec

INFO - 2026-09-29T21:29:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13497 downloaded in 13.9 sec

INFO - 2026-09-29T21:29:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:29:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:29:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:29:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13500 downloaded in 8.3 sec

INFO - 2026-09-29T21:30:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13501 downloaded in 8.6 sec

INFO - 2026-09-29T21:30:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13502 downloaded in 8.4 sec

INFO - 2026-09-29T21:30:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13503 downloaded in 8.5 sec

INFO - 2026-09-29T21:30:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13478 downloaded in 8.7 sec

INFO - 2026-09-29T21:30:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13477 downloaded in 8.5 sec

INFO - 2026-09-29T21:30:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13507 downloaded in 8.8 sec

INFO - 2026-09-29T21:30:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:30:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:30:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:30:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13508 downloaded in 8.5 sec

INFO - 2026-09-29T21:31:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13514 downloaded in 8.6 sec

INFO - 2026-09-29T21:31:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13511 downloaded in 9.4 sec

INFO - 2026-09-29T21:31:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13513 downloaded in 8.9 sec

INFO - 2026-09-29T21:31:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13516 downloaded in 13.1 sec

INFO - 2026-09-29T21:31:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13517 downloaded in 9.4 sec

INFO - 2026-09-29T21:31:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:31:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:31:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:31:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13518 downloaded in 9.4 sec

INFO - 2026-09-29T21:32:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13480 downloaded in 8.6 sec

INFO - 2026-09-29T21:32:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13499 downloaded in 8.8 sec

INFO - 2026-09-29T21:32:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13506 downloaded in 8.6 sec

INFO - 2026-09-29T21:32:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13482 downloaded in 8.4 sec

INFO - 2026-09-29T21:32:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13483 downloaded in 8.6 sec

INFO - 2026-09-29T21:32:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:32:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13484 downloaded in 8.7 sec

INFO - 2026-09-29T21:32:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:32:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:32:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13468 downloaded in 8.7 sec

INFO - 2026-09-29T21:33:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13519 downloaded in 9.0 sec

INFO - 2026-09-29T21:33:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13510 downloaded in 9.1 sec

INFO - 2026-09-29T21:33:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13479 downloaded in 13.8 sec

INFO - 2026-09-29T21:33:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12614 downloaded in 8.7 sec

INFO - 2026-09-29T21:33:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:33:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12606 downloaded in 8.6 sec

INFO - 2026-09-29T21:33:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:33:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:33:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10228 downloaded in 8.4 sec

INFO - 2026-09-29T21:34:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 12612 downloaded in 8.7 sec

INFO - 2026-09-29T21:34:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9283 downloaded in 8.7 sec

INFO - 2026-09-29T21:34:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9273 downloaded in 8.4 sec

INFO - 2026-09-29T21:34:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9281 downloaded in 8.5 sec

INFO - 2026-09-29T21:34:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9282 downloaded in 8.6 sec

INFO - 2026-09-29T21:34:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:34:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9280 downloaded in 8.6 sec

INFO - 2026-09-29T21:34:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:34:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:34:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9108 downloaded in 8.3 sec

INFO - 2026-09-29T21:35:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10121 downloaded in 9.2 sec

INFO - 2026-09-29T21:35:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10115 downloaded in 13.7 sec

INFO - 2026-09-29T21:35:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10123 downloaded in 8.7 sec

INFO - 2026-09-29T21:35:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10124 downloaded in 8.6 sec

INFO - 2026-09-29T21:35:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10125 downloaded in 8.7 sec

INFO - 2026-09-29T21:35:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:35:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:35:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:35:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10126 downloaded in 8.6 sec

INFO - 2026-09-29T21:36:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10127 downloaded in 8.7 sec

INFO - 2026-09-29T21:36:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10147 downloaded in 8.5 sec

INFO - 2026-09-29T21:36:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10114 downloaded in 8.5 sec

INFO - 2026-09-29T21:36:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10118 downloaded in 8.8 sec

INFO - 2026-09-29T21:36:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10122 downloaded in 8.4 sec

INFO - 2026-09-29T21:36:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:36:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11830 downloaded in 8.5 sec

INFO - 2026-09-29T21:36:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:36:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:36:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11827 downloaded in 8.8 sec

INFO - 2026-09-29T21:37:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11825 downloaded in 13.2 sec

INFO - 2026-09-29T21:37:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11828 downloaded in 8.5 sec

INFO - 2026-09-29T21:37:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11826 downloaded in 8.8 sec

INFO - 2026-09-29T21:37:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11829 downloaded in 8.4 sec

INFO - 2026-09-29T21:37:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 11068 downloaded in 9.1 sec

INFO - 2026-09-29T21:37:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:37:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:37:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:37:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10169 downloaded in 9.2 sec

INFO - 2026-09-29T21:38:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10170 downloaded in 8.8 sec

INFO - 2026-09-29T21:38:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8738 downloaded in 8.4 sec

INFO - 2026-09-29T21:38:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8504 downloaded in 8.6 sec

INFO - 2026-09-29T21:38:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8848 downloaded in 8.7 sec

INFO - 2026-09-29T21:38:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8506 downloaded in 8.6 sec

INFO - 2026-09-29T21:38:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:38:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8507 downloaded in 8.5 sec

INFO - 2026-09-29T21:38:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:38:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:38:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8512 downloaded in 13.5 sec

INFO - 2026-09-29T21:39:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8513 downloaded in 8.8 sec

INFO - 2026-09-29T21:39:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8519 downloaded in 8.9 sec

INFO - 2026-09-29T21:39:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8522 downloaded in 8.4 sec

INFO - 2026-09-29T21:39:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8523 downloaded in 8.6 sec

INFO - 2026-09-29T21:39:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8505 downloaded in 8.9 sec

INFO - 2026-09-29T21:39:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:39:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:39:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:39:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8616 downloaded in 8.6 sec

INFO - 2026-09-29T21:40:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8617 downloaded in 8.7 sec

INFO - 2026-09-29T21:40:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8601 downloaded in 8.5 sec

INFO - 2026-09-29T21:40:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8602 downloaded in 8.7 sec

INFO - 2026-09-29T21:40:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8603 downloaded in 8.4 sec

INFO - 2026-09-29T21:40:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8605 downloaded in 8.9 sec

INFO - 2026-09-29T21:40:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:40:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8606 downloaded in 13.1 sec

INFO - 2026-09-29T21:40:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:40:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:40:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8607 downloaded in 9.3 sec

INFO - 2026-09-29T21:41:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8608 downloaded in 8.9 sec

INFO - 2026-09-29T21:41:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8613 downloaded in 8.7 sec

INFO - 2026-09-29T21:41:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8614 downloaded in 8.7 sec

INFO - 2026-09-29T21:41:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8615 downloaded in 8.9 sec

INFO - 2026-09-29T21:41:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8618 downloaded in 8.6 sec

INFO - 2026-09-29T21:41:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:41:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:41:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:41:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8619 downloaded in 8.5 sec

INFO - 2026-09-29T21:42:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8620 downloaded in 8.5 sec

INFO - 2026-09-29T21:42:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8621 downloaded in 8.9 sec

INFO - 2026-09-29T21:42:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8622 downloaded in 8.3 sec

INFO - 2026-09-29T21:42:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8604 downloaded in 8.5 sec

INFO - 2026-09-29T21:42:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8623 downloaded in 9.0 sec

INFO - 2026-09-29T21:42:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:42:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:42:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:42:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9076 downloaded in 14.0 sec

INFO - 2026-09-29T21:43:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8739 downloaded in 8.9 sec

INFO - 2026-09-29T21:43:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8730 downloaded in 8.6 sec

INFO - 2026-09-29T21:43:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8731 downloaded in 8.6 sec

INFO - 2026-09-29T21:43:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8732 downloaded in 8.7 sec

INFO - 2026-09-29T21:43:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8733 downloaded in 8.4 sec

INFO - 2026-09-29T21:43:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:43:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8734 downloaded in 8.5 sec

INFO - 2026-09-29T21:43:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:43:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:43:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8735 downloaded in 8.7 sec

INFO - 2026-09-29T21:44:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8736 downloaded in 8.6 sec

INFO - 2026-09-29T21:44:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8737 downloaded in 8.6 sec

INFO - 2026-09-29T21:44:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8740 downloaded in 8.5 sec

INFO - 2026-09-29T21:44:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8741 downloaded in 13.2 sec

INFO - 2026-09-29T21:44:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8742 downloaded in 8.5 sec

INFO - 2026-09-29T21:44:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:44:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:44:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:44:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8743 downloaded in 8.7 sec

INFO - 2026-09-29T21:45:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8744 downloaded in 8.9 sec

INFO - 2026-09-29T21:45:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8745 downloaded in 8.5 sec

INFO - 2026-09-29T21:45:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8746 downloaded in 8.7 sec

INFO - 2026-09-29T21:45:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8729 downloaded in 8.8 sec

INFO - 2026-09-29T21:45:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8793 downloaded in 8.6 sec

INFO - 2026-09-29T21:45:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8836 downloaded in 8.4 sec

INFO - 2026-09-29T21:45:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:45:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:45:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:45:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8837 downloaded in 8.7 sec

INFO - 2026-09-29T21:46:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8838 downloaded in 8.8 sec

INFO - 2026-09-29T21:46:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8835 downloaded in 8.5 sec

INFO - 2026-09-29T21:46:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8854 downloaded in 13.5 sec

INFO - 2026-09-29T21:46:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8859 downloaded in 8.7 sec

INFO - 2026-09-29T21:46:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8855 downloaded in 8.8 sec

INFO - 2026-09-29T21:46:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:46:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:46:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:46:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8856 downloaded in 8.6 sec

INFO - 2026-09-29T21:47:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9025 downloaded in 8.7 sec

INFO - 2026-09-29T21:47:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9026 downloaded in 8.5 sec

INFO - 2026-09-29T21:47:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9035 downloaded in 8.9 sec

INFO - 2026-09-29T21:47:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9036 downloaded in 8.5 sec

INFO - 2026-09-29T21:47:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9037 downloaded in 8.5 sec

INFO - 2026-09-29T21:47:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9051 downloaded in 8.5 sec

INFO - 2026-09-29T21:47:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:47:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:47:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:47:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9024 downloaded in 8.7 sec

INFO - 2026-09-29T21:48:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9082 downloaded in 8.7 sec

INFO - 2026-09-29T21:48:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9083 downloaded in 12.6 sec

INFO - 2026-09-29T21:48:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9086 downloaded in 8.8 sec

INFO - 2026-09-29T21:48:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9087 downloaded in 8.7 sec

INFO - 2026-09-29T21:48:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9117 downloaded in 8.8 sec

INFO - 2026-09-29T21:48:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:48:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9074 downloaded in 8.7 sec

INFO - 2026-09-29T21:48:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:48:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:48:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9081 downloaded in 8.6 sec

INFO - 2026-09-29T21:49:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9116 downloaded in 9.0 sec

INFO - 2026-09-29T21:49:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9110 downloaded in 8.3 sec

INFO - 2026-09-29T21:49:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9111 downloaded in 8.4 sec

INFO - 2026-09-29T21:49:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9114 downloaded in 8.5 sec

INFO - 2026-09-29T21:49:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9115 downloaded in 8.5 sec

INFO - 2026-09-29T21:49:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:49:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:49:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:49:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9109 downloaded in 8.6 sec

INFO - 2026-09-29T21:50:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9187 downloaded in 13.1 sec

INFO - 2026-09-29T21:50:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9188 downloaded in 8.6 sec

INFO - 2026-09-29T21:50:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9643 downloaded in 8.7 sec

INFO - 2026-09-29T21:50:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9644 downloaded in 8.6 sec

INFO - 2026-09-29T21:50:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8503 downloaded in 9.0 sec

INFO - 2026-09-29T21:50:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:50:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9642 downloaded in 8.4 sec

INFO - 2026-09-29T21:50:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:50:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:50:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9112 downloaded in 9.0 sec

INFO - 2026-09-29T21:51:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9100 downloaded in 8.5 sec

INFO - 2026-09-29T21:51:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9189 downloaded in 8.9 sec

INFO - 2026-09-29T21:51:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14192 downloaded in 8.5 sec

INFO - 2026-09-29T21:51:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14297 downloaded in 8.8 sec

INFO - 2026-09-29T21:51:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:51:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10035 downloaded in 8.5 sec

INFO - 2026-09-29T21:51:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:51:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:51:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10025 downloaded in 12.4 sec

INFO - 2026-09-29T21:52:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10034 downloaded in 8.3 sec

INFO - 2026-09-29T21:52:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10172 downloaded in 8.6 sec

INFO - 2026-09-29T21:52:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10171 downloaded in 8.4 sec

INFO - 2026-09-29T21:52:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9028 downloaded in 8.2 sec

INFO - 2026-09-29T21:52:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9027 downloaded in 8.6 sec

INFO - 2026-09-29T21:52:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:52:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8791 downloaded in 8.5 sec

INFO - 2026-09-29T21:52:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:52:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:52:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8748 downloaded in 8.6 sec

INFO - 2026-09-29T21:53:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8715 downloaded in 8.0 sec

INFO - 2026-09-29T21:53:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8857 downloaded in 8.6 sec

INFO - 2026-09-29T21:53:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9038 downloaded in 8.6 sec

INFO - 2026-09-29T21:53:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9052 downloaded in 8.2 sec

INFO - 2026-09-29T21:53:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8718 downloaded in 12.4 sec

INFO - 2026-09-29T21:53:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:53:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:53:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:53:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8792 downloaded in 8.3 sec

INFO - 2026-09-29T21:54:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8790 downloaded in 8.6 sec

INFO - 2026-09-29T21:54:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8716 downloaded in 8.2 sec

INFO - 2026-09-29T21:54:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8717 downloaded in 8.1 sec

INFO - 2026-09-29T21:54:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9085 downloaded in 8.3 sec

INFO - 2026-09-29T21:54:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8719 downloaded in 8.3 sec

INFO - 2026-09-29T21:54:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8789 downloaded in 8.2 sec

INFO - 2026-09-29T21:54:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:54:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8720 downloaded in 8.5 sec

INFO - 2026-09-29T21:54:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:54:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:54:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8858 downloaded in 8.3 sec

INFO - 2026-09-29T21:55:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9084 downloaded in 8.2 sec

INFO - 2026-09-29T21:55:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8749 downloaded in 8.4 sec

INFO - 2026-09-29T21:55:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13695 downloaded in 13.4 sec

INFO - 2026-09-29T21:55:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9628 downloaded in 8.6 sec

INFO - 2026-09-29T21:55:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:55:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9545 downloaded in 8.6 sec

INFO - 2026-09-29T21:55:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:55:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:55:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9695 downloaded in 8.4 sec

INFO - 2026-09-29T21:56:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9586 downloaded in 8.9 sec

INFO - 2026-09-29T21:56:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9598 downloaded in 8.4 sec

INFO - 2026-09-29T21:56:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9872 downloaded in 8.3 sec

INFO - 2026-09-29T21:56:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9561 downloaded in 8.4 sec

INFO - 2026-09-29T21:56:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9870 downloaded in 8.4 sec

INFO - 2026-09-29T21:56:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:56:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9819 downloaded in 8.4 sec

INFO - 2026-09-29T21:56:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:56:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:56:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9682 downloaded in 8.4 sec

INFO - 2026-09-29T21:57:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9536 downloaded in 8.6 sec

INFO - 2026-09-29T21:57:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9707 downloaded in 8.7 sec

INFO - 2026-09-29T21:57:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9812 downloaded in 12.7 sec

INFO - 2026-09-29T21:57:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9742 downloaded in 8.4 sec

INFO - 2026-09-29T21:57:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9777 downloaded in 8.6 sec

INFO - 2026-09-29T21:57:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:57:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:57:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:57:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9728 downloaded in 8.5 sec

INFO - 2026-09-29T21:58:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9716 downloaded in 8.4 sec

INFO - 2026-09-29T21:58:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9673 downloaded in 8.4 sec

INFO - 2026-09-29T21:58:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9683 downloaded in 8.7 sec

INFO - 2026-09-29T21:58:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9664 downloaded in 8.4 sec

INFO - 2026-09-29T21:58:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9651 downloaded in 8.1 sec

INFO - 2026-09-29T21:58:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9641 downloaded in 8.6 sec

INFO - 2026-09-29T21:58:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:58:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:58:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:58:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9549 downloaded in 8.3 sec

INFO - 2026-09-29T21:59:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9621 downloaded in 8.4 sec

INFO - 2026-09-29T21:59:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9906 downloaded in 12.6 sec

INFO - 2026-09-29T21:59:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9788 downloaded in 8.4 sec

INFO - 2026-09-29T21:59:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9800 downloaded in 8.5 sec

INFO - 2026-09-29T21:59:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9609 downloaded in 8.5 sec

INFO - 2026-09-29T21:59:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T21:59:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9895 downloaded in 8.4 sec

INFO - 2026-09-29T21:59:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T21:59:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T21:59:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9752 downloaded in 8.5 sec

INFO - 2026-09-29T22:00:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9806 downloaded in 8.2 sec

INFO - 2026-09-29T22:00:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9881 downloaded in 11.2 sec

INFO - 2026-09-29T22:00:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9729 downloaded in 8.3 sec

INFO - 2026-09-29T22:00:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9770 downloaded in 8.3 sec

INFO - 2026-09-29T22:00:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:00:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9789 downloaded in 8.1 sec

INFO - 2026-09-29T22:00:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:00:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:00:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9814 downloaded in 12.9 sec

INFO - 2026-09-29T22:01:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9891 downloaded in 8.2 sec

INFO - 2026-09-29T22:01:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9820 downloaded in 8.1 sec

INFO - 2026-09-29T22:01:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9787 downloaded in 8.4 sec

INFO - 2026-09-29T22:01:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9786 downloaded in 8.2 sec

INFO - 2026-09-29T22:01:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9821 downloaded in 8.2 sec

INFO - 2026-09-29T22:01:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:01:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9822 downloaded in 8.4 sec

INFO - 2026-09-29T22:01:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:01:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:01:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9785 downloaded in 8.2 sec

INFO - 2026-09-29T22:02:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9784 downloaded in 8.1 sec

INFO - 2026-09-29T22:02:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9842 downloaded in 8.3 sec

INFO - 2026-09-29T22:02:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9843 downloaded in 8.3 sec

INFO - 2026-09-29T22:02:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9783 downloaded in 8.2 sec

INFO - 2026-09-29T22:02:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9782 downloaded in 13.3 sec

INFO - 2026-09-29T22:02:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:02:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9781 downloaded in 8.0 sec

INFO - 2026-09-29T22:02:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:02:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:02:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9892 downloaded in 8.8 sec

INFO - 2026-09-29T22:03:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9780 downloaded in 8.2 sec

INFO - 2026-09-29T22:03:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9893 downloaded in 8.1 sec

INFO - 2026-09-29T22:03:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9880 downloaded in 8.5 sec

INFO - 2026-09-29T22:03:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9894 downloaded in 8.4 sec

INFO - 2026-09-29T22:03:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9844 downloaded in 8.2 sec

INFO - 2026-09-29T22:03:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:03:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9845 downloaded in 8.1 sec

INFO - 2026-09-29T22:03:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:03:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:03:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9846 downloaded in 8.1 sec

INFO - 2026-09-29T22:04:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9847 downloaded in 8.3 sec

INFO - 2026-09-29T22:04:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9848 downloaded in 8.3 sec

INFO - 2026-09-29T22:04:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9849 downloaded in 13.6 sec

INFO - 2026-09-29T22:04:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9850 downloaded in 8.6 sec

INFO - 2026-09-29T22:04:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:04:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9851 downloaded in 8.2 sec

INFO - 2026-09-29T22:04:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:04:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:04:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9779 downloaded in 8.0 sec

INFO - 2026-09-29T22:05:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9896 downloaded in 8.5 sec

INFO - 2026-09-29T22:05:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9897 downloaded in 8.3 sec

INFO - 2026-09-29T22:05:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9852 downloaded in 8.0 sec

INFO - 2026-09-29T22:05:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9853 downloaded in 8.4 sec

INFO - 2026-09-29T22:05:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9854 downloaded in 7.9 sec

INFO - 2026-09-29T22:05:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9855 downloaded in 8.1 sec

INFO - 2026-09-29T22:05:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:05:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:05:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:05:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9856 downloaded in 8.2 sec

INFO - 2026-09-29T22:06:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9857 downloaded in 8.1 sec

INFO - 2026-09-29T22:06:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9858 downloaded in 13.2 sec

INFO - 2026-09-29T22:06:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9898 downloaded in 8.1 sec

INFO - 2026-09-29T22:06:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9778 downloaded in 8.3 sec

INFO - 2026-09-29T22:06:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9776 downloaded in 8.2 sec

INFO - 2026-09-29T22:06:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:06:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9859 downloaded in 8.5 sec

INFO - 2026-09-29T22:06:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:06:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:06:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9899 downloaded in 8.3 sec

INFO - 2026-09-29T22:07:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9900 downloaded in 8.3 sec

INFO - 2026-09-29T22:07:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9902 downloaded in 8.2 sec

INFO - 2026-09-29T22:07:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9903 downloaded in 8.0 sec

INFO - 2026-09-29T22:07:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9904 downloaded in 8.4 sec

INFO - 2026-09-29T22:07:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9905 downloaded in 8.1 sec

INFO - 2026-09-29T22:07:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:07:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9907 downloaded in 8.2 sec

INFO - 2026-09-29T22:07:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:07:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:07:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9775 downloaded in 12.9 sec

INFO - 2026-09-29T22:08:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9774 downloaded in 8.3 sec

INFO - 2026-09-29T22:08:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9769 downloaded in 8.0 sec

INFO - 2026-09-29T22:08:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9768 downloaded in 8.1 sec

INFO - 2026-09-29T22:08:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9767 downloaded in 8.3 sec

INFO - 2026-09-29T22:08:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9908 downloaded in 8.1 sec

INFO - 2026-09-29T22:08:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:08:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9766 downloaded in 8.3 sec

INFO - 2026-09-29T22:08:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:08:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:08:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9765 downloaded in 8.0 sec

INFO - 2026-09-29T22:09:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9764 downloaded in 8.1 sec

INFO - 2026-09-29T22:09:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9773 downloaded in 8.1 sec

INFO - 2026-09-29T22:09:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9772 downloaded in 8.3 sec

INFO - 2026-09-29T22:09:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9909 downloaded in 8.2 sec

INFO - 2026-09-29T22:09:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9910 downloaded in 8.0 sec

INFO - 2026-09-29T22:09:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:09:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:09:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:09:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9911 downloaded in 12.2 sec

INFO - 2026-09-29T22:10:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9884 downloaded in 8.5 sec

INFO - 2026-09-29T22:10:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9883 downloaded in 8.5 sec

INFO - 2026-09-29T22:10:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9771 downloaded in 8.1 sec

INFO - 2026-09-29T22:10:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9754 downloaded in 8.3 sec

INFO - 2026-09-29T22:10:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9753 downloaded in 8.4 sec

INFO - 2026-09-29T22:10:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9750 downloaded in 8.0 sec

INFO - 2026-09-29T22:10:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:10:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:10:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:10:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9749 downloaded in 8.3 sec

INFO - 2026-09-29T22:11:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9748 downloaded in 8.3 sec

INFO - 2026-09-29T22:11:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9747 downloaded in 8.1 sec

INFO - 2026-09-29T22:11:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9882 downloaded in 8.1 sec

INFO - 2026-09-29T22:11:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9746 downloaded in 12.4 sec

INFO - 2026-09-29T22:11:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9745 downloaded in 8.0 sec

INFO - 2026-09-29T22:11:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:11:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9879 downloaded in 8.1 sec

INFO - 2026-09-29T22:11:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:11:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:11:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9744 downloaded in 8.4 sec

INFO - 2026-09-29T22:12:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9741 downloaded in 8.2 sec

INFO - 2026-09-29T22:12:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9740 downloaded in 8.2 sec

INFO - 2026-09-29T22:12:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9739 downloaded in 8.1 sec

INFO - 2026-09-29T22:12:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9738 downloaded in 8.2 sec

INFO - 2026-09-29T22:12:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9737 downloaded in 8.2 sec

INFO - 2026-09-29T22:12:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:12:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9736 downloaded in 8.3 sec

INFO - 2026-09-29T22:12:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:12:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:12:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9735 downloaded in 8.1 sec

INFO - 2026-09-29T22:13:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9734 downloaded in 8.3 sec

INFO - 2026-09-29T22:13:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9733 downloaded in 12.8 sec

INFO - 2026-09-29T22:13:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9732 downloaded in 8.1 sec

INFO - 2026-09-29T22:13:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9731 downloaded in 8.4 sec

INFO - 2026-09-29T22:13:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9878 downloaded in 8.3 sec

INFO - 2026-09-29T22:13:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:13:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9730 downloaded in 8.4 sec

INFO - 2026-09-29T22:13:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:13:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:13:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9724 downloaded in 7.9 sec

INFO - 2026-09-29T22:14:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9723 downloaded in 8.2 sec

INFO - 2026-09-29T22:14:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9722 downloaded in 8.2 sec

INFO - 2026-09-29T22:14:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9877 downloaded in 8.1 sec

INFO - 2026-09-29T22:14:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9721 downloaded in 8.1 sec

INFO - 2026-09-29T22:14:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9720 downloaded in 8.3 sec

INFO - 2026-09-29T22:14:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:14:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9751 downloaded in 8.2 sec

INFO - 2026-09-29T22:14:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:14:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:14:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9719 downloaded in 13.2 sec

INFO - 2026-09-29T22:15:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9718 downloaded in 8.4 sec

INFO - 2026-09-29T22:15:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9717 downloaded in 8.2 sec

INFO - 2026-09-29T22:15:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9876 downloaded in 8.0 sec

INFO - 2026-09-29T22:15:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9727 downloaded in 8.0 sec

INFO - 2026-09-29T22:15:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9726 downloaded in 8.4 sec

INFO - 2026-09-29T22:15:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:15:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:15:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:15:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9725 downloaded in 8.3 sec

INFO - 2026-09-29T22:16:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9715 downloaded in 8.0 sec

INFO - 2026-09-29T22:16:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9713 downloaded in 8.1 sec

INFO - 2026-09-29T22:16:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9875 downloaded in 8.2 sec

INFO - 2026-09-29T22:16:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9712 downloaded in 8.0 sec

INFO - 2026-09-29T22:16:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9711 downloaded in 8.1 sec

INFO - 2026-09-29T22:16:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9710 downloaded in 12.2 sec

INFO - 2026-09-29T22:16:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:16:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:16:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:16:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9709 downloaded in 8.1 sec

INFO - 2026-09-29T22:17:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9708 downloaded in 8.0 sec

INFO - 2026-09-29T22:17:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9706 downloaded in 8.2 sec

INFO - 2026-09-29T22:17:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9705 downloaded in 8.2 sec

INFO - 2026-09-29T22:17:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9703 downloaded in 8.1 sec

INFO - 2026-09-29T22:17:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9702 downloaded in 8.1 sec

INFO - 2026-09-29T22:17:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9701 downloaded in 8.1 sec

INFO - 2026-09-29T22:17:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:17:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:17:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:17:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9700 downloaded in 8.3 sec

INFO - 2026-09-29T22:18:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9699 downloaded in 8.2 sec

INFO - 2026-09-29T22:18:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9698 downloaded in 8.4 sec

INFO - 2026-09-29T22:18:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9697 downloaded in 8.2 sec

INFO - 2026-09-29T22:18:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9696 downloaded in 11.9 sec

INFO - 2026-09-29T22:18:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9693 downloaded in 8.1 sec

INFO - 2026-09-29T22:18:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:18:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9692 downloaded in 8.2 sec

INFO - 2026-09-29T22:18:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:18:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:18:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9691 downloaded in 8.1 sec

INFO - 2026-09-29T22:19:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9690 downloaded in 8.3 sec

INFO - 2026-09-29T22:19:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9689 downloaded in 8.1 sec

INFO - 2026-09-29T22:19:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9688 downloaded in 8.1 sec

INFO - 2026-09-29T22:19:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9687 downloaded in 8.3 sec

INFO - 2026-09-29T22:19:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9686 downloaded in 8.2 sec

INFO - 2026-09-29T22:19:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9685 downloaded in 8.1 sec

INFO - 2026-09-29T22:19:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:19:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:19:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:19:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9684 downloaded in 8.1 sec

INFO - 2026-09-29T22:20:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9679 downloaded in 8.3 sec

INFO - 2026-09-29T22:20:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9678 downloaded in 11.9 sec

INFO - 2026-09-29T22:20:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9676 downloaded in 7.9 sec

INFO - 2026-09-29T22:20:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9675 downloaded in 8.2 sec

INFO - 2026-09-29T22:20:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9674 downloaded in 8.0 sec

INFO - 2026-09-29T22:20:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:20:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9714 downloaded in 8.2 sec

INFO - 2026-09-29T22:20:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:20:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:20:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9681 downloaded in 8.4 sec

INFO - 2026-09-29T22:21:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9672 downloaded in 8.4 sec

INFO - 2026-09-29T22:21:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9671 downloaded in 8.4 sec

INFO - 2026-09-29T22:21:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9874 downloaded in 8.1 sec

INFO - 2026-09-29T22:21:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9670 downloaded in 8.0 sec

INFO - 2026-09-29T22:21:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9669 downloaded in 8.3 sec

INFO - 2026-09-29T22:21:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:21:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9668 downloaded in 7.9 sec

INFO - 2026-09-29T22:21:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:21:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:21:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9667 downloaded in 11.4 sec

INFO - 2026-09-29T22:22:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9666 downloaded in 8.4 sec

INFO - 2026-09-29T22:22:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9665 downloaded in 8.4 sec

INFO - 2026-09-29T22:22:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9663 downloaded in 8.2 sec

INFO - 2026-09-29T22:22:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9662 downloaded in 8.1 sec

INFO - 2026-09-29T22:22:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9661 downloaded in 8.2 sec

INFO - 2026-09-29T22:22:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:22:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9660 downloaded in 7.9 sec

INFO - 2026-09-29T22:22:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:22:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:22:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9659 downloaded in 8.0 sec

INFO - 2026-09-29T22:23:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9873 downloaded in 8.1 sec

INFO - 2026-09-29T22:23:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9658 downloaded in 8.4 sec

INFO - 2026-09-29T22:23:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9656 downloaded in 8.0 sec

INFO - 2026-09-29T22:23:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9655 downloaded in 8.0 sec

INFO - 2026-09-29T22:23:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9889 downloaded in 12.5 sec

INFO - 2026-09-29T22:23:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:23:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9654 downloaded in 8.3 sec

INFO - 2026-09-29T22:23:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:23:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:23:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9653 downloaded in 8.0 sec

INFO - 2026-09-29T22:24:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9652 downloaded in 8.0 sec

INFO - 2026-09-29T22:24:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9650 downloaded in 8.2 sec

INFO - 2026-09-29T22:24:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9649 downloaded in 8.1 sec

INFO - 2026-09-29T22:24:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9648 downloaded in 8.1 sec

INFO - 2026-09-29T22:24:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9647 downloaded in 8.1 sec

INFO - 2026-09-29T22:24:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:24:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9645 downloaded in 8.1 sec

INFO - 2026-09-29T22:24:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:24:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:24:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9640 downloaded in 8.0 sec

INFO - 2026-09-29T22:25:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9639 downloaded in 8.2 sec

INFO - 2026-09-29T22:25:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9638 downloaded in 7.9 sec

INFO - 2026-09-29T22:25:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9888 downloaded in 11.6 sec

INFO - 2026-09-29T22:25:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9887 downloaded in 8.3 sec

INFO - 2026-09-29T22:25:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9633 downloaded in 8.4 sec

INFO - 2026-09-29T22:25:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:25:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9632 downloaded in 8.4 sec

INFO - 2026-09-29T22:25:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:25:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:25:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9631 downloaded in 8.2 sec

INFO - 2026-09-29T22:26:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9630 downloaded in 8.4 sec

INFO - 2026-09-29T22:26:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9629 downloaded in 7.9 sec

INFO - 2026-09-29T22:26:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9637 downloaded in 8.1 sec

INFO - 2026-09-29T22:26:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9636 downloaded in 8.1 sec

INFO - 2026-09-29T22:26:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9634 downloaded in 8.2 sec

INFO - 2026-09-29T22:26:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:26:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9627 downloaded in 8.1 sec

INFO - 2026-09-29T22:26:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:26:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:26:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9625 downloaded in 8.5 sec

INFO - 2026-09-29T22:27:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9624 downloaded in 11.8 sec

INFO - 2026-09-29T22:27:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9623 downloaded in 8.3 sec

INFO - 2026-09-29T22:27:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9622 downloaded in 8.3 sec

INFO - 2026-09-29T22:27:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9620 downloaded in 8.2 sec

INFO - 2026-09-29T22:27:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9619 downloaded in 8.2 sec

INFO - 2026-09-29T22:27:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:27:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:27:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:27:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9618 downloaded in 8.0 sec

INFO - 2026-09-29T22:28:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9617 downloaded in 8.4 sec

INFO - 2026-09-29T22:28:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9616 downloaded in 8.2 sec

INFO - 2026-09-29T22:28:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9615 downloaded in 8.1 sec

INFO - 2026-09-29T22:28:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9614 downloaded in 7.9 sec

INFO - 2026-09-29T22:28:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9613 downloaded in 8.5 sec

INFO - 2026-09-29T22:28:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9612 downloaded in 7.9 sec

INFO - 2026-09-29T22:28:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:28:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9611 downloaded in 8.1 sec

INFO - 2026-09-29T22:28:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:28:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:28:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9610 downloaded in 11.8 sec

INFO - 2026-09-29T22:29:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9608 downloaded in 8.2 sec

INFO - 2026-09-29T22:29:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9607 downloaded in 8.2 sec

INFO - 2026-09-29T22:29:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9606 downloaded in 8.0 sec

INFO - 2026-09-29T22:29:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9605 downloaded in 8.3 sec

INFO - 2026-09-29T22:29:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9604 downloaded in 8.0 sec

INFO - 2026-09-29T22:29:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:29:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:29:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:29:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9603 downloaded in 8.1 sec

INFO - 2026-09-29T22:30:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9602 downloaded in 8.1 sec

INFO - 2026-09-29T22:30:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9601 downloaded in 8.3 sec

INFO - 2026-09-29T22:30:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9600 downloaded in 8.0 sec

INFO - 2026-09-29T22:30:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9599 downloaded in 7.8 sec

INFO - 2026-09-29T22:30:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9597 downloaded in 11.4 sec

INFO - 2026-09-29T22:30:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9596 downloaded in 8.1 sec

INFO - 2026-09-29T22:30:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:30:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:30:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:30:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9595 downloaded in 8.1 sec

INFO - 2026-09-29T22:31:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9594 downloaded in 8.4 sec

INFO - 2026-09-29T22:31:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9593 downloaded in 8.3 sec

INFO - 2026-09-29T22:31:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9592 downloaded in 8.2 sec

INFO - 2026-09-29T22:31:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9588 downloaded in 8.2 sec

INFO - 2026-09-29T22:31:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9587 downloaded in 8.3 sec

INFO - 2026-09-29T22:31:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9635 downloaded in 8.3 sec

INFO - 2026-09-29T22:31:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:31:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:31:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:31:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9591 downloaded in 8.2 sec

INFO - 2026-09-29T22:32:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9590 downloaded in 8.0 sec

INFO - 2026-09-29T22:32:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9589 downloaded in 8.0 sec

INFO - 2026-09-29T22:32:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9584 downloaded in 11.7 sec

INFO - 2026-09-29T22:32:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9583 downloaded in 8.0 sec

INFO - 2026-09-29T22:32:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9582 downloaded in 8.3 sec

INFO - 2026-09-29T22:32:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9581 downloaded in 8.3 sec

INFO - 2026-09-29T22:32:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:32:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:32:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:32:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9580 downloaded in 8.4 sec

INFO - 2026-09-29T22:33:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9579 downloaded in 8.3 sec

INFO - 2026-09-29T22:33:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9578 downloaded in 8.0 sec

INFO - 2026-09-29T22:33:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9577 downloaded in 8.2 sec

INFO - 2026-09-29T22:33:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9576 downloaded in 8.2 sec

INFO - 2026-09-29T22:33:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9575 downloaded in 8.0 sec

INFO - 2026-09-29T22:33:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9574 downloaded in 8.3 sec

INFO - 2026-09-29T22:33:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:33:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:33:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:33:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9573 downloaded in 8.2 sec

INFO - 2026-09-29T22:34:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9572 downloaded in 11.9 sec

INFO - 2026-09-29T22:34:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9571 downloaded in 8.0 sec

INFO - 2026-09-29T22:34:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9570 downloaded in 8.1 sec

INFO - 2026-09-29T22:34:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9569 downloaded in 8.2 sec

INFO - 2026-09-29T22:34:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9568 downloaded in 8.2 sec

INFO - 2026-09-29T22:34:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:34:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9567 downloaded in 8.1 sec

INFO - 2026-09-29T22:34:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:34:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:34:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9566 downloaded in 8.2 sec

INFO - 2026-09-29T22:35:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9565 downloaded in 8.2 sec

INFO - 2026-09-29T22:35:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9563 downloaded in 8.2 sec

INFO - 2026-09-29T22:35:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9560 downloaded in 8.1 sec

INFO - 2026-09-29T22:35:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9559 downloaded in 8.2 sec

INFO - 2026-09-29T22:35:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9558 downloaded in 8.2 sec

INFO - 2026-09-29T22:35:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:35:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9557 downloaded in 11.5 sec

INFO - 2026-09-29T22:35:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:35:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:35:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9556 downloaded in 8.2 sec

INFO - 2026-09-29T22:36:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9555 downloaded in 8.4 sec

INFO - 2026-09-29T22:36:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9554 downloaded in 8.2 sec

INFO - 2026-09-29T22:36:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9553 downloaded in 8.2 sec

INFO - 2026-09-29T22:36:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9552 downloaded in 8.5 sec

INFO - 2026-09-29T22:36:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9551 downloaded in 8.0 sec

INFO - 2026-09-29T22:36:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:36:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9550 downloaded in 8.1 sec

INFO - 2026-09-29T22:36:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:36:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:36:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9886 downloaded in 8.4 sec

INFO - 2026-09-29T22:37:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9548 downloaded in 8.2 sec

INFO - 2026-09-29T22:37:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9547 downloaded in 8.7 sec

INFO - 2026-09-29T22:37:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9546 downloaded in 8.4 sec

INFO - 2026-09-29T22:37:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9544 downloaded in 12.1 sec

INFO - 2026-09-29T22:37:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9885 downloaded in 8.2 sec

INFO - 2026-09-29T22:37:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:37:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9871 downloaded in 8.2 sec

INFO - 2026-09-29T22:37:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:37:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:37:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9543 downloaded in 8.2 sec

INFO - 2026-09-29T22:38:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9541 downloaded in 8.5 sec

INFO - 2026-09-29T22:38:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9540 downloaded in 8.1 sec

INFO - 2026-09-29T22:38:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9539 downloaded in 8.1 sec

INFO - 2026-09-29T22:38:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9538 downloaded in 8.5 sec

INFO - 2026-09-29T22:38:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9537 downloaded in 8.3 sec

INFO - 2026-09-29T22:38:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:38:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9535 downloaded in 8.2 sec

INFO - 2026-09-29T22:38:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:38:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:38:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9534 downloaded in 8.3 sec

INFO - 2026-09-29T22:39:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9533 downloaded in 8.6 sec

INFO - 2026-09-29T22:39:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9532 downloaded in 8.1 sec

INFO - 2026-09-29T22:39:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9531 downloaded in 11.9 sec

INFO - 2026-09-29T22:39:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9529 downloaded in 8.4 sec

INFO - 2026-09-29T22:39:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9528 downloaded in 8.4 sec

INFO - 2026-09-29T22:39:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:39:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:39:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:39:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9530 downloaded in 8.1 sec

INFO - 2026-09-29T22:40:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9542 downloaded in 8.2 sec

INFO - 2026-09-29T22:40:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9564 downloaded in 8.6 sec

INFO - 2026-09-29T22:40:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9805 downloaded in 8.2 sec

INFO - 2026-09-29T22:40:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9815 downloaded in 8.2 sec

INFO - 2026-09-29T22:40:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9817 downloaded in 8.3 sec

INFO - 2026-09-29T22:40:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9818 downloaded in 8.4 sec

INFO - 2026-09-29T22:40:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:40:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:40:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:40:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9803 downloaded in 8.0 sec

INFO - 2026-09-29T22:41:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9807 downloaded in 11.2 sec

INFO - 2026-09-29T22:41:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9802 downloaded in 8.4 sec

INFO - 2026-09-29T22:41:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9801 downloaded in 8.1 sec

INFO - 2026-09-29T22:41:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9799 downloaded in 8.3 sec

INFO - 2026-09-29T22:41:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9798 downloaded in 8.1 sec

INFO - 2026-09-29T22:41:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:41:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9797 downloaded in 8.5 sec

INFO - 2026-09-29T22:41:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:41:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:41:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9796 downloaded in 8.2 sec

INFO - 2026-09-29T22:42:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9795 downloaded in 8.0 sec

INFO - 2026-09-29T22:42:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9794 downloaded in 8.3 sec

INFO - 2026-09-29T22:42:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9808 downloaded in 8.3 sec

INFO - 2026-09-29T22:42:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9793 downloaded in 8.0 sec

INFO - 2026-09-29T22:42:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9809 downloaded in 8.1 sec

INFO - 2026-09-29T22:42:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:42:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9810 downloaded in 11.7 sec

INFO - 2026-09-29T22:42:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:42:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:42:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9792 downloaded in 8.2 sec

INFO - 2026-09-29T22:43:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9791 downloaded in 8.3 sec

INFO - 2026-09-29T22:43:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9811 downloaded in 8.2 sec

INFO - 2026-09-29T22:43:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9813 downloaded in 8.5 sec

INFO - 2026-09-29T22:43:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9790 downloaded in 8.2 sec

INFO - 2026-09-29T22:43:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9890 downloaded in 8.1 sec

INFO - 2026-09-29T22:43:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:43:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9816 downloaded in 8.5 sec

INFO - 2026-09-29T22:43:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:43:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:43:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9680 downloaded in 8.6 sec

INFO - 2026-09-29T22:44:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9804 downloaded in 8.2 sec

INFO - 2026-09-29T22:44:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10083 downloaded in 8.3 sec

INFO - 2026-09-29T22:44:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10085 downloaded in 8.6 sec

INFO - 2026-09-29T22:44:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10084 downloaded in 11.6 sec

INFO - 2026-09-29T22:44:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9079 downloaded in 8.2 sec

INFO - 2026-09-29T22:44:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:44:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:44:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:44:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9078 downloaded in 8.3 sec

INFO - 2026-09-29T22:45:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9077 downloaded in 8.5 sec

INFO - 2026-09-29T22:45:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9080 downloaded in 8.3 sec

INFO - 2026-09-29T22:45:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10056 downloaded in 8.2 sec

INFO - 2026-09-29T22:45:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10061 downloaded in 8.3 sec

INFO - 2026-09-29T22:45:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10068 downloaded in 8.3 sec

INFO - 2026-09-29T22:45:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10064 downloaded in 8.1 sec

INFO - 2026-09-29T22:45:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:45:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:45:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10008 downloaded in 8.4 sec

INFO - 2026-09-29T22:45:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:45:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10063 downloaded in 8.7 sec

INFO - 2026-09-29T22:46:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10007 downloaded in 8.3 sec

INFO - 2026-09-29T22:46:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10004 downloaded in 11.9 sec

INFO - 2026-09-29T22:46:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10070 downloaded in 8.6 sec

INFO - 2026-09-29T22:46:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10006 downloaded in 8.5 sec

INFO - 2026-09-29T22:46:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:46:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10005 downloaded in 8.2 sec

INFO - 2026-09-29T22:46:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:46:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:46:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10062 downloaded in 8.2 sec

INFO - 2026-09-29T22:47:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10060 downloaded in 8.6 sec

INFO - 2026-09-29T22:47:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10071 downloaded in 8.3 sec

INFO - 2026-09-29T22:47:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10059 downloaded in 8.2 sec

INFO - 2026-09-29T22:47:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10066 downloaded in 8.6 sec

INFO - 2026-09-29T22:47:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10058 downloaded in 8.4 sec

INFO - 2026-09-29T22:47:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:47:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10148 downloaded in 8.3 sec

INFO - 2026-09-29T22:47:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:47:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:47:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10073 downloaded in 8.5 sec

INFO - 2026-09-29T22:48:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10057 downloaded in 12.5 sec

INFO - 2026-09-29T22:48:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10204 downloaded in 8.2 sec

INFO - 2026-09-29T22:48:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10203 downloaded in 8.4 sec

INFO - 2026-09-29T22:48:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9562 downloaded in 8.6 sec

INFO - 2026-09-29T22:48:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10208 downloaded in 8.5 sec

INFO - 2026-09-29T22:48:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:48:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10116 downloaded in 8.2 sec

INFO - 2026-09-29T22:48:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:48:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:48:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10105 downloaded in 8.4 sec

INFO - 2026-09-29T22:49:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10112 downloaded in 8.5 sec

INFO - 2026-09-29T22:49:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10120 downloaded in 8.5 sec

INFO - 2026-09-29T22:49:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10119 downloaded in 8.4 sec

INFO - 2026-09-29T22:49:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10110 downloaded in 8.3 sec

INFO - 2026-09-29T22:49:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10109 downloaded in 8.2 sec

INFO - 2026-09-29T22:49:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:49:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:49:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:49:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10108 downloaded in 11.7 sec

INFO - 2026-09-29T22:50:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10195 downloaded in 8.6 sec

INFO - 2026-09-29T22:50:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10157 downloaded in 9.1 sec

INFO - 2026-09-29T22:50:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10156 downloaded in 8.5 sec

INFO - 2026-09-29T22:50:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10163 downloaded in 8.6 sec

INFO - 2026-09-29T22:50:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10164 downloaded in 8.8 sec

INFO - 2026-09-29T22:50:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:50:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10159 downloaded in 8.6 sec

INFO - 2026-09-29T22:50:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:50:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:50:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10160 downloaded in 8.6 sec

INFO - 2026-09-29T22:51:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10197 downloaded in 8.4 sec

INFO - 2026-09-29T22:51:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10150 downloaded in 9.0 sec

INFO - 2026-09-29T22:51:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10153 downloaded in 8.8 sec

INFO - 2026-09-29T22:51:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10152 downloaded in 8.6 sec

INFO - 2026-09-29T22:51:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10154 downloaded in 12.3 sec

INFO - 2026-09-29T22:51:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:51:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:51:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:51:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10165 downloaded in 8.4 sec

INFO - 2026-09-29T22:52:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10196 downloaded in 8.6 sec

INFO - 2026-09-29T22:52:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10151 downloaded in 8.7 sec

INFO - 2026-09-29T22:52:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13065 downloaded in 8.8 sec

INFO - 2026-09-29T22:52:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9284 downloaded in 8.6 sec

INFO - 2026-09-29T22:52:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10202 downloaded in 8.2 sec

INFO - 2026-09-29T22:52:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:52:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9196 downloaded in 8.6 sec

INFO - 2026-09-29T22:52:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:52:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:52:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10200 downloaded in 8.6 sec

INFO - 2026-09-29T22:53:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10199 downloaded in 8.4 sec

INFO - 2026-09-29T22:53:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9193 downloaded in 8.6 sec

INFO - 2026-09-29T22:53:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9190 downloaded in 8.7 sec

INFO - 2026-09-29T22:53:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10198 downloaded in 12.3 sec

INFO - 2026-09-29T22:53:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9191 downloaded in 8.7 sec

INFO - 2026-09-29T22:53:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:53:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9194 downloaded in 8.9 sec

INFO - 2026-09-29T22:53:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:53:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:53:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10201 downloaded in 8.2 sec

INFO - 2026-09-29T22:54:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9195 downloaded in 8.8 sec

INFO - 2026-09-29T22:54:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9192 downloaded in 8.3 sec

INFO - 2026-09-29T22:54:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8801 downloaded in 8.5 sec

INFO - 2026-09-29T22:54:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8800 downloaded in 8.7 sec

INFO - 2026-09-29T22:54:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8803 downloaded in 8.3 sec

INFO - 2026-09-29T22:54:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:54:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:54:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:54:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8802 downloaded in 8.4 sec

INFO - 2026-09-29T22:55:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8799 downloaded in 8.5 sec

INFO - 2026-09-29T22:55:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8588 downloaded in 8.2 sec

INFO - 2026-09-29T22:55:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8191 downloaded in 11.9 sec

INFO - 2026-09-29T22:55:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8344 downloaded in 8.7 sec

INFO - 2026-09-29T22:55:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8040 downloaded in 8.5 sec

INFO - 2026-09-29T22:55:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:55:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8038 downloaded in 8.9 sec

INFO - 2026-09-29T22:55:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:55:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:55:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8111 downloaded in 9.1 sec

INFO - 2026-09-29T22:56:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8108 downloaded in 8.6 sec

INFO - 2026-09-29T22:56:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8107 downloaded in 8.5 sec

INFO - 2026-09-29T22:56:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8068 downloaded in 8.8 sec

INFO - 2026-09-29T22:56:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8069 downloaded in 8.8 sec

INFO - 2026-09-29T22:56:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8306 downloaded in 9.0 sec

INFO - 2026-09-29T22:56:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:56:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8063 downloaded in 8.5 sec

INFO - 2026-09-29T22:56:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:56:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:56:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8269 downloaded in 8.6 sec

INFO - 2026-09-29T22:57:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8305 downloaded in 14.0 sec

INFO - 2026-09-29T22:57:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8304 downloaded in 8.5 sec

INFO - 2026-09-29T22:57:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8034 downloaded in 9.0 sec

INFO - 2026-09-29T22:57:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8036 downloaded in 8.8 sec

INFO - 2026-09-29T22:57:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:57:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8395 downloaded in 8.7 sec

INFO - 2026-09-29T22:57:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:57:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:57:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8511 downloaded in 8.7 sec

INFO - 2026-09-29T22:58:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8510 downloaded in 8.6 sec

INFO - 2026-09-29T22:58:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8509 downloaded in 8.9 sec

INFO - 2026-09-29T22:58:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8508 downloaded in 8.9 sec

INFO - 2026-09-29T22:58:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8396 downloaded in 8.7 sec

INFO - 2026-09-29T22:58:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8397 downloaded in 9.0 sec

INFO - 2026-09-29T22:58:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:58:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:58:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:58:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8502 downloaded in 8.7 sec

INFO - 2026-09-29T22:59:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8398 downloaded in 13.8 sec

INFO - 2026-09-29T22:59:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8033 downloaded in 8.8 sec

INFO - 2026-09-29T22:59:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8293 downloaded in 8.4 sec

INFO - 2026-09-29T22:59:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8294 downloaded in 8.5 sec

INFO - 2026-09-29T22:59:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8295 downloaded in 8.9 sec

INFO - 2026-09-29T22:59:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T22:59:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8297 downloaded in 8.4 sec

INFO - 2026-09-29T22:59:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T22:59:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T22:59:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8302 downloaded in 8.4 sec

INFO - 2026-09-29T23:00:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8290 downloaded in 8.8 sec

INFO - 2026-09-29T23:00:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8289 downloaded in 8.9 sec

INFO - 2026-09-29T23:00:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8288 downloaded in 8.6 sec

INFO - 2026-09-29T23:00:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8287 downloaded in 8.4 sec

INFO - 2026-09-29T23:00:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:00:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8286 downloaded in 8.8 sec

INFO - 2026-09-29T23:00:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:00:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:00:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8285 downloaded in 14.0 sec

INFO - 2026-09-29T23:01:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8282 downloaded in 8.7 sec

INFO - 2026-09-29T23:01:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8281 downloaded in 8.4 sec

INFO - 2026-09-29T23:01:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8280 downloaded in 8.5 sec

INFO - 2026-09-29T23:01:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8279 downloaded in 8.9 sec

INFO - 2026-09-29T23:01:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8298 downloaded in 8.5 sec

INFO - 2026-09-29T23:01:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:01:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8299 downloaded in 8.8 sec

INFO - 2026-09-29T23:01:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:01:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:01:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8300 downloaded in 8.6 sec

INFO - 2026-09-29T23:02:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8308 downloaded in 8.5 sec

INFO - 2026-09-29T23:02:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8067 downloaded in 8.8 sec

INFO - 2026-09-29T23:02:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8065 downloaded in 8.5 sec

INFO - 2026-09-29T23:02:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8070 downloaded in 8.8 sec

INFO - 2026-09-29T23:02:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:02:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8062 downloaded in 13.0 sec

INFO - 2026-09-29T23:02:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:02:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:02:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8278 downloaded in 8.8 sec

INFO - 2026-09-29T23:03:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8277 downloaded in 8.9 sec

INFO - 2026-09-29T23:03:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8276 downloaded in 8.7 sec

INFO - 2026-09-29T23:03:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8275 downloaded in 9.0 sec

INFO - 2026-09-29T23:03:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8274 downloaded in 8.6 sec

INFO - 2026-09-29T23:03:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8109 downloaded in 8.7 sec

INFO - 2026-09-29T23:03:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:03:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:03:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8110 downloaded in 8.8 sec

INFO - 2026-09-29T23:03:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:03:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8039 downloaded in 8.4 sec

INFO - 2026-09-29T23:04:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8273 downloaded in 8.5 sec

INFO - 2026-09-29T23:04:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8272 downloaded in 8.7 sec

INFO - 2026-09-29T23:04:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8271 downloaded in 8.8 sec

INFO - 2026-09-29T23:04:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8284 downloaded in 13.3 sec

INFO - 2026-09-29T23:04:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:04:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8257 downloaded in 8.6 sec

INFO - 2026-09-29T23:04:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:04:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:04:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8256 downloaded in 8.7 sec

INFO - 2026-09-29T23:05:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8255 downloaded in 8.6 sec

INFO - 2026-09-29T23:05:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8270 downloaded in 8.8 sec

INFO - 2026-09-29T23:05:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8402 downloaded in 8.9 sec

INFO - 2026-09-29T23:05:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8401 downloaded in 8.4 sec

INFO - 2026-09-29T23:05:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8334 downloaded in 8.7 sec

INFO - 2026-09-29T23:05:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:05:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:05:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:05:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8335 downloaded in 8.7 sec

INFO - 2026-09-29T23:06:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8336 downloaded in 8.9 sec

INFO - 2026-09-29T23:06:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8337 downloaded in 8.8 sec

INFO - 2026-09-29T23:06:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8338 downloaded in 8.8 sec

INFO - 2026-09-29T23:06:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8400 downloaded in 13.0 sec

INFO - 2026-09-29T23:06:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8399 downloaded in 9.0 sec

INFO - 2026-09-29T23:06:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:06:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8394 downloaded in 8.5 sec

INFO - 2026-09-29T23:06:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:06:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:06:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8518 downloaded in 8.6 sec

INFO - 2026-09-29T23:07:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8517 downloaded in 8.7 sec

INFO - 2026-09-29T23:07:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8514 downloaded in 8.5 sec

INFO - 2026-09-29T23:07:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8061 downloaded in 8.6 sec

INFO - 2026-09-29T23:07:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8303 downloaded in 8.7 sec

INFO - 2026-09-29T23:07:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8064 downloaded in 8.7 sec

INFO - 2026-09-29T23:07:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:07:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:07:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:07:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8031 downloaded in 8.6 sec

INFO - 2026-09-29T23:08:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8018 downloaded in 8.5 sec

INFO - 2026-09-29T23:08:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8041 downloaded in 8.9 sec

INFO - 2026-09-29T23:08:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8014 downloaded in 13.1 sec

INFO - 2026-09-29T23:08:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8015 downloaded in 8.9 sec

INFO - 2026-09-29T23:08:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8044 downloaded in 8.8 sec

INFO - 2026-09-29T23:08:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:08:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8016 downloaded in 8.5 sec

INFO - 2026-09-29T23:08:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:08:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:08:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8017 downloaded in 9.0 sec

INFO - 2026-09-29T23:09:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8019 downloaded in 8.8 sec

INFO - 2026-09-29T23:09:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8020 downloaded in 9.0 sec

INFO - 2026-09-29T23:09:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8021 downloaded in 8.7 sec

INFO - 2026-09-29T23:09:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8022 downloaded in 8.7 sec

INFO - 2026-09-29T23:09:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8024 downloaded in 8.4 sec

INFO - 2026-09-29T23:09:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:09:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:09:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:09:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8025 downloaded in 8.4 sec

INFO - 2026-09-29T23:10:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8026 downloaded in 8.8 sec

INFO - 2026-09-29T23:10:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8060 downloaded in 8.5 sec

INFO - 2026-09-29T23:10:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8042 downloaded in 13.9 sec

INFO - 2026-09-29T23:10:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8043 downloaded in 8.7 sec

INFO - 2026-09-29T23:10:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8028 downloaded in 8.4 sec

INFO - 2026-09-29T23:10:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:10:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8029 downloaded in 8.7 sec

INFO - 2026-09-29T23:10:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:10:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:10:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8345 downloaded in 8.5 sec

INFO - 2026-09-29T23:11:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8346 downloaded in 8.8 sec

INFO - 2026-09-29T23:11:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8032 downloaded in 8.6 sec

INFO - 2026-09-29T23:11:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8404 downloaded in 8.8 sec

INFO - 2026-09-29T23:11:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8403 downloaded in 8.5 sec

INFO - 2026-09-29T23:11:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8307 downloaded in 8.6 sec

INFO - 2026-09-29T23:11:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:11:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:11:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:11:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8030 downloaded in 8.5 sec

INFO - 2026-09-29T23:12:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8035 downloaded in 13.1 sec

INFO - 2026-09-29T23:12:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8283 downloaded in 8.7 sec

INFO - 2026-09-29T23:12:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8291 downloaded in 8.6 sec

INFO - 2026-09-29T23:12:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8292 downloaded in 8.7 sec

INFO - 2026-09-29T23:12:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8516 downloaded in 8.9 sec

INFO - 2026-09-29T23:12:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:12:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8027 downloaded in 8.7 sec

INFO - 2026-09-29T23:12:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:12:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:12:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8037 downloaded in 8.5 sec

INFO - 2026-09-29T23:13:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8515 downloaded in 8.4 sec

INFO - 2026-09-29T23:13:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8301 downloaded in 8.8 sec

INFO - 2026-09-29T23:13:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8023 downloaded in 8.5 sec

INFO - 2026-09-29T23:13:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8449 downloaded in 8.4 sec

INFO - 2026-09-29T23:13:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:13:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8448 downloaded in 8.8 sec

INFO - 2026-09-29T23:13:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:13:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:13:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8447 downloaded in 13.3 sec

INFO - 2026-09-29T23:14:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13597 downloaded in 8.6 sec

INFO - 2026-09-29T23:14:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14190 downloaded in 8.5 sec

INFO - 2026-09-29T23:14:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7842 downloaded in 8.1 sec

INFO - 2026-09-29T23:14:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14189 downloaded in 8.5 sec

INFO - 2026-09-29T23:14:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14191 downloaded in 8.1 sec

INFO - 2026-09-29T23:14:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:14:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10033 downloaded in 8.4 sec

INFO - 2026-09-29T23:14:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:14:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:14:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10027 downloaded in 8.7 sec

INFO - 2026-09-29T23:15:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10030 downloaded in 8.3 sec

INFO - 2026-09-29T23:15:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10031 downloaded in 8.3 sec

INFO - 2026-09-29T23:15:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10029 downloaded in 8.1 sec

INFO - 2026-09-29T23:15:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10032 downloaded in 8.5 sec

INFO - 2026-09-29T23:15:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10026 downloaded in 13.0 sec

INFO - 2026-09-29T23:15:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:15:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:15:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:15:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10028 downloaded in 8.3 sec

INFO - 2026-09-29T23:16:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8664 downloaded in 8.5 sec

INFO - 2026-09-29T23:16:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8663 downloaded in 8.5 sec

INFO - 2026-09-29T23:16:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8671 downloaded in 8.6 sec

INFO - 2026-09-29T23:16:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8670 downloaded in 8.4 sec

INFO - 2026-09-29T23:16:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8669 downloaded in 8.3 sec

INFO - 2026-09-29T23:16:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8668 downloaded in 8.7 sec

INFO - 2026-09-29T23:16:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:16:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:16:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:16:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8667 downloaded in 9.5 sec

INFO - 2026-09-29T23:17:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8666 downloaded in 8.0 sec

INFO - 2026-09-29T23:17:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8665 downloaded in 8.5 sec

INFO - 2026-09-29T23:17:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8662 downloaded in 8.6 sec

INFO - 2026-09-29T23:17:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8661 downloaded in 13.3 sec

INFO - 2026-09-29T23:17:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8659 downloaded in 8.5 sec

INFO - 2026-09-29T23:17:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:17:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8660 downloaded in 8.7 sec

INFO - 2026-09-29T23:17:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:17:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:17:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8114 downloaded in 8.7 sec

INFO - 2026-09-29T23:18:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8349 downloaded in 9.3 sec

INFO - 2026-09-29T23:18:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8589 downloaded in 8.4 sec

INFO - 2026-09-29T23:18:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8339 downloaded in 8.4 sec

INFO - 2026-09-29T23:18:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8333 downloaded in 8.6 sec

INFO - 2026-09-29T23:18:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8332 downloaded in 8.4 sec

INFO - 2026-09-29T23:18:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:18:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:18:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:18:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8331 downloaded in 8.3 sec

INFO - 2026-09-29T23:19:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8330 downloaded in 8.4 sec

INFO - 2026-09-29T23:19:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8329 downloaded in 8.3 sec

INFO - 2026-09-29T23:19:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8405 downloaded in 13.1 sec

INFO - 2026-09-29T23:19:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8406 downloaded in 8.4 sec

INFO - 2026-09-29T23:19:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8340 downloaded in 8.2 sec

INFO - 2026-09-29T23:19:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:19:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8343 downloaded in 8.7 sec

INFO - 2026-09-29T23:19:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:19:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:19:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8342 downloaded in 8.3 sec

INFO - 2026-09-29T23:20:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8328 downloaded in 8.3 sec

INFO - 2026-09-29T23:20:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8327 downloaded in 8.3 sec

INFO - 2026-09-29T23:20:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8326 downloaded in 8.3 sec

INFO - 2026-09-29T23:20:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8325 downloaded in 8.2 sec

INFO - 2026-09-29T23:20:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8324 downloaded in 8.4 sec

INFO - 2026-09-29T23:20:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:20:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8323 downloaded in 8.3 sec

INFO - 2026-09-29T23:20:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:20:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:20:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8321 downloaded in 8.6 sec

INFO - 2026-09-29T23:21:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8320 downloaded in 13.5 sec

INFO - 2026-09-29T23:21:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8318 downloaded in 8.3 sec

INFO - 2026-09-29T23:21:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8316 downloaded in 8.2 sec

INFO - 2026-09-29T23:21:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8315 downloaded in 8.2 sec

INFO - 2026-09-29T23:21:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8314 downloaded in 8.3 sec

INFO - 2026-09-29T23:21:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:21:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:21:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:21:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8313 downloaded in 8.3 sec

INFO - 2026-09-29T23:22:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8341 downloaded in 8.3 sec

INFO - 2026-09-29T23:22:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8312 downloaded in 8.3 sec

INFO - 2026-09-29T23:22:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8311 downloaded in 8.4 sec

INFO - 2026-09-29T23:22:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8409 downloaded in 8.5 sec

INFO - 2026-09-29T23:22:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8309 downloaded in 8.6 sec

INFO - 2026-09-29T23:22:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:22:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8408 downloaded in 8.2 sec

INFO - 2026-09-29T23:22:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:22:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:22:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8407 downloaded in 12.9 sec

INFO - 2026-09-29T23:23:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8322 downloaded in 8.3 sec

INFO - 2026-09-29T23:23:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8319 downloaded in 8.6 sec

INFO - 2026-09-29T23:23:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8317 downloaded in 8.4 sec

INFO - 2026-09-29T23:23:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8310 downloaded in 8.6 sec

INFO - 2026-09-29T23:23:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13663 downloaded in 8.6 sec

INFO - 2026-09-29T23:23:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:23:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9437 downloaded in 8.3 sec

INFO - 2026-09-29T23:23:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:23:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:23:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9511 downloaded in 8.5 sec

INFO - 2026-09-29T23:24:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9500 downloaded in 8.3 sec

INFO - 2026-09-29T23:24:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9499 downloaded in 8.1 sec

INFO - 2026-09-29T23:24:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9521 downloaded in 8.4 sec

INFO - 2026-09-29T23:24:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9362 downloaded in 8.7 sec

INFO - 2026-09-29T23:24:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9365 downloaded in 12.7 sec

INFO - 2026-09-29T23:24:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:24:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:24:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:24:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9378 downloaded in 8.3 sec

INFO - 2026-09-29T23:25:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9389 downloaded in 8.5 sec

INFO - 2026-09-29T23:25:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9402 downloaded in 8.4 sec

INFO - 2026-09-29T23:25:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9404 downloaded in 8.7 sec

INFO - 2026-09-29T23:25:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9412 downloaded in 8.4 sec

INFO - 2026-09-29T23:25:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9425 downloaded in 8.5 sec

INFO - 2026-09-29T23:25:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:25:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9448 downloaded in 8.0 sec

INFO - 2026-09-29T23:25:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:25:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:25:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9451 downloaded in 8.5 sec

INFO - 2026-09-29T23:26:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9460 downloaded in 8.8 sec

INFO - 2026-09-29T23:26:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9473 downloaded in 8.4 sec

INFO - 2026-09-29T23:26:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9487 downloaded in 8.8 sec

INFO - 2026-09-29T23:26:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9495 downloaded in 13.3 sec

INFO - 2026-09-29T23:26:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9463 downloaded in 8.2 sec

INFO - 2026-09-29T23:26:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:26:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:26:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:26:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9522 downloaded in 8.3 sec

INFO - 2026-09-29T23:27:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9406 downloaded in 8.4 sec

INFO - 2026-09-29T23:27:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9869 downloaded in 8.5 sec

INFO - 2026-09-29T23:27:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9868 downloaded in 8.3 sec

INFO - 2026-09-29T23:27:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9867 downloaded in 8.2 sec

INFO - 2026-09-29T23:27:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9866 downloaded in 8.2 sec

INFO - 2026-09-29T23:27:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9865 downloaded in 8.3 sec

INFO - 2026-09-29T23:27:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:27:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9864 downloaded in 8.1 sec

INFO - 2026-09-29T23:27:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:27:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:27:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9863 downloaded in 8.4 sec

INFO - 2026-09-29T23:28:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9862 downloaded in 8.4 sec

INFO - 2026-09-29T23:28:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9861 downloaded in 12.8 sec

INFO - 2026-09-29T23:28:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9860 downloaded in 8.2 sec

INFO - 2026-09-29T23:28:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9527 downloaded in 8.2 sec

INFO - 2026-09-29T23:28:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:28:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9526 downloaded in 8.5 sec

INFO - 2026-09-29T23:28:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:28:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:28:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9525 downloaded in 8.5 sec

INFO - 2026-09-29T23:29:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9524 downloaded in 8.3 sec

INFO - 2026-09-29T23:29:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9523 downloaded in 8.6 sec

INFO - 2026-09-29T23:29:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9520 downloaded in 8.4 sec

INFO - 2026-09-29T23:29:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9519 downloaded in 8.2 sec

INFO - 2026-09-29T23:29:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9518 downloaded in 8.5 sec

INFO - 2026-09-29T23:29:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:29:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9517 downloaded in 8.5 sec

INFO - 2026-09-29T23:29:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:29:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:29:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9516 downloaded in 8.2 sec

INFO - 2026-09-29T23:30:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9515 downloaded in 12.9 sec

INFO - 2026-09-29T23:30:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9514 downloaded in 8.7 sec

INFO - 2026-09-29T23:30:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9513 downloaded in 8.4 sec

INFO - 2026-09-29T23:30:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9512 downloaded in 8.4 sec

INFO - 2026-09-29T23:30:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9510 downloaded in 8.4 sec

INFO - 2026-09-29T23:30:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:30:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:30:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:30:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9509 downloaded in 8.4 sec

INFO - 2026-09-29T23:31:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9508 downloaded in 8.5 sec

INFO - 2026-09-29T23:31:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9507 downloaded in 8.3 sec

INFO - 2026-09-29T23:31:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9506 downloaded in 8.4 sec

INFO - 2026-09-29T23:31:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9504 downloaded in 8.3 sec

INFO - 2026-09-29T23:31:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9503 downloaded in 8.2 sec

INFO - 2026-09-29T23:31:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:31:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9502 downloaded in 8.2 sec

INFO - 2026-09-29T23:31:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:31:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:31:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9501 downloaded in 13.2 sec

INFO - 2026-09-29T23:32:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9496 downloaded in 8.6 sec

INFO - 2026-09-29T23:32:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9498 downloaded in 8.3 sec

INFO - 2026-09-29T23:32:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9497 downloaded in 8.3 sec

INFO - 2026-09-29T23:32:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9494 downloaded in 8.4 sec

INFO - 2026-09-29T23:32:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9493 downloaded in 8.3 sec

INFO - 2026-09-29T23:32:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:32:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9492 downloaded in 8.8 sec

INFO - 2026-09-29T23:32:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:32:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:32:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9491 downloaded in 8.2 sec

INFO - 2026-09-29T23:33:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9490 downloaded in 8.2 sec

INFO - 2026-09-29T23:33:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9489 downloaded in 8.3 sec

INFO - 2026-09-29T23:33:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9488 downloaded in 8.2 sec

INFO - 2026-09-29T23:33:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9486 downloaded in 8.6 sec

INFO - 2026-09-29T23:33:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9485 downloaded in 12.7 sec

INFO - 2026-09-29T23:33:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:33:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:33:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:33:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9484 downloaded in 8.4 sec

INFO - 2026-09-29T23:34:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9483 downloaded in 8.2 sec

INFO - 2026-09-29T23:34:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9482 downloaded in 8.5 sec

INFO - 2026-09-29T23:34:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9481 downloaded in 8.4 sec

INFO - 2026-09-29T23:34:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9479 downloaded in 8.5 sec

INFO - 2026-09-29T23:34:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9478 downloaded in 8.4 sec

INFO - 2026-09-29T23:34:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9477 downloaded in 8.3 sec

INFO - 2026-09-29T23:34:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:34:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:34:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:34:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9476 downloaded in 8.2 sec

INFO - 2026-09-29T23:35:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9475 downloaded in 8.5 sec

INFO - 2026-09-29T23:35:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9474 downloaded in 8.4 sec

INFO - 2026-09-29T23:35:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9472 downloaded in 8.6 sec

INFO - 2026-09-29T23:35:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9471 downloaded in 8.2 sec

INFO - 2026-09-29T23:35:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9470 downloaded in 12.4 sec

INFO - 2026-09-29T23:35:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:35:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9469 downloaded in 8.6 sec

INFO - 2026-09-29T23:35:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:35:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:35:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9468 downloaded in 9.0 sec

INFO - 2026-09-29T23:36:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9467 downloaded in 8.3 sec

INFO - 2026-09-29T23:36:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9466 downloaded in 8.3 sec

INFO - 2026-09-29T23:36:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9465 downloaded in 8.6 sec

INFO - 2026-09-29T23:36:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9464 downloaded in 8.2 sec

INFO - 2026-09-29T23:36:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9462 downloaded in 8.3 sec

INFO - 2026-09-29T23:36:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:36:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9461 downloaded in 8.6 sec

INFO - 2026-09-29T23:36:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:36:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:36:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9459 downloaded in 8.3 sec

INFO - 2026-09-29T23:37:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9458 downloaded in 8.1 sec

INFO - 2026-09-29T23:37:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9457 downloaded in 12.2 sec

INFO - 2026-09-29T23:37:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9456 downloaded in 8.5 sec

INFO - 2026-09-29T23:37:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9450 downloaded in 8.6 sec

INFO - 2026-09-29T23:37:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9449 downloaded in 8.1 sec

INFO - 2026-09-29T23:37:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:37:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:37:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:37:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9480 downloaded in 8.4 sec

INFO - 2026-09-29T23:38:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9455 downloaded in 8.0 sec

INFO - 2026-09-29T23:38:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9454 downloaded in 8.5 sec

INFO - 2026-09-29T23:38:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9453 downloaded in 8.3 sec

INFO - 2026-09-29T23:38:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9452 downloaded in 8.5 sec

INFO - 2026-09-29T23:38:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9447 downloaded in 8.4 sec

INFO - 2026-09-29T23:38:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9446 downloaded in 8.5 sec

INFO - 2026-09-29T23:38:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:38:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:38:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:38:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9445 downloaded in 8.5 sec

INFO - 2026-09-29T23:39:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9444 downloaded in 12.3 sec

INFO - 2026-09-29T23:39:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9443 downloaded in 8.6 sec

INFO - 2026-09-29T23:39:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9442 downloaded in 8.2 sec

INFO - 2026-09-29T23:39:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9441 downloaded in 8.4 sec

INFO - 2026-09-29T23:39:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9439 downloaded in 8.6 sec

INFO - 2026-09-29T23:39:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:39:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9438 downloaded in 8.3 sec

INFO - 2026-09-29T23:39:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:39:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:39:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9436 downloaded in 8.4 sec

INFO - 2026-09-29T23:40:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9435 downloaded in 8.3 sec

INFO - 2026-09-29T23:40:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9434 downloaded in 8.4 sec

INFO - 2026-09-29T23:40:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9433 downloaded in 8.3 sec

INFO - 2026-09-29T23:40:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9432 downloaded in 8.5 sec

INFO - 2026-09-29T23:40:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9430 downloaded in 8.2 sec

INFO - 2026-09-29T23:40:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:40:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:40:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:40:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9429 downloaded in 12.6 sec

INFO - 2026-09-29T23:41:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9428 downloaded in 8.2 sec

INFO - 2026-09-29T23:41:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9427 downloaded in 8.3 sec

INFO - 2026-09-29T23:41:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9426 downloaded in 8.5 sec

INFO - 2026-09-29T23:41:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9424 downloaded in 8.2 sec

INFO - 2026-09-29T23:41:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9423 downloaded in 8.3 sec

INFO - 2026-09-29T23:41:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9422 downloaded in 8.4 sec

INFO - 2026-09-29T23:41:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:41:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:41:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:41:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9421 downloaded in 8.5 sec

INFO - 2026-09-29T23:42:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9420 downloaded in 7.9 sec

INFO - 2026-09-29T23:42:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9419 downloaded in 8.6 sec

INFO - 2026-09-29T23:42:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9418 downloaded in 8.2 sec

INFO - 2026-09-29T23:42:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9417 downloaded in 8.2 sec

INFO - 2026-09-29T23:42:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9416 downloaded in 12.9 sec

INFO - 2026-09-29T23:42:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:42:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9415 downloaded in 8.5 sec

INFO - 2026-09-29T23:42:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:42:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:42:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9414 downloaded in 8.1 sec

INFO - 2026-09-29T23:43:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9413 downloaded in 8.5 sec

INFO - 2026-09-29T23:43:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9411 downloaded in 8.6 sec

INFO - 2026-09-29T23:43:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9410 downloaded in 8.3 sec

INFO - 2026-09-29T23:43:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9431 downloaded in 8.5 sec

INFO - 2026-09-29T23:43:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9408 downloaded in 8.1 sec

INFO - 2026-09-29T23:43:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:43:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9407 downloaded in 8.5 sec

INFO - 2026-09-29T23:43:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:43:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:43:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9403 downloaded in 8.4 sec

INFO - 2026-09-29T23:44:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9401 downloaded in 8.2 sec

INFO - 2026-09-29T23:44:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9400 downloaded in 8.7 sec

INFO - 2026-09-29T23:44:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9399 downloaded in 12.8 sec

INFO - 2026-09-29T23:44:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9398 downloaded in 8.4 sec

INFO - 2026-09-29T23:44:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9396 downloaded in 8.3 sec

INFO - 2026-09-29T23:44:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:44:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:44:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:44:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9395 downloaded in 8.2 sec

INFO - 2026-09-29T23:45:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9394 downloaded in 8.3 sec

INFO - 2026-09-29T23:45:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9393 downloaded in 8.2 sec

INFO - 2026-09-29T23:45:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9392 downloaded in 8.8 sec

INFO - 2026-09-29T23:45:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9391 downloaded in 8.6 sec

INFO - 2026-09-29T23:45:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9390 downloaded in 8.1 sec

INFO - 2026-09-29T23:45:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9388 downloaded in 8.3 sec

INFO - 2026-09-29T23:45:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:45:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:45:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:45:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9387 downloaded in 8.3 sec

INFO - 2026-09-29T23:46:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9386 downloaded in 8.3 sec

INFO - 2026-09-29T23:46:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9385 downloaded in 12.4 sec

INFO - 2026-09-29T23:46:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9384 downloaded in 8.6 sec

INFO - 2026-09-29T23:46:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9383 downloaded in 8.3 sec

INFO - 2026-09-29T23:46:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9382 downloaded in 8.6 sec

INFO - 2026-09-29T23:46:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:46:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9381 downloaded in 8.4 sec

INFO - 2026-09-29T23:46:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:46:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:46:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9380 downloaded in 8.5 sec

INFO - 2026-09-29T23:47:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9379 downloaded in 8.6 sec

INFO - 2026-09-29T23:47:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9377 downloaded in 8.4 sec

INFO - 2026-09-29T23:47:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9376 downloaded in 8.4 sec

INFO - 2026-09-29T23:47:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9375 downloaded in 8.3 sec

INFO - 2026-09-29T23:47:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9374 downloaded in 8.4 sec

INFO - 2026-09-29T23:47:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:47:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9373 downloaded in 8.4 sec

INFO - 2026-09-29T23:47:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:47:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:47:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9372 downloaded in 8.6 sec

INFO - 2026-09-29T23:48:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9371 downloaded in 13.5 sec

INFO - 2026-09-29T23:48:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9370 downloaded in 8.6 sec

INFO - 2026-09-29T23:48:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9368 downloaded in 8.5 sec

INFO - 2026-09-29T23:48:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9367 downloaded in 8.0 sec

INFO - 2026-09-29T23:48:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:48:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9366 downloaded in 8.3 sec

INFO - 2026-09-29T23:48:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:48:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:48:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9364 downloaded in 8.7 sec

INFO - 2026-09-29T23:49:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9397 downloaded in 8.5 sec

INFO - 2026-09-29T23:49:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9409 downloaded in 8.3 sec

INFO - 2026-09-29T23:49:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9369 downloaded in 8.6 sec

INFO - 2026-09-29T23:49:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9361 downloaded in 8.1 sec

INFO - 2026-09-29T23:49:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9360 downloaded in 8.5 sec

INFO - 2026-09-29T23:49:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:49:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9359 downloaded in 12.5 sec

INFO - 2026-09-29T23:49:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:49:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:49:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9363 downloaded in 8.2 sec

INFO - 2026-09-29T23:50:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9405 downloaded in 8.7 sec

INFO - 2026-09-29T23:50:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9358 downloaded in 8.3 sec

INFO - 2026-09-29T23:50:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8584 downloaded in 8.3 sec

INFO - 2026-09-29T23:50:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8583 downloaded in 8.6 sec

INFO - 2026-09-29T23:50:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8585 downloaded in 8.3 sec

INFO - 2026-09-29T23:50:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:50:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8569 downloaded in 8.3 sec

INFO - 2026-09-29T23:50:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:50:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:50:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8570 downloaded in 8.5 sec

INFO - 2026-09-29T23:51:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10051 downloaded in 8.5 sec

INFO - 2026-09-29T23:51:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9092 downloaded in 8.2 sec

INFO - 2026-09-29T23:51:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10040 downloaded in 8.6 sec

INFO - 2026-09-29T23:51:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10045 downloaded in 13.4 sec

INFO - 2026-09-29T23:51:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:51:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10016 downloaded in 8.6 sec

INFO - 2026-09-29T23:51:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:51:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:51:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10055 downloaded in 8.3 sec

INFO - 2026-09-29T23:52:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10019 downloaded in 8.4 sec

INFO - 2026-09-29T23:52:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10072 downloaded in 8.6 sec

INFO - 2026-09-29T23:52:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10020 downloaded in 8.2 sec

INFO - 2026-09-29T23:52:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10037 downloaded in 8.4 sec

INFO - 2026-09-29T23:52:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10022 downloaded in 8.7 sec

INFO - 2026-09-29T23:52:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:52:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10046 downloaded in 8.4 sec

INFO - 2026-09-29T23:52:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:52:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:52:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10054 downloaded in 8.4 sec

INFO - 2026-09-29T23:53:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10018 downloaded in 8.2 sec

INFO - 2026-09-29T23:53:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10050 downloaded in 8.5 sec

INFO - 2026-09-29T23:53:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10009 downloaded in 13.4 sec

INFO - 2026-09-29T23:53:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10011 downloaded in 8.5 sec

INFO - 2026-09-29T23:53:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:53:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10013 downloaded in 9.4 sec

INFO - 2026-09-29T23:53:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:53:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:53:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8773 downloaded in 8.6 sec

INFO - 2026-09-29T23:54:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10012 downloaded in 8.8 sec

INFO - 2026-09-29T23:54:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10014 downloaded in 9.4 sec

INFO - 2026-09-29T23:54:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10038 downloaded in 8.4 sec

INFO - 2026-09-29T23:54:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10021 downloaded in 8.2 sec

INFO - 2026-09-29T23:54:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10041 downloaded in 8.4 sec

INFO - 2026-09-29T23:54:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:54:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10039 downloaded in 8.6 sec

INFO - 2026-09-29T23:54:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:54:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:54:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10052 downloaded in 8.1 sec

INFO - 2026-09-29T23:55:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10048 downloaded in 8.6 sec

INFO - 2026-09-29T23:55:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10042 downloaded in 13.7 sec

INFO - 2026-09-29T23:55:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10010 downloaded in 8.5 sec

INFO - 2026-09-29T23:55:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10053 downloaded in 8.0 sec

INFO - 2026-09-29T23:55:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10015 downloaded in 9.3 sec

INFO - 2026-09-29T23:55:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:55:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:55:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:55:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10145 downloaded in 8.7 sec

INFO - 2026-09-29T23:56:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10017 downloaded in 8.4 sec

INFO - 2026-09-29T23:56:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9197 downloaded in 8.3 sec

INFO - 2026-09-29T23:56:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10209 downloaded in 8.4 sec

INFO - 2026-09-29T23:56:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14360 downloaded in 8.5 sec

INFO - 2026-09-29T23:56:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14352 downloaded in 8.5 sec

INFO - 2026-09-29T23:56:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14359 downloaded in 8.4 sec

INFO - 2026-09-29T23:56:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:56:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:56:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:56:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14355 downloaded in 8.2 sec

INFO - 2026-09-29T23:57:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14356 downloaded in 13.3 sec

INFO - 2026-09-29T23:57:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14351 downloaded in 8.1 sec

INFO - 2026-09-29T23:57:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14358 downloaded in 8.5 sec

INFO - 2026-09-29T23:57:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14354 downloaded in 9.0 sec

INFO - 2026-09-29T23:57:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14357 downloaded in 8.2 sec

INFO - 2026-09-29T23:57:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:57:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14362 downloaded in 8.5 sec

INFO - 2026-09-29T23:57:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:57:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:57:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14361 downloaded in 8.5 sec

INFO - 2026-09-29T23:58:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9956 downloaded in 8.4 sec

INFO - 2026-09-29T23:58:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9960 downloaded in 8.4 sec

INFO - 2026-09-29T23:58:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10036 downloaded in 8.2 sec

INFO - 2026-09-29T23:58:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9958 downloaded in 8.8 sec

INFO - 2026-09-29T23:58:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:58:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9959 downloaded in 8.4 sec

INFO - 2026-09-29T23:58:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:58:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:58:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9957 downloaded in 12.7 sec

INFO - 2026-09-29T23:59:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8631 downloaded in 8.8 sec

INFO - 2026-09-29T23:59:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8632 downloaded in 8.7 sec

INFO - 2026-09-29T23:59:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8627 downloaded in 8.6 sec

INFO - 2026-09-29T23:59:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8628 downloaded in 8.8 sec

INFO - 2026-09-29T23:59:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8636 downloaded in 8.5 sec

INFO - 2026-09-29T23:59:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-29T23:59:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8629 downloaded in 8.8 sec

INFO - 2026-09-29T23:59:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-29T23:59:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-29T23:59:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8626 downloaded in 8.7 sec

INFO - 2026-09-30T00:00:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8534 downloaded in 8.8 sec

INFO - 2026-09-30T00:00:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8633 downloaded in 8.6 sec

INFO - 2026-09-30T00:00:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8638 downloaded in 8.6 sec

INFO - 2026-09-30T00:00:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8637 downloaded in 8.8 sec

INFO - 2026-09-30T00:00:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:00:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8634 downloaded in 8.6 sec

INFO - 2026-09-30T00:00:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:00:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:00:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8635 downloaded in 13.0 sec

INFO - 2026-09-30T00:01:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8630 downloaded in 8.9 sec

INFO - 2026-09-30T00:01:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8624 downloaded in 8.7 sec

INFO - 2026-09-30T00:01:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8625 downloaded in 9.0 sec

INFO - 2026-09-30T00:01:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8597 downloaded in 8.3 sec

INFO - 2026-09-30T00:01:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8446 downloaded in 9.2 sec

INFO - 2026-09-30T00:01:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:01:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7344 downloaded in 8.6 sec

INFO - 2026-09-30T00:01:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:01:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:01:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8591 downloaded in 8.5 sec

INFO - 2026-09-30T00:02:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6959 downloaded in 8.9 sec

INFO - 2026-09-30T00:02:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8786 downloaded in 8.6 sec

INFO - 2026-09-30T00:02:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8753 downloaded in 8.5 sec

INFO - 2026-09-30T00:02:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8783 downloaded in 12.2 sec

INFO - 2026-09-30T00:02:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8754 downloaded in 8.5 sec

INFO - 2026-09-30T00:02:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:02:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:02:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:02:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8781 downloaded in 8.3 sec

INFO - 2026-09-30T00:03:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8779 downloaded in 8.5 sec

INFO - 2026-09-30T00:03:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8778 downloaded in 9.3 sec

INFO - 2026-09-30T00:03:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8777 downloaded in 8.5 sec

INFO - 2026-09-30T00:03:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8774 downloaded in 8.6 sec

INFO - 2026-09-30T00:03:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8776 downloaded in 8.7 sec

INFO - 2026-09-30T00:03:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:03:53Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8775 downloaded in 8.9 sec

INFO - 2026-09-30T00:03:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:03:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:03:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8780 downloaded in 8.2 sec

INFO - 2026-09-30T00:04:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8752 downloaded in 8.6 sec

INFO - 2026-09-30T00:04:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8785 downloaded in 8.6 sec

INFO - 2026-09-30T00:04:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6965 downloaded in 13.4 sec

INFO - 2026-09-30T00:04:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8782 downloaded in 8.5 sec

INFO - 2026-09-30T00:04:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8787 downloaded in 8.6 sec

INFO - 2026-09-30T00:04:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:04:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:04:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:04:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8784 downloaded in 8.4 sec

INFO - 2026-09-30T00:05:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6497 downloaded in 8.1 sec

INFO - 2026-09-30T00:05:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8796 downloaded in 8.4 sec

INFO - 2026-09-30T00:05:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8795 downloaded in 8.8 sec

INFO - 2026-09-30T00:05:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8797 downloaded in 8.7 sec

INFO - 2026-09-30T00:05:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8798 downloaded in 8.3 sec

INFO - 2026-09-30T00:05:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:05:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7178 downloaded in 8.8 sec

INFO - 2026-09-30T00:05:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:05:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:05:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8587 downloaded in 8.6 sec

INFO - 2026-09-30T00:06:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6618 downloaded in 8.6 sec

INFO - 2026-09-30T00:06:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7176 downloaded in 12.1 sec

INFO - 2026-09-30T00:06:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6152 downloaded in 8.6 sec

INFO - 2026-09-30T00:06:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 10223 downloaded in 8.4 sec

INFO - 2026-09-30T00:06:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7944 downloaded in 8.4 sec

INFO - 2026-09-30T00:06:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:06:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7945 downloaded in 8.4 sec

INFO - 2026-09-30T00:06:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:06:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:06:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7946 downloaded in 8.3 sec

INFO - 2026-09-30T00:07:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7948 downloaded in 8.6 sec

INFO - 2026-09-30T00:07:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7921 downloaded in 9.1 sec

INFO - 2026-09-30T00:07:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7940 downloaded in 8.5 sec

INFO - 2026-09-30T00:07:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7950 downloaded in 8.3 sec

INFO - 2026-09-30T00:07:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7947 downloaded in 8.3 sec

INFO - 2026-09-30T00:07:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:07:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:07:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:07:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7951 downloaded in 8.3 sec

INFO - 2026-09-30T00:08:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7939 downloaded in 12.7 sec

INFO - 2026-09-30T00:08:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7952 downloaded in 8.4 sec

INFO - 2026-09-30T00:08:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7954 downloaded in 8.6 sec

INFO - 2026-09-30T00:08:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7955 downloaded in 8.4 sec

INFO - 2026-09-30T00:08:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7956 downloaded in 8.4 sec

INFO - 2026-09-30T00:08:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:08:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7938 downloaded in 9.1 sec

INFO - 2026-09-30T00:08:56Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:08:56Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:08:56Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7957 downloaded in 8.5 sec

INFO - 2026-09-30T00:09:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7958 downloaded in 8.3 sec

INFO - 2026-09-30T00:09:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:20Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7949 downloaded in 8.5 sec

INFO - 2026-09-30T00:09:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7924 downloaded in 8.7 sec

INFO - 2026-09-30T00:09:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7929 downloaded in 9.0 sec

INFO - 2026-09-30T00:09:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7959 downloaded in 8.5 sec

INFO - 2026-09-30T00:09:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:09:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:09:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:09:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7925 downloaded in 11.8 sec

INFO - 2026-09-30T00:10:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7923 downloaded in 8.3 sec

INFO - 2026-09-30T00:10:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7926 downloaded in 8.9 sec

INFO - 2026-09-30T00:10:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7922 downloaded in 8.4 sec

INFO - 2026-09-30T00:10:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7927 downloaded in 8.9 sec

INFO - 2026-09-30T00:10:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7928 downloaded in 9.0 sec

INFO - 2026-09-30T00:10:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:10:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7930 downloaded in 8.9 sec

INFO - 2026-09-30T00:10:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:10:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:10:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7941 downloaded in 8.4 sec

INFO - 2026-09-30T00:11:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7942 downloaded in 8.4 sec

INFO - 2026-09-30T00:11:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7943 downloaded in 8.8 sec

INFO - 2026-09-30T00:11:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7357 downloaded in 8.6 sec

INFO - 2026-09-30T00:11:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6161 downloaded in 8.7 sec

INFO - 2026-09-30T00:11:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6162 downloaded in 12.8 sec

INFO - 2026-09-30T00:11:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:11:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:11:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:11:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6386 downloaded in 8.7 sec

INFO - 2026-09-30T00:12:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6387 downloaded in 9.0 sec

INFO - 2026-09-30T00:12:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6388 downloaded in 8.6 sec

INFO - 2026-09-30T00:12:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6390 downloaded in 8.6 sec

INFO - 2026-09-30T00:12:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7400 downloaded in 8.8 sec

INFO - 2026-09-30T00:12:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7397 downloaded in 8.7 sec

INFO - 2026-09-30T00:12:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:12:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7396 downloaded in 8.6 sec

INFO - 2026-09-30T00:12:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:12:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:12:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7395 downloaded in 8.5 sec

INFO - 2026-09-30T00:13:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7394 downloaded in 8.8 sec

INFO - 2026-09-30T00:13:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7393 downloaded in 8.7 sec

INFO - 2026-09-30T00:13:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7392 downloaded in 8.8 sec

INFO - 2026-09-30T00:13:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7391 downloaded in 13.6 sec

INFO - 2026-09-30T00:13:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7389 downloaded in 8.7 sec

INFO - 2026-09-30T00:13:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:13:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:13:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:13:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7382 downloaded in 8.7 sec

INFO - 2026-09-30T00:14:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7381 downloaded in 9.0 sec

INFO - 2026-09-30T00:14:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7380 downloaded in 8.6 sec

INFO - 2026-09-30T00:14:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7379 downloaded in 8.5 sec

INFO - 2026-09-30T00:14:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7377 downloaded in 8.6 sec

INFO - 2026-09-30T00:14:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7388 downloaded in 8.6 sec

INFO - 2026-09-30T00:14:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:14:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7387 downloaded in 8.7 sec

INFO - 2026-09-30T00:14:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:14:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:14:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7384 downloaded in 8.6 sec

INFO - 2026-09-30T00:15:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6334 downloaded in 8.7 sec

INFO - 2026-09-30T00:15:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7386 downloaded in 8.7 sec

INFO - 2026-09-30T00:15:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7385 downloaded in 12.8 sec

INFO - 2026-09-30T00:15:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7383 downloaded in 8.6 sec

INFO - 2026-09-30T00:15:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7373 downloaded in 9.0 sec

INFO - 2026-09-30T00:15:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:15:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:15:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:15:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7372 downloaded in 8.9 sec

INFO - 2026-09-30T00:16:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7370 downloaded in 8.6 sec

INFO - 2026-09-30T00:16:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7369 downloaded in 8.7 sec

INFO - 2026-09-30T00:16:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7368 downloaded in 8.8 sec

INFO - 2026-09-30T00:16:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7367 downloaded in 8.7 sec

INFO - 2026-09-30T00:16:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7366 downloaded in 8.5 sec

INFO - 2026-09-30T00:16:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:16:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7363 downloaded in 8.6 sec

INFO - 2026-09-30T00:16:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:16:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:16:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7362 downloaded in 8.8 sec

INFO - 2026-09-30T00:17:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7356 downloaded in 8.6 sec

INFO - 2026-09-30T00:17:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7355 downloaded in 12.3 sec

INFO - 2026-09-30T00:17:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7354 downloaded in 9.0 sec

INFO - 2026-09-30T00:17:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7353 downloaded in 8.7 sec

INFO - 2026-09-30T00:17:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7352 downloaded in 9.0 sec

INFO - 2026-09-30T00:17:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:17:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:17:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:17:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7348 downloaded in 9.0 sec

INFO - 2026-09-30T00:18:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7349 downloaded in 8.6 sec

INFO - 2026-09-30T00:18:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7347 downloaded in 8.6 sec

INFO - 2026-09-30T00:18:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7351 downloaded in 8.8 sec

INFO - 2026-09-30T00:18:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7350 downloaded in 8.6 sec

INFO - 2026-09-30T00:18:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7358 downloaded in 8.4 sec

INFO - 2026-09-30T00:18:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:18:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6160 downloaded in 8.7 sec

INFO - 2026-09-30T00:18:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:18:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:18:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7463 downloaded in 8.8 sec

INFO - 2026-09-30T00:19:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7364 downloaded in 13.1 sec

INFO - 2026-09-30T00:19:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7361 downloaded in 8.5 sec

INFO - 2026-09-30T00:19:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7360 downloaded in 8.8 sec

INFO - 2026-09-30T00:19:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7371 downloaded in 8.8 sec

INFO - 2026-09-30T00:19:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7846 downloaded in 8.7 sec

INFO - 2026-09-30T00:19:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:19:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:19:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:19:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7854 downloaded in 8.7 sec

INFO - 2026-09-30T00:20:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7465 downloaded in 8.9 sec

INFO - 2026-09-30T00:20:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7467 downloaded in 8.7 sec

INFO - 2026-09-30T00:20:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7365 downloaded in 8.6 sec

INFO - 2026-09-30T00:20:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7466 downloaded in 8.9 sec

INFO - 2026-09-30T00:20:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7376 downloaded in 8.6 sec

INFO - 2026-09-30T00:20:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:20:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7407 downloaded in 8.7 sec

INFO - 2026-09-30T00:20:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:20:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:20:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7406 downloaded in 13.3 sec

INFO - 2026-09-30T00:21:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7405 downloaded in 9.2 sec

INFO - 2026-09-30T00:21:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7404 downloaded in 8.7 sec

INFO - 2026-09-30T00:21:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7403 downloaded in 8.6 sec

INFO - 2026-09-30T00:21:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7399 downloaded in 9.0 sec

INFO - 2026-09-30T00:21:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:21:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7402 downloaded in 9.0 sec

INFO - 2026-09-30T00:21:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:21:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:21:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6535 downloaded in 9.0 sec

INFO - 2026-09-30T00:22:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6536 downloaded in 9.1 sec

INFO - 2026-09-30T00:22:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6534 downloaded in 8.8 sec

INFO - 2026-09-30T00:22:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6698 downloaded in 9.0 sec

INFO - 2026-09-30T00:22:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6703 downloaded in 8.8 sec

INFO - 2026-09-30T00:22:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:22:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7855 downloaded in 8.8 sec

INFO - 2026-09-30T00:22:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:22:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:22:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6702 downloaded in 14.0 sec

INFO - 2026-09-30T00:23:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6700 downloaded in 9.3 sec

INFO - 2026-09-30T00:23:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6655 downloaded in 11.4 sec

INFO - 2026-09-30T00:23:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6668 downloaded in 8.7 sec

INFO - 2026-09-30T00:23:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6667 downloaded in 8.6 sec

INFO - 2026-09-30T00:23:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6666 downloaded in 8.9 sec

INFO - 2026-09-30T00:23:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:23:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:23:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:23:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6665 downloaded in 8.7 sec

INFO - 2026-09-30T00:24:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6664 downloaded in 8.8 sec

INFO - 2026-09-30T00:24:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6663 downloaded in 8.7 sec

INFO - 2026-09-30T00:24:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:24Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6660 downloaded in 9.1 sec

INFO - 2026-09-30T00:24:27Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:27Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:27Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:33Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6539 downloaded in 8.7 sec

INFO - 2026-09-30T00:24:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6659 downloaded in 9.0 sec

INFO - 2026-09-30T00:24:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:24:55Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6658 downloaded in 12.5 sec

INFO - 2026-09-30T00:24:58Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:24:58Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:24:58Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:04Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6657 downloaded in 8.6 sec

INFO - 2026-09-30T00:25:07Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:07Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:07Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6538 downloaded in 8.7 sec

INFO - 2026-09-30T00:25:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6533 downloaded in 8.6 sec

INFO - 2026-09-30T00:25:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6331 downloaded in 8.9 sec

INFO - 2026-09-30T00:25:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7378 downloaded in 9.0 sec

INFO - 2026-09-30T00:25:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6656 downloaded in 8.6 sec

INFO - 2026-09-30T00:25:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:25:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:25:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:25:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6332 downloaded in 8.8 sec

INFO - 2026-09-30T00:26:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6338 downloaded in 9.0 sec

INFO - 2026-09-30T00:26:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6337 downloaded in 8.9 sec

INFO - 2026-09-30T00:26:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6336 downloaded in 8.7 sec

INFO - 2026-09-30T00:26:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6335 downloaded in 8.7 sec

INFO - 2026-09-30T00:26:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6333 downloaded in 13.7 sec

INFO - 2026-09-30T00:26:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:26:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:26:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:26:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6339 downloaded in 8.6 sec

INFO - 2026-09-30T00:27:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6532 downloaded in 9.0 sec

INFO - 2026-09-30T00:27:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6661 downloaded in 8.6 sec

INFO - 2026-09-30T00:27:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6610 downloaded in 8.7 sec

INFO - 2026-09-30T00:27:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6699 downloaded in 8.9 sec

INFO - 2026-09-30T00:27:36Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:36Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:36Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7468 downloaded in 8.8 sec

INFO - 2026-09-30T00:27:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7398 downloaded in 8.7 sec

INFO - 2026-09-30T00:27:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:27:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:27:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:27:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7374 downloaded in 8.5 sec

INFO - 2026-09-30T00:28:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6701 downloaded in 8.9 sec

INFO - 2026-09-30T00:28:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:17Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6391 downloaded in 8.6 sec

INFO - 2026-09-30T00:28:20Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:20Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:20Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6389 downloaded in 8.6 sec

INFO - 2026-09-30T00:28:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6654 downloaded in 13.7 sec

INFO - 2026-09-30T00:28:43Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:43Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:43Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6662 downloaded in 8.8 sec

INFO - 2026-09-30T00:28:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:28:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:28:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:28:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7375 downloaded in 8.7 sec

INFO - 2026-09-30T00:29:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7359 downloaded in 8.9 sec

INFO - 2026-09-30T00:29:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7390 downloaded in 9.1 sec

INFO - 2026-09-30T00:29:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7401 downloaded in 8.7 sec

INFO - 2026-09-30T00:29:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7464 downloaded in 8.5 sec

INFO - 2026-09-30T00:29:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:43Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8451 downloaded in 8.8 sec

INFO - 2026-09-30T00:29:46Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:46Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:46Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:29:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8450 downloaded in 8.8 sec

INFO - 2026-09-30T00:29:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:29:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:29:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13596 downloaded in 8.7 sec

INFO - 2026-09-30T00:30:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7849 downloaded in 8.3 sec

INFO - 2026-09-30T00:30:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7850 downloaded in 8.7 sec

INFO - 2026-09-30T00:30:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7848 downloaded in 13.5 sec

INFO - 2026-09-30T00:30:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7847 downloaded in 8.5 sec

INFO - 2026-09-30T00:30:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14188 downloaded in 8.7 sec

INFO - 2026-09-30T00:30:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:30:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:30:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:30:58Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7851 downloaded in 8.7 sec

INFO - 2026-09-30T00:31:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7184 downloaded in 8.6 sec

INFO - 2026-09-30T00:31:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 14317 downloaded in 8.7 sec

INFO - 2026-09-30T00:31:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7899 downloaded in 8.6 sec

INFO - 2026-09-30T00:31:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7901 downloaded in 8.6 sec

INFO - 2026-09-30T00:31:37Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:37Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:37Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:42Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7898 downloaded in 8.1 sec

INFO - 2026-09-30T00:31:45Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:45Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:51Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7896 downloaded in 8.5 sec

INFO - 2026-09-30T00:31:54Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:31:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:31:54Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:31:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7895 downloaded in 8.1 sec

INFO - 2026-09-30T00:32:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7897 downloaded in 8.4 sec

INFO - 2026-09-30T00:32:11Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:11Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:11Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8205 downloaded in 13.0 sec

INFO - 2026-09-30T00:32:24Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:24Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:30Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8213 downloaded in 8.6 sec

INFO - 2026-09-30T00:32:33Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:33Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8206 downloaded in 8.5 sec

INFO - 2026-09-30T00:32:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8210 downloaded in 8.8 sec

INFO - 2026-09-30T00:32:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:32:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8199 downloaded in 8.6 sec

INFO - 2026-09-30T00:32:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:32:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:32:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8212 downloaded in 8.3 sec

INFO - 2026-09-30T00:33:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8207 downloaded in 8.5 sec

INFO - 2026-09-30T00:33:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8217 downloaded in 8.5 sec

INFO - 2026-09-30T00:33:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8214 downloaded in 8.4 sec

INFO - 2026-09-30T00:33:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8215 downloaded in 8.5 sec

INFO - 2026-09-30T00:33:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8211 downloaded in 8.6 sec

INFO - 2026-09-30T00:33:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:33:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:33:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:33:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8204 downloaded in 8.6 sec

INFO - 2026-09-30T00:34:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8208 downloaded in 13.6 sec

INFO - 2026-09-30T00:34:14Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:14Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8203 downloaded in 8.3 sec

INFO - 2026-09-30T00:34:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8202 downloaded in 8.6 sec

INFO - 2026-09-30T00:34:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:37Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8201 downloaded in 8.6 sec

INFO - 2026-09-30T00:34:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:46Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6743 downloaded in 8.3 sec

INFO - 2026-09-30T00:34:49Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:49Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:49Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:34:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8209 downloaded in 8.3 sec

INFO - 2026-09-30T00:34:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:34:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:34:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:03Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6300 downloaded in 8.7 sec

INFO - 2026-09-30T00:35:06Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:06Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:06Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:12Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8115 downloaded in 8.6 sec

INFO - 2026-09-30T00:35:15Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:15Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:15Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:21Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6348 downloaded in 8.3 sec

INFO - 2026-09-30T00:35:23Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:23Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:23Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:29Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8493 downloaded in 8.5 sec

INFO - 2026-09-30T00:35:32Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:32Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:32Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:38Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 7999 downloaded in 8.8 sec

INFO - 2026-09-30T00:35:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:35:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6632 downloaded in 8.5 sec

INFO - 2026-09-30T00:35:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:35:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:35:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:00Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6635 downloaded in 13.0 sec

INFO - 2026-09-30T00:36:03Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:03Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:03Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:09Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6634 downloaded in 8.5 sec

INFO - 2026-09-30T00:36:12Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:12Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:12Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8501 downloaded in 8.6 sec

INFO - 2026-09-30T00:36:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:26Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8013 downloaded in 8.4 sec

INFO - 2026-09-30T00:36:29Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:29Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:29Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:35Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6628 downloaded in 8.6 sec

INFO - 2026-09-30T00:36:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:44Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8500 downloaded in 8.4 sec

INFO - 2026-09-30T00:36:47Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:47Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:47Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:36:52Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8499 downloaded in 8.4 sec

INFO - 2026-09-30T00:36:55Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:36:55Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:36:55Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:01Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8497 downloaded in 8.2 sec

INFO - 2026-09-30T00:37:04Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:04Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:04Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:10Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6630 downloaded in 8.6 sec

INFO - 2026-09-30T00:37:13Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:13Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:13Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:18Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8496 downloaded in 8.4 sec

INFO - 2026-09-30T00:37:21Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:21Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:21Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:27Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8495 downloaded in 8.5 sec

INFO - 2026-09-30T00:37:30Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:30Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:30Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6633 downloaded in 8.6 sec

INFO - 2026-09-30T00:37:39Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:39Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:39Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:49Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6631 downloaded in 12.9 sec

INFO - 2026-09-30T00:37:52Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:37:52Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:37:52Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:37:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8498 downloaded in 8.1 sec

INFO - 2026-09-30T00:38:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6629 downloaded in 8.9 sec

INFO - 2026-09-30T00:38:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:15Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8012 downloaded in 8.4 sec

INFO - 2026-09-30T00:38:18Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:18Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 8494 downloaded in 8.2 sec

INFO - 2026-09-30T00:38:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13650 downloaded in 8.7 sec

INFO - 2026-09-30T00:38:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 13651 downloaded in 8.7 sec

INFO - 2026-09-30T00:38:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 6617 downloaded in 8.7 sec

INFO - 2026-09-30T00:38:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:38:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:38:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:38:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9216 downloaded in 8.5 sec

INFO - 2026-09-30T00:39:02Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:02Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:02Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:08Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9214 downloaded in 8.5 sec

INFO - 2026-09-30T00:39:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9212 downloaded in 8.7 sec

INFO - 2026-09-30T00:39:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9211 downloaded in 8.4 sec

INFO - 2026-09-30T00:39:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:28Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:34Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9210 downloaded in 9.1 sec

INFO - 2026-09-30T00:39:38Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:38Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9209 downloaded in 13.6 sec

INFO - 2026-09-30T00:39:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:39:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:39:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:39:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9208 downloaded in 8.6 sec

INFO - 2026-09-30T00:40:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:06Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9207 downloaded in 8.4 sec

INFO - 2026-09-30T00:40:09Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:09Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:09Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:14Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9206 downloaded in 8.6 sec

INFO - 2026-09-30T00:40:17Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:17Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:17Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:23Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9205 downloaded in 8.5 sec

INFO - 2026-09-30T00:40:26Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:26Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:26Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:32Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9204 downloaded in 8.5 sec

INFO - 2026-09-30T00:40:35Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:35Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:35Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:41Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9203 downloaded in 8.8 sec

INFO - 2026-09-30T00:40:44Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:44Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:44Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:50Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9201 downloaded in 8.6 sec

INFO - 2026-09-30T00:40:53Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:40:53Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:40:53Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:40:59Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9202 downloaded in 8.7 sec

INFO - 2026-09-30T00:41:01Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:01Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:01Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:07Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9270 downloaded in 8.6 sec

INFO - 2026-09-30T00:41:10Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:10Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:10Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:16Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9271 downloaded in 8.4 sec

INFO - 2026-09-30T00:41:19Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:19Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:19Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:25Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9335 downloaded in 8.5 sec

INFO - 2026-09-30T00:41:28Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:28Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:33Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:39Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9357 downloaded in 13.7 sec

INFO - 2026-09-30T00:41:41Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:41Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:41Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:47Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9272 downloaded in 8.5 sec

INFO - 2026-09-30T00:41:50Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:50Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:50Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:41:56Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9317 downloaded in 8.5 sec

INFO - 2026-09-30T00:41:59Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:41:59Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:41:59Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9312 downloaded in 8.4 sec

INFO - 2026-09-30T00:42:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:13Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9311 downloaded in 8.5 sec

INFO - 2026-09-30T00:42:16Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:16Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:16Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:22Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9339 downloaded in 8.7 sec

INFO - 2026-09-30T00:42:25Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:25Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:25Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:31Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9316 downloaded in 8.3 sec

INFO - 2026-09-30T00:42:34Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:34Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:34Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:40Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9315 downloaded in 8.5 sec

INFO - 2026-09-30T00:42:42Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:42Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:42Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:48Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9314 downloaded in 8.4 sec

INFO - 2026-09-30T00:42:51Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:42:51Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:42:51Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:42:57Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9313 downloaded in 8.3 sec

INFO - 2026-09-30T00:43:00Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:00Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:00Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:05Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9309 downloaded in 8.3 sec

INFO - 2026-09-30T00:43:08Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:08Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:08Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:19Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9308 downloaded in 13.8 sec

INFO - 2026-09-30T00:43:22Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:22Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:22Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:28Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9307 downloaded in 8.4 sec

INFO - 2026-09-30T00:43:31Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:31Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:36Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9306 downloaded in 8.5 sec

INFO - 2026-09-30T00:43:40Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:40Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:45Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9305 downloaded in 8.5 sec

INFO - 2026-09-30T00:43:48Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:48Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:43:54Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9304 downloaded in 8.4 sec

INFO - 2026-09-30T00:43:57Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:43:57Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:43:57Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:44:02Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9303 downloaded in 8.4 sec

INFO - 2026-09-30T00:44:05Z - Selected dataset version: "202311"
INFO:copernicusmarine:Selected dataset version: "202311"
INFO - 2026-09-30T00:44:05Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"
WARNING - 2026-09-30T00:44:05Z - Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
WARNING:copernicusmarine:Some of your subset selection [0.0, 1.0] for the depth dimension exceed the dataset coordinates [0.49402499198913574, 5727.9169921875]
INFO - 2026-09-30T00:44:11Z - Total size of the download: 18.16 KB.
INFO:copernicusmarine:Total size of the download: 18.16 KB.

Event 9302 downloaded in 8.3 sec